import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionSeedPrefixRowSource
import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionProgramStatementDescriptorSemantics

/-!
# Self-describing recursive program descriptors

Each program-wide recursive statement descriptor is prefixed with the exact
transition seed that produced it.  The resulting row remains generated by a
fixed polynomial-time TM2 from the raw verifier input, while exposing the
height, statement start, and public row base needed by a downstream concrete
interpreter.
-/

noncomputable section

namespace CLRS.Chapter34.Turing.CookLevin

open PolyBuilder

/-- Seed coordinates followed by all recursive program statement descriptors
for that same transition row. -/
noncomputable def
    verifierTransitionSelfDescribingProgramDescriptorSeedRowSource
    {Γ : Type} {L : Language Γ} (W : VerifierWitness L) :
    VerifierTransitionSeedRowSource W :=
  (verifierTransitionSeedPrefixRowSource W).append
    (verifierTransitionProgramStatementDescriptorSeedRowSource W)

/-- Exact row payload of the self-describing program source. -/
@[simp] theorem
    verifierTransitionSelfDescribingProgramDescriptorSeedRowSource_row
    {Γ : Type} {L : Language Γ} (W : VerifierWitness L)
    (seed : TransitionRowSeed) :
    (verifierTransitionSelfDescribingProgramDescriptorSeedRowSource W).row
        seed =
      encodeUnaryFrame [seed.height, seed.start, seed.rowBase] ++
        (verifierTransitionProgramStatementDescriptorSeedRowSource W).row
          seed := rfl

/-- Public marked family of self-describing program rows. -/
noncomputable def verifierTransitionSelfDescribingProgramDescriptorFamily
    {Γ : Type} {L : Language Γ} (W : VerifierWitness L)
    (input : List Γ) : UnaryFrameMarkedRowFamily :=
  (verifierTransitionSelfDescribingProgramDescriptorSeedRowSource W).family
    input

/-- Every self-describing output row is aligned with the canonical seed list. -/
theorem verifierTransitionSelfDescribingProgramDescriptorFamily_rows
    {Γ : Type} {L : Language Γ} (W : VerifierWitness L)
    (input : List Γ) :
    (verifierTransitionSelfDescribingProgramDescriptorFamily W input).rows =
      (verifierTransitionRowSeeds W input).map fun seed =>
        encodeUnaryFrame [seed.height, seed.start, seed.rowBase] ++
          (verifierTransitionProgramStatementDescriptorSeedRowSource W).row
            seed := by
  rw [verifierTransitionSelfDescribingProgramDescriptorFamily,
    (verifierTransitionSelfDescribingProgramDescriptorSeedRowSource W
      ).rows_eq]
  rfl

/-- The complete self-describing row has an independent explicit semantic
normal form: the seed triple followed by the canonical program-label fold. -/
theorem
    verifierTransitionSelfDescribingProgramDescriptorSeedRowSource_row_eq_semantics
    {Γ : Type} {L : Language Γ} (W : VerifierWitness L)
    (seed : TransitionRowSeed) :
    (verifierTransitionSelfDescribingProgramDescriptorSeedRowSource W).row
        seed =
      encodeUnaryFrame [seed.height, seed.start, seed.rowBase] ++
        transitionLabelListStatementNumericDescriptorRow W.machine.tm seed
          (TransitionAffineNat.const 2) (programLabels W.machine.tm) := by
  rw [
    verifierTransitionSelfDescribingProgramDescriptorSeedRowSource_row,
    verifierTransitionProgramStatementDescriptorSeedRowSource_row_eq]

/-- One fixed polynomial-time machine generates the seed-prefixed recursive
program descriptors directly from the raw verifier input. -/
noncomputable def
    verifierTransitionSelfDescribingProgramDescriptorFamily_computableInPolyTime
    {Γ : Type} {L : Language Γ} (W : VerifierWitness L) :
    _root_.Turing.TM2ComputableInPolyTime id
      encodeUnaryFrameMarkedRowFamily
      (verifierTransitionSelfDescribingProgramDescriptorFamily W) :=
  (verifierTransitionSelfDescribingProgramDescriptorSeedRowSource W
    ).computableInPolyTime

end CLRS.Chapter34.Turing.CookLevin
