import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.PolyBuilder.AffineExactlyOneStructuredRowSource
import Mathlib.Tactic

/-!
# Continuous compact exactly-one source for a runtime row family

This module closes the outer row loop of the compact one-hot source.  A fixed
controller repeatedly loads a runtime `(height, start, rowBase)` seed, runs the
complete structured-row controller, clears its three persistent counters, and
continues with the next seed.  Only the fixed label/state widths and fixed
stack alphabet widths occur in finite control.
-/

noncomputable section

open StateTransition

namespace CLRS.Chapter34.Turing.PolyBuilder

/-- Runtime data needed to generate one complete structured one-hot row. -/
structure AffineExactlyOneStructuredRowSeed where
  height : Nat
  start : Nat
  rowBase : Nat
deriving DecidableEq

/-- Delimiter-bearing input for one row seed. -/
def encodeAffineExactlyOneStructuredRowSeed
    (seed : AffineExactlyOneStructuredRowSeed) : List UnaryFrameSym :=
  encodeUnaryFrame [seed.height, seed.start, seed.rowBase]

/-- Concatenated runtime seed stream, with no additional sentinel. -/
def encodeAffineExactlyOneStructuredRowSeedFamily :
    List AffineExactlyOneStructuredRowSeed → List UnaryFrameSym
  | [] => []
  | seed :: rest =>
      encodeAffineExactlyOneStructuredRowSeed seed ++
        encodeAffineExactlyOneStructuredRowSeedFamily rest

/-- Canonical compact frame family generated by the runtime row seeds. -/
def affineExactlyOneStructuredRowFamilyFrames
    (labelWidth stateWidth : Nat) (cellCounts : List Nat) :
    List AffineExactlyOneStructuredRowSeed → List AffineExactlyOneFrame
  | [] => []
  | seed :: rest =>
      affineExactlyOneStructuredRowFrames labelWidth stateWidth cellCounts
          seed.height seed.start seed.rowBase ++
        affineExactlyOneStructuredRowFamilyFrames
          labelWidth stateWidth cellCounts rest

/-- Counter-clearing phases between adjacent runtime rows. -/
inductive AffineExactlyOneStructuredRowFamilyClearLabel
  | height | start | rowBase
deriving DecidableEq, Fintype

/-- Public terminal label of the embedded structured-row controller. -/
def affineExactlyOneStructuredRowFinishLabel
    (labelWidth stateWidth : Nat) (cellCounts : List Nat) :
    (affineExactlyOneStructuredRowRevProgram
      labelWidth stateWidth cellCounts).Label :=
  .inr (affineExactlyOneStackFamilyFinishLabel cellCounts)

private def structuredRowFamilyRelabelOp {Γ Δ Λ Μ : Type} (tag : Λ → Μ) :
    Op Γ Δ Λ → Op Γ Δ Μ
  | .pushOutput symbol next => .pushOutput symbol (tag next)
  | .pushWork₁ symbol next => .pushWork₁ symbol (tag next)
  | .pushWork₂ symbol next => .pushWork₂ symbol (tag next)
  | .moveInputWork₁ nextEmpty nextMoved =>
      .moveInputWork₁ (tag nextEmpty) (fun symbol => tag (nextMoved symbol))
  | .moveWork₁Input nextEmpty nextMoved =>
      .moveWork₁Input (tag nextEmpty) (fun symbol => tag (nextMoved symbol))
  | .moveInputWork₂ nextEmpty nextMoved =>
      .moveInputWork₂ (tag nextEmpty) (fun symbol => tag (nextMoved symbol))
  | .moveWork₂Input nextEmpty nextMoved =>
      .moveWork₂Input (tag nextEmpty) (fun symbol => tag (nextMoved symbol))
  | .moveWork₁Work₂ nextEmpty nextMoved =>
      .moveWork₁Work₂ (tag nextEmpty) (fun symbol => tag (nextMoved symbol))
  | .moveWork₂Work₁ nextEmpty nextMoved =>
      .moveWork₂Work₁ (tag nextEmpty) (fun symbol => tag (nextMoved symbol))
  | .copyInputWorks nextEmpty nextMoved =>
      .copyInputWorks (tag nextEmpty) (fun symbol => tag (nextMoved symbol))
  | .popInput nextEmpty nextMoved =>
      .popInput (tag nextEmpty) (fun symbol => tag (nextMoved symbol))
  | .popWork₁ nextEmpty nextMoved =>
      .popWork₁ (tag nextEmpty) (fun symbol => tag (nextMoved symbol))
  | .popWork₂ nextEmpty nextMoved =>
      .popWork₂ (tag nextEmpty) (fun symbol => tag (nextMoved symbol))
  | .inc₁ next => .inc₁ (tag next)
  | .inc₂ next => .inc₂ (tag next)
  | .inc₃ next => .inc₃ (tag next)
  | .dec₁ nextZero nextSucc => .dec₁ (tag nextZero) (tag nextSucc)
  | .dec₂ nextZero nextSucc => .dec₂ (tag nextZero) (tag nextSucc)
  | .dec₃ nextZero nextSucc => .dec₃ (tag nextZero) (tag nextSucc)
  | .jump next => .jump (tag next)
  | .halt => .halt

/-- One fixed controller iterating the complete structured-row source over an
arbitrary runtime seed stream. -/
abbrev affineExactlyOneStructuredRowFamilyRevProgram
    (labelWidth stateWidth : Nat) (cellCounts : List Nat) :
    Program UnaryFrameSym UnaryFrameSym :=
  let loader := unaryTripleLoaderProgramFor UnaryFrameSym
  let row := affineExactlyOneStructuredRowRevProgram
    labelWidth stateWidth cellCounts
  letI := loader.labelDecidableEq
  letI := loader.labelFintype
  letI := row.labelDecidableEq
  letI := row.labelFintype
  { Label := Sum loader.Label
      (Sum row.Label AffineExactlyOneStructuredRowFamilyClearLabel)
    main := .inl loader.main
    op := fun
      | .inl .ready =>
          .popWork₁ (.inr (.inl row.main))
            (fun _ => .inr (.inl row.main))
      | .inl label => structuredRowFamilyRelabelOp .inl (loader.op label)
      | .inr (.inl label) =>
          if label = affineExactlyOneStructuredRowFinishLabel
              labelWidth stateWidth cellCounts then
            .jump (.inr (.inr .height))
          else
            structuredRowFamilyRelabelOp (fun next => .inr (.inl next))
              (row.op label)
      | .inr (.inr .height) =>
          .dec₁ (.inr (.inr .start)) (.inr (.inr .height))
      | .inr (.inr .start) =>
          .dec₂ (.inr (.inr .rowBase)) (.inr (.inr .start))
      | .inr (.inr .rowBase) =>
          .dec₃ (.inl .load₁) (.inr (.inr .rowBase)) }

private def affineExactlyOneStructuredRowFamilyCfg
    {labelWidth stateWidth : Nat} {cellCounts : List Nat}
    (label : (affineExactlyOneStructuredRowFamilyRevProgram
      labelWidth stateWidth cellCounts).Label)
    (buffer₁ buffer₂ : Option UnaryFrameSym) (test : Bool)
    (input output work₁ work₂ : List UnaryFrameSym)
    (height start rowBase : List Unit) :
    BuilderCfg (affineExactlyOneStructuredRowFamilyRevProgram
      labelWidth stateWidth cellCounts) where
  label := some label
  buffer₁ := buffer₁
  buffer₂ := buffer₂
  test := test
  input := input
  output := output
  work₁ := work₁
  work₂ := work₂
  counter₁ := height
  counter₂ := start
  counter₃ := rowBase

/-- Clean loop entry before loading the next row seed. -/
def affineExactlyOneStructuredRowFamilyLoopCfg
    (labelWidth stateWidth : Nat) (cellCounts : List Nat)
    (input output : List UnaryFrameSym) :
    BuilderCfg (affineExactlyOneStructuredRowFamilyRevProgram
      labelWidth stateWidth cellCounts) :=
  affineExactlyOneStructuredRowFamilyCfg (.inl .load₁)
    none none false input output [] [] [] [] []

private def structuredRowFamilyRelabelCfg
    {Γ Δ : Type} {P Q : Program Γ Δ} (tag : P.Label → Q.Label)
    (c : BuilderCfg P) : BuilderCfg Q where
  label := c.label.map tag
  buffer₁ := c.buffer₁
  buffer₂ := c.buffer₂
  test := c.test
  input := c.input
  output := c.output
  work₁ := c.work₁
  work₂ := c.work₂
  counter₁ := c.counter₁
  counter₂ := c.counter₂
  counter₃ := c.counter₃

private def liftStructuredRowFamilyLoaderCfg
    {labelWidth stateWidth : Nat} {cellCounts : List Nat}
    (c : BuilderCfg (unaryTripleLoaderProgramFor UnaryFrameSym)) :
    BuilderCfg (affineExactlyOneStructuredRowFamilyRevProgram
      labelWidth stateWidth cellCounts) :=
  structuredRowFamilyRelabelCfg .inl c

private def liftStructuredRowFamilyRowCfg
    {labelWidth stateWidth : Nat} {cellCounts : List Nat}
    (c : BuilderCfg (affineExactlyOneStructuredRowRevProgram
      labelWidth stateWidth cellCounts)) :
    BuilderCfg (affineExactlyOneStructuredRowFamilyRevProgram
      labelWidth stateWidth cellCounts) :=
  structuredRowFamilyRelabelCfg (fun label => .inr (.inl label)) c

private theorem structuredRowFamilyRelabel_stepOp
    {Γ Δ : Type} {P Q : Program Γ Δ} (tag : P.Label → Q.Label)
    (op : Op Γ Δ P.Label) (c : BuilderCfg P) :
    stepOp (structuredRowFamilyRelabelOp tag op)
        (structuredRowFamilyRelabelCfg tag c) =
      structuredRowFamilyRelabelCfg tag (stepOp op c) := by
  rcases c with
    ⟨label, buffer₁, buffer₂, test, input, output, work₁, work₂,
      counter₁, counter₂, counter₃⟩
  cases op <;>
    simp only [structuredRowFamilyRelabelOp,
      structuredRowFamilyRelabelCfg, stepOp] <;>
    first
    | rfl
    | split <;> rfl

private theorem affineExactlyOneStructuredRow_finish_op
    (labelWidth stateWidth : Nat) (cellCounts : List Nat) :
    (affineExactlyOneStructuredRowRevProgram
      labelWidth stateWidth cellCounts).op
        (affineExactlyOneStructuredRowFinishLabel
          labelWidth stateWidth cellCounts) = Op.halt := by
  simpa [affineExactlyOneStructuredRowFinishLabel] using
    affineExactlyOneStructuredRow_op_finish
      labelWidth stateWidth cellCounts

private theorem affineExactlyOneStructuredRowFamily_op_loader
    {labelWidth stateWidth : Nat} {cellCounts : List Nat}
    (label : UnaryTripleLoaderLabel) (hexit : label ≠ .ready) :
    (affineExactlyOneStructuredRowFamilyRevProgram
      labelWidth stateWidth cellCounts).op (.inl label) =
      structuredRowFamilyRelabelOp .inl
        ((unaryTripleLoaderProgramFor UnaryFrameSym).op label) := by
  cases label <;>
    simp_all [affineExactlyOneStructuredRowFamilyRevProgram]

private theorem affineExactlyOneStructuredRowFamily_op_row
    {labelWidth stateWidth : Nat} {cellCounts : List Nat}
    (label : (affineExactlyOneStructuredRowRevProgram
      labelWidth stateWidth cellCounts).Label)
    (hexit : label ≠ affineExactlyOneStructuredRowFinishLabel
      labelWidth stateWidth cellCounts) :
    (affineExactlyOneStructuredRowFamilyRevProgram
      labelWidth stateWidth cellCounts).op (.inr (.inl label)) =
      structuredRowFamilyRelabelOp (fun next => .inr (.inl next))
        ((affineExactlyOneStructuredRowRevProgram
          labelWidth stateWidth cellCounts).op label) := by
  simp [affineExactlyOneStructuredRowFamilyRevProgram, hexit]

private theorem affineExactlyOneStructuredRowFamily_op_finish
    (labelWidth stateWidth : Nat) (cellCounts : List Nat) :
    (affineExactlyOneStructuredRowFamilyRevProgram
      labelWidth stateWidth cellCounts).op
        (.inr (.inl (affineExactlyOneStructuredRowFinishLabel
          labelWidth stateWidth cellCounts))) =
      Op.jump (.inr (.inr
        AffineExactlyOneStructuredRowFamilyClearLabel.height)) := by
  simp [affineExactlyOneStructuredRowFamilyRevProgram]

private theorem affineExactlyOneStructuredRowFamily_finish_step
    {labelWidth stateWidth : Nat} {cellCounts : List Nat}
    (c : BuilderCfg (affineExactlyOneStructuredRowRevProgram
      labelWidth stateWidth cellCounts))
    (hlabel : c.label = some (affineExactlyOneStructuredRowFinishLabel
      labelWidth stateWidth cellCounts)) :
    step (affineExactlyOneStructuredRowFamilyRevProgram
        labelWidth stateWidth cellCounts)
        (liftStructuredRowFamilyRowCfg c) =
      some { liftStructuredRowFamilyRowCfg c with
        label := some (.inr (.inr
          AffineExactlyOneStructuredRowFamilyClearLabel.height)) } := by
  unfold step
  rw [show (liftStructuredRowFamilyRowCfg c).label =
    c.label.map (fun label => .inr (.inl label)) by rfl]
  rw [hlabel]
  simp [stepOp]

private theorem liftStructuredRowFamilyLoader_step
    {labelWidth stateWidth : Nat} {cellCounts : List Nat}
    (c : BuilderCfg (unaryTripleLoaderProgramFor UnaryFrameSym))
    (hexit : c.label ≠ some .ready) :
    step (affineExactlyOneStructuredRowFamilyRevProgram
        labelWidth stateWidth cellCounts)
        (liftStructuredRowFamilyLoaderCfg c) =
      Option.map liftStructuredRowFamilyLoaderCfg
        (step (unaryTripleLoaderProgramFor UnaryFrameSym) c) := by
  unfold step
  rw [show (liftStructuredRowFamilyLoaderCfg c).label =
    c.label.map .inl by rfl]
  cases hlabel : c.label with
  | none => rfl
  | some label =>
      have hlabelExit : label ≠ .ready := by
        intro h
        apply hexit
        simpa [hlabel] using congrArg some h
      simp only [Option.map_some]
      exact congrArg some
        (structuredRowFamilyRelabel_stepOp
          (Q := affineExactlyOneStructuredRowFamilyRevProgram
            labelWidth stateWidth cellCounts)
          (fun label => Sum.inl label)
          ((unaryTripleLoaderProgramFor UnaryFrameSym).op label) c)

private theorem liftStructuredRowFamilyRow_step
    {labelWidth stateWidth : Nat} {cellCounts : List Nat}
    (c : BuilderCfg (affineExactlyOneStructuredRowRevProgram
      labelWidth stateWidth cellCounts))
    (hexit : c.label ≠ some (affineExactlyOneStructuredRowFinishLabel
      labelWidth stateWidth cellCounts)) :
    step (affineExactlyOneStructuredRowFamilyRevProgram
        labelWidth stateWidth cellCounts)
        (liftStructuredRowFamilyRowCfg c) =
      Option.map liftStructuredRowFamilyRowCfg
        (step (affineExactlyOneStructuredRowRevProgram
          labelWidth stateWidth cellCounts) c) := by
  unfold step
  rw [show (liftStructuredRowFamilyRowCfg c).label =
    c.label.map (fun label => .inr (.inl label)) by rfl]
  cases hlabel : c.label with
  | none => rfl
  | some label =>
      have hlabelExit : label ≠ affineExactlyOneStructuredRowFinishLabel
          labelWidth stateWidth cellCounts := by
        intro h
        apply hexit
        simpa [hlabel] using congrArg some h
      simp only [Option.map_some]
      simp only [if_neg hlabelExit]
      exact congrArg some
        (structuredRowFamilyRelabel_stepOp
          (Q := affineExactlyOneStructuredRowFamilyRevProgram
            labelWidth stateWidth cellCounts)
          (fun next => Sum.inr (Sum.inl next))
          ((affineExactlyOneStructuredRowRevProgram
            labelWidth stateWidth cellCounts).op label) c)

private theorem structuredRowFamily_iterate_bind_none {σ : Type}
    (f : σ → Option σ) : ∀ n : Nat,
    (flip Option.bind f)^[n] none = none := by
  intro n
  induction n with
  | zero => rfl
  | succ n ih =>
      rw [Function.iterate_succ_apply]
      change (flip Option.bind f)^[n] none = none
      exact ih

private theorem structuredRowFamily_haltExit_no_return
    {Γ Δ : Type} {P : Program Γ Δ} (exit : P.Label)
    (hop : P.op exit = Op.halt) (a b : BuilderCfg P)
    (ha : a.label = some exit) (hb : b.label = some exit) : ∀ n : Nat,
    (flip Option.bind (step P))^[n] (step P a) ≠ some b := by
  intro n
  let halted : BuilderCfg P :=
    { a with label := none, buffer₁ := none, buffer₂ := none, test := false }
  have hstep : step P a = some halted := by
    unfold step
    rw [ha]
    simp [hop, stepOp, halted]
  cases n with
  | zero =>
      rw [hstep]
      intro h
      have hlabel := congrArg (fun cfg => cfg.label) (Option.some.inj h)
      simp [halted, hb] at hlabel
  | succ n =>
      rw [hstep, Function.iterate_succ_apply]
      change (flip Option.bind (step P))^[n] (step P halted) ≠ some b
      have hnone : step P halted = none := rfl
      rw [hnone, structuredRowFamily_iterate_bind_none]
      simp

private theorem structuredRowFamily_lift_iterations_to_haltExit
    {Γ Δ : Type} {P Q : Program Γ Δ} (exit : P.Label)
    (hop : P.op exit = Op.halt) (tr : BuilderCfg P → BuilderCfg Q)
    (hstep : ∀ c, c.label ≠ some exit →
      step Q (tr c) = Option.map tr (step P c))
    {a b : BuilderCfg P} (hb : b.label = some exit) : ∀ n : Nat,
    (flip Option.bind (step P))^[n] (some a) = some b →
      (flip Option.bind (step Q))^[n] (some (tr a)) = some (tr b) := by
  intro n
  induction n generalizing a with
  | zero =>
      intro h
      injection h with hab
      simp [hab]
  | succ n ih =>
      intro h
      rw [Function.iterate_succ_apply] at h ⊢
      change (flip Option.bind (step P))^[n] (step P a) = some b at h
      change (flip Option.bind (step Q))^[n] (step Q (tr a)) = some (tr b)
      have haexit : a.label ≠ some exit := by
        intro ha
        exact structuredRowFamily_haltExit_no_return
          exit hop a b ha hb n h
      cases hsource : step P a with
      | none =>
          rw [hsource, structuredRowFamily_iterate_bind_none] at h
          contradiction
      | some c =>
          have hsim := hstep a haexit
          rw [hsource] at hsim
          simp only [Option.map_some] at hsim
          rw [hsim]
          rw [hsource] at h
          exact ih h

private def affineExactlyOneStructuredRowFamily_loader_run
    {labelWidth stateWidth : Nat} {cellCounts : List Nat}
    (height start rowBase : Nat) (tail output : List UnaryFrameSym) :
    EvalsToInTime
      (step (affineExactlyOneStructuredRowFamilyRevProgram
        labelWidth stateWidth cellCounts))
      (affineExactlyOneStructuredRowFamilyLoopCfg
        labelWidth stateWidth cellCounts
        (encodeUnaryFrame [height, start, rowBase] ++ tail) output)
      (some (liftStructuredRowFamilyLoaderCfg
        (unaryTripleLoaderReadyCfgFor height start rowBase tail output
          [] [])))
      (unaryTripleLoaderSteps height start rowBase) := by
  have sourceRun := unaryTripleLoader_runFor
    (Δ := UnaryFrameSym) height start rowBase tail output [] []
  have htarget :
      (unaryTripleLoaderReadyCfgFor height start rowBase tail output
        ([] : List UnaryFrameSym) []).label = some .ready := rfl
  refine ⟨⟨sourceRun.steps, ?_⟩, sourceRun.steps_le_m⟩
  have hstart :
      liftStructuredRowFamilyLoaderCfg
          (unaryTripleLoaderCfgFor .load₁ none
            (encodeUnaryFrame [height, start, rowBase] ++ tail)
            output [] [] [] [] []) =
        affineExactlyOneStructuredRowFamilyLoopCfg
          labelWidth stateWidth cellCounts
          (encodeUnaryFrame [height, start, rowBase] ++ tail) output := rfl
  rw [← hstart]
  exact structuredRowFamily_lift_iterations_to_haltExit
      UnaryTripleLoaderLabel.ready rfl
      liftStructuredRowFamilyLoaderCfg liftStructuredRowFamilyLoader_step
      htarget sourceRun.steps sourceRun.evals_in_steps

private def affineExactlyOneStructuredRowFamily_row_run
    {labelWidth stateWidth : Nat} {cellCounts : List Nat}
    (height start rowBase : Nat) (tail output : List UnaryFrameSym) :
    EvalsToInTime
      (step (affineExactlyOneStructuredRowFamilyRevProgram
        labelWidth stateWidth cellCounts))
      (liftStructuredRowFamilyRowCfg
        (affineExactlyOneStructuredRowLoadedCfg
          labelWidth stateWidth cellCounts height start rowBase tail output))
      (some (liftStructuredRowFamilyRowCfg
        (affineExactlyOneStructuredRowFinishCfg
          labelWidth stateWidth cellCounts height start rowBase tail
          ((encodeAffineExactlyOneCompactFamily
            (affineExactlyOneStructuredRowFrames labelWidth stateWidth
              cellCounts height start rowBase)).reverse ++ output))))
      (affineExactlyOneStructuredRowSteps
        labelWidth stateWidth cellCounts height start rowBase) := by
  have sourceRun := affineExactlyOneStructuredRow_runToFinish
    labelWidth stateWidth cellCounts height start rowBase tail output
  have htarget :
      (affineExactlyOneStructuredRowFinishCfg
        labelWidth stateWidth cellCounts height start rowBase tail
        ((encodeAffineExactlyOneCompactFamily
          (affineExactlyOneStructuredRowFrames labelWidth stateWidth
            cellCounts height start rowBase)).reverse ++ output)).label =
        some (affineExactlyOneStructuredRowFinishLabel
          labelWidth stateWidth cellCounts) := rfl
  refine ⟨⟨sourceRun.steps, ?_⟩, sourceRun.steps_le_m⟩
  exact structuredRowFamily_lift_iterations_to_haltExit
    (affineExactlyOneStructuredRowFinishLabel
      labelWidth stateWidth cellCounts)
    (affineExactlyOneStructuredRow_finish_op
      labelWidth stateWidth cellCounts)
    liftStructuredRowFamilyRowCfg liftStructuredRowFamilyRow_step
    htarget sourceRun.steps sourceRun.evals_in_steps

private theorem structuredRowFamily_clearHeight_eval
    {labelWidth stateWidth : Nat} {cellCounts : List Nat}
    (value : Nat) (buffer₁ buffer₂ : Option UnaryFrameSym) (test : Bool)
    (input output work₁ work₂ : List UnaryFrameSym)
    (start rowBase : List Unit) :
    (flip Option.bind
      (step (affineExactlyOneStructuredRowFamilyRevProgram
        labelWidth stateWidth cellCounts)))^[value + 1]
      (some (affineExactlyOneStructuredRowFamilyCfg
        (.inr (.inr .height)) buffer₁ buffer₂ test input output work₁ work₂
        (List.replicate value ()) start rowBase)) =
      some (affineExactlyOneStructuredRowFamilyCfg
        (.inr (.inr .start)) buffer₁ buffer₂ false input output work₁ work₂
        [] start rowBase) := by
  induction value generalizing test with
  | zero => rfl
  | succ value ih =>
      rw [show value + 1 + 1 = (value + 1) + 1 by omega,
        Function.iterate_succ_apply]
      change
        (flip Option.bind
          (step (affineExactlyOneStructuredRowFamilyRevProgram
            labelWidth stateWidth cellCounts)))^[value + 1]
          (some (affineExactlyOneStructuredRowFamilyCfg
            (.inr (.inr .height)) buffer₁ buffer₂ true input output
            work₁ work₂ (List.replicate value ()) start rowBase)) = _
      simpa using ih true

private theorem structuredRowFamily_clearStart_eval
    {labelWidth stateWidth : Nat} {cellCounts : List Nat}
    (value : Nat) (buffer₁ buffer₂ : Option UnaryFrameSym) (test : Bool)
    (input output work₁ work₂ : List UnaryFrameSym)
    (height rowBase : List Unit) :
    (flip Option.bind
      (step (affineExactlyOneStructuredRowFamilyRevProgram
        labelWidth stateWidth cellCounts)))^[value + 1]
      (some (affineExactlyOneStructuredRowFamilyCfg
        (.inr (.inr .start)) buffer₁ buffer₂ test input output work₁ work₂
        height (List.replicate value ()) rowBase)) =
      some (affineExactlyOneStructuredRowFamilyCfg
        (.inr (.inr .rowBase)) buffer₁ buffer₂ false input output work₁ work₂
        height [] rowBase) := by
  induction value generalizing test with
  | zero => rfl
  | succ value ih =>
      rw [show value + 1 + 1 = (value + 1) + 1 by omega,
        Function.iterate_succ_apply]
      change
        (flip Option.bind
          (step (affineExactlyOneStructuredRowFamilyRevProgram
            labelWidth stateWidth cellCounts)))^[value + 1]
          (some (affineExactlyOneStructuredRowFamilyCfg
            (.inr (.inr .start)) buffer₁ buffer₂ true input output
            work₁ work₂ height (List.replicate value ()) rowBase)) = _
      simpa using ih true

private theorem structuredRowFamily_clearRowBase_eval
    {labelWidth stateWidth : Nat} {cellCounts : List Nat}
    (value : Nat) (buffer₁ buffer₂ : Option UnaryFrameSym) (test : Bool)
    (input output work₁ work₂ : List UnaryFrameSym)
    (height start : List Unit) :
    (flip Option.bind
      (step (affineExactlyOneStructuredRowFamilyRevProgram
        labelWidth stateWidth cellCounts)))^[value + 1]
      (some (affineExactlyOneStructuredRowFamilyCfg
        (.inr (.inr .rowBase)) buffer₁ buffer₂ test input output work₁ work₂
        height start (List.replicate value ()))) =
      some (affineExactlyOneStructuredRowFamilyCfg
        (.inl .load₁) buffer₁ buffer₂ false input output work₁ work₂
        height start []) := by
  induction value generalizing test with
  | zero => rfl
  | succ value ih =>
      rw [show value + 1 + 1 = (value + 1) + 1 by omega,
        Function.iterate_succ_apply]
      change
        (flip Option.bind
          (step (affineExactlyOneStructuredRowFamilyRevProgram
            labelWidth stateWidth cellCounts)))^[value + 1]
          (some (affineExactlyOneStructuredRowFamilyCfg
            (.inr (.inr .rowBase)) buffer₁ buffer₂ true input output
            work₁ work₂ height start (List.replicate value ()))) = _
      simpa using ih true

private def affineExactlyOneStructuredRowFamily_clear_run
    {labelWidth stateWidth : Nat} {cellCounts : List Nat}
    (height start rowBase : Nat) (input output : List UnaryFrameSym) :
    EvalsToInTime
      (step (affineExactlyOneStructuredRowFamilyRevProgram
        labelWidth stateWidth cellCounts))
      (affineExactlyOneStructuredRowFamilyCfg (.inr (.inr .height))
        none none false input output [] []
        (List.replicate height ()) (List.replicate start ())
        (List.replicate rowBase ()))
      (some (affineExactlyOneStructuredRowFamilyLoopCfg
        labelWidth stateWidth cellCounts input output))
      ((height + 1) + (start + 1) + (rowBase + 1)) := by
  let afterHeight := affineExactlyOneStructuredRowFamilyCfg
    (labelWidth := labelWidth) (stateWidth := stateWidth)
    (cellCounts := cellCounts) (.inr (.inr .start)) none none false
    input output [] [] [] (List.replicate start ())
    (List.replicate rowBase ())
  let afterStart := affineExactlyOneStructuredRowFamilyCfg
    (labelWidth := labelWidth) (stateWidth := stateWidth)
    (cellCounts := cellCounts) (.inr (.inr .rowBase)) none none false
    input output [] [] [] [] (List.replicate rowBase ())
  have hheight : EvalsToInTime
      (step (affineExactlyOneStructuredRowFamilyRevProgram
        labelWidth stateWidth cellCounts))
      (affineExactlyOneStructuredRowFamilyCfg (.inr (.inr .height))
        none none false input output [] [] (List.replicate height ())
        (List.replicate start ()) (List.replicate rowBase ()))
      (some afterHeight) (height + 1) :=
    ⟨⟨height + 1, by
      simpa [afterHeight] using structuredRowFamily_clearHeight_eval
        (labelWidth := labelWidth) (stateWidth := stateWidth)
        (cellCounts := cellCounts) height none none false input output [] []
        (List.replicate start ()) (List.replicate rowBase ())⟩, le_rfl⟩
  have hstart : EvalsToInTime
      (step (affineExactlyOneStructuredRowFamilyRevProgram
        labelWidth stateWidth cellCounts)) afterHeight
      (some afterStart) (start + 1) :=
    ⟨⟨start + 1, by
      simpa [afterHeight, afterStart] using
        structuredRowFamily_clearStart_eval
          (labelWidth := labelWidth) (stateWidth := stateWidth)
          (cellCounts := cellCounts) start none none false input output [] []
          [] (List.replicate rowBase ())⟩, le_rfl⟩
  have hbase : EvalsToInTime
      (step (affineExactlyOneStructuredRowFamilyRevProgram
        labelWidth stateWidth cellCounts)) afterStart
      (some (affineExactlyOneStructuredRowFamilyLoopCfg
        labelWidth stateWidth cellCounts input output)) (rowBase + 1) :=
    ⟨⟨rowBase + 1, by
      simpa [afterStart, affineExactlyOneStructuredRowFamilyLoopCfg] using
        structuredRowFamily_clearRowBase_eval
          (labelWidth := labelWidth) (stateWidth := stateWidth)
          (cellCounts := cellCounts) rowBase none none false input output
          [] [] [] []⟩, le_rfl⟩
  let throughStart := EvalsToInTime.trans
    (step (affineExactlyOneStructuredRowFamilyRevProgram
      labelWidth stateWidth cellCounts))
    (height + 1) (start + 1) _ afterHeight _ hheight hstart
  let full := EvalsToInTime.trans
    (step (affineExactlyOneStructuredRowFamilyRevProgram
      labelWidth stateWidth cellCounts))
    ((start + 1) + (height + 1)) (rowBase + 1) _ afterStart _
    throughStart hbase
  convert full using 1 <;> omega

/-- Exact cost of one loaded-seed iteration, including restoration of the
clean loop invariant. -/
def affineExactlyOneStructuredRowFamilyOneSteps
    (labelWidth stateWidth : Nat) (cellCounts : List Nat)
    (seed : AffineExactlyOneStructuredRowSeed) : Nat :=
  unaryTripleLoaderSteps seed.height seed.start seed.rowBase + 1 +
    affineExactlyOneStructuredRowSteps labelWidth stateWidth cellCounts
      seed.height seed.start seed.rowBase + 1 +
    (seed.height + 1) +
    (affineExactlyOneStackFamilyEndStart cellCounts seed.height
      (affineExactlyOneStructuredRowStackStart
        labelWidth stateWidth seed.start) + 1) +
    (affineExactlyOneStackFamilyEndBase cellCounts seed.height
      (affineExactlyOneStructuredRowStackBase
        labelWidth stateWidth seed.rowBase) + 1)

private def affineExactlyOneStructuredRowFamily_one
    (labelWidth stateWidth : Nat) (cellCounts : List Nat)
    (seed : AffineExactlyOneStructuredRowSeed)
    (tail output : List UnaryFrameSym) :
    EvalsToInTime
      (step (affineExactlyOneStructuredRowFamilyRevProgram
        labelWidth stateWidth cellCounts))
      (affineExactlyOneStructuredRowFamilyLoopCfg
        labelWidth stateWidth cellCounts
        (encodeAffineExactlyOneStructuredRowSeed seed ++ tail) output)
      (some (affineExactlyOneStructuredRowFamilyLoopCfg
        labelWidth stateWidth cellCounts tail
        ((encodeAffineExactlyOneCompactFamily
          (affineExactlyOneStructuredRowFrames labelWidth stateWidth
            cellCounts seed.height seed.start seed.rowBase)).reverse ++
          output)))
      (affineExactlyOneStructuredRowFamilyOneSteps
        labelWidth stateWidth cellCounts seed) := by
  let rowOutput :=
    (encodeAffineExactlyOneCompactFamily
      (affineExactlyOneStructuredRowFrames labelWidth stateWidth cellCounts
        seed.height seed.start seed.rowBase)).reverse ++ output
  let loaderReady := liftStructuredRowFamilyLoaderCfg
    (labelWidth := labelWidth) (stateWidth := stateWidth)
    (cellCounts := cellCounts)
    (unaryTripleLoaderReadyCfgFor seed.height seed.start seed.rowBase
      tail output [] [])
  let rowStart := liftStructuredRowFamilyRowCfg
    (affineExactlyOneStructuredRowLoadedCfg
      labelWidth stateWidth cellCounts seed.height seed.start seed.rowBase
      tail output)
  let rowDone := liftStructuredRowFamilyRowCfg
    (affineExactlyOneStructuredRowFinishCfg
      labelWidth stateWidth cellCounts seed.height seed.start seed.rowBase
      tail rowOutput)
  let endStart := affineExactlyOneStackFamilyEndStart cellCounts seed.height
    (affineExactlyOneStructuredRowStackStart
      labelWidth stateWidth seed.start)
  let endBase := affineExactlyOneStackFamilyEndBase cellCounts seed.height
    (affineExactlyOneStructuredRowStackBase
      labelWidth stateWidth seed.rowBase)
  let clearStart := affineExactlyOneStructuredRowFamilyCfg
    (labelWidth := labelWidth) (stateWidth := stateWidth)
    (cellCounts := cellCounts) (.inr (.inr .height)) none none false
    tail rowOutput [] [] (List.replicate seed.height ())
    (List.replicate endStart ()) (List.replicate endBase ())
  have hloader : EvalsToInTime
      (step (affineExactlyOneStructuredRowFamilyRevProgram
        labelWidth stateWidth cellCounts))
      (affineExactlyOneStructuredRowFamilyLoopCfg
        labelWidth stateWidth cellCounts
        (encodeAffineExactlyOneStructuredRowSeed seed ++ tail) output)
      (some loaderReady)
      (unaryTripleLoaderSteps seed.height seed.start seed.rowBase) := by
    simpa [encodeAffineExactlyOneStructuredRowSeed, loaderReady] using
      affineExactlyOneStructuredRowFamily_loader_run
        (labelWidth := labelWidth) (stateWidth := stateWidth)
        (cellCounts := cellCounts) seed.height seed.start seed.rowBase
        tail output
  have hbridge : EvalsToInTime
      (step (affineExactlyOneStructuredRowFamilyRevProgram
        labelWidth stateWidth cellCounts)) loaderReady (some rowStart) 1 := by
    refine ⟨⟨1, ?_⟩, le_rfl⟩
    rfl
  have hrow : EvalsToInTime
      (step (affineExactlyOneStructuredRowFamilyRevProgram
        labelWidth stateWidth cellCounts)) rowStart (some rowDone)
      (affineExactlyOneStructuredRowSteps labelWidth stateWidth cellCounts
        seed.height seed.start seed.rowBase) := by
    simpa [rowStart, rowDone, rowOutput] using
      affineExactlyOneStructuredRowFamily_row_run
        (labelWidth := labelWidth) (stateWidth := stateWidth)
        (cellCounts := cellCounts) seed.height seed.start seed.rowBase
        tail output
  have hexit : EvalsToInTime
      (step (affineExactlyOneStructuredRowFamilyRevProgram
        labelWidth stateWidth cellCounts)) rowDone (some clearStart) 1 := by
    refine ⟨⟨1, ?_⟩, le_rfl⟩
    change step (affineExactlyOneStructuredRowFamilyRevProgram
      labelWidth stateWidth cellCounts) rowDone = some clearStart
    rw [show rowDone = liftStructuredRowFamilyRowCfg
      (affineExactlyOneStructuredRowFinishCfg
        labelWidth stateWidth cellCounts seed.height seed.start seed.rowBase
        tail rowOutput) by rfl]
    rw [affineExactlyOneStructuredRowFamily_finish_step _ rfl]
    congr 2
  have hclear : EvalsToInTime
      (step (affineExactlyOneStructuredRowFamilyRevProgram
        labelWidth stateWidth cellCounts)) clearStart
      (some (affineExactlyOneStructuredRowFamilyLoopCfg
        labelWidth stateWidth cellCounts tail rowOutput))
      ((seed.height + 1) + (endStart + 1) + (endBase + 1)) := by
    simpa [clearStart] using
      affineExactlyOneStructuredRowFamily_clear_run
        (labelWidth := labelWidth) (stateWidth := stateWidth)
        (cellCounts := cellCounts) seed.height endStart endBase tail rowOutput
  let h₁ := EvalsToInTime.trans
    (step (affineExactlyOneStructuredRowFamilyRevProgram
      labelWidth stateWidth cellCounts)) _ 1 _ loaderReady _ hloader hbridge
  let h₂ := EvalsToInTime.trans
    (step (affineExactlyOneStructuredRowFamilyRevProgram
      labelWidth stateWidth cellCounts)) _ _ _ rowStart _ h₁ hrow
  let h₃ := EvalsToInTime.trans
    (step (affineExactlyOneStructuredRowFamilyRevProgram
      labelWidth stateWidth cellCounts)) _ 1 _ rowDone _ h₂ hexit
  let full := EvalsToInTime.trans
    (step (affineExactlyOneStructuredRowFamilyRevProgram
      labelWidth stateWidth cellCounts)) _ _ _ clearStart _ h₃ hclear
  convert full using 1 <;>
    simp [affineExactlyOneStructuredRowFamilyOneSteps,
      endStart, endBase] <;> omega

/-- Exact runtime, including loader, row execution, counter clearing, and the
two final empty-input halt steps. -/
def affineExactlyOneStructuredRowFamilyRevSteps
    (labelWidth stateWidth : Nat) (cellCounts : List Nat) :
    List AffineExactlyOneStructuredRowSeed → Nat
  | [] => 2
  | seed :: rest =>
      affineExactlyOneStructuredRowFamilyOneSteps
          labelWidth stateWidth cellCounts seed +
        affineExactlyOneStructuredRowFamilyRevSteps
          labelWidth stateWidth cellCounts rest

private theorem structuredRowFamily_encode_append
    (left right : List AffineExactlyOneFrame) :
    encodeAffineExactlyOneCompactFamily (left ++ right) =
      encodeAffineExactlyOneCompactFamily left ++
        encodeAffineExactlyOneCompactFamily right := by
  induction left with
  | nil => rfl
  | cons frame rest ih =>
      simp [encodeAffineExactlyOneCompactFamily, ih, List.append_assoc]

private def affineExactlyOneStructuredRowFamily_runFrom
    (labelWidth stateWidth : Nat) (cellCounts : List Nat)
    (seeds : List AffineExactlyOneStructuredRowSeed)
    (output : List UnaryFrameSym) :
    EvalsToInTime
      (step (affineExactlyOneStructuredRowFamilyRevProgram
        labelWidth stateWidth cellCounts))
      (affineExactlyOneStructuredRowFamilyLoopCfg
        labelWidth stateWidth cellCounts
        (encodeAffineExactlyOneStructuredRowSeedFamily seeds) output)
      (some (haltCfg
        (affineExactlyOneStructuredRowFamilyRevProgram
          labelWidth stateWidth cellCounts)
        ((encodeAffineExactlyOneCompactFamily
          (affineExactlyOneStructuredRowFamilyFrames
            labelWidth stateWidth cellCounts seeds)).reverse ++ output)))
      (affineExactlyOneStructuredRowFamilyRevSteps
        labelWidth stateWidth cellCounts seeds) := by
  induction seeds generalizing output with
  | nil =>
      refine ⟨⟨2, ?_⟩, le_rfl⟩
      rfl
  | cons seed rest ih =>
      let rowFrames := affineExactlyOneStructuredRowFrames
        labelWidth stateWidth cellCounts
        seed.height seed.start seed.rowBase
      let rowOutput :=
        (encodeAffineExactlyOneCompactFamily rowFrames).reverse ++ output
      have hfirst := affineExactlyOneStructuredRowFamily_one
        labelWidth stateWidth cellCounts seed
        (encodeAffineExactlyOneStructuredRowSeedFamily rest) output
      have hrest := ih rowOutput
      let full := EvalsToInTime.trans
        (step (affineExactlyOneStructuredRowFamilyRevProgram
          labelWidth stateWidth cellCounts))
        (affineExactlyOneStructuredRowFamilyOneSteps
          labelWidth stateWidth cellCounts seed)
        (affineExactlyOneStructuredRowFamilyRevSteps
          labelWidth stateWidth cellCounts rest)
        _ (affineExactlyOneStructuredRowFamilyLoopCfg
          labelWidth stateWidth cellCounts
          (encodeAffineExactlyOneStructuredRowSeedFamily rest) rowOutput)
        _ hfirst hrest
      convert full using 1
      · simp [encodeAffineExactlyOneStructuredRowSeedFamily,
          encodeAffineExactlyOneStructuredRowSeed]
      · simp [affineExactlyOneStructuredRowFamilyFrames, rowFrames,
          rowOutput, structuredRowFamily_encode_append,
          List.reverse_append, List.append_assoc]
      · simp [affineExactlyOneStructuredRowFamilyRevSteps]
        omega

/-- One fixed controller consumes every runtime row seed, emits the reverse of
the complete canonical compact frame stream, and halts with all scratch state
cleared. -/
def affineExactlyOneStructuredRowFamilyRev_run
    (labelWidth stateWidth : Nat) (cellCounts : List Nat)
    (seeds : List AffineExactlyOneStructuredRowSeed) :
    EvalsToInTime
      (step (affineExactlyOneStructuredRowFamilyRevProgram
        labelWidth stateWidth cellCounts))
      (initialCfg
        (affineExactlyOneStructuredRowFamilyRevProgram
          labelWidth stateWidth cellCounts)
        (encodeAffineExactlyOneStructuredRowSeedFamily seeds))
      (some (haltCfg
        (affineExactlyOneStructuredRowFamilyRevProgram
          labelWidth stateWidth cellCounts)
        ((encodeAffineExactlyOneCompactFamily
          (affineExactlyOneStructuredRowFamilyFrames
            labelWidth stateWidth cellCounts seeds)).reverse)))
      (affineExactlyOneStructuredRowFamilyRevSteps
        labelWidth stateWidth cellCounts seeds) := by
  have hinit : affineExactlyOneStructuredRowFamilyLoopCfg
      labelWidth stateWidth cellCounts
      (encodeAffineExactlyOneStructuredRowSeedFamily seeds) [] =
        initialCfg
          (affineExactlyOneStructuredRowFamilyRevProgram
            labelWidth stateWidth cellCounts)
          (encodeAffineExactlyOneStructuredRowSeedFamily seeds) := rfl
  rw [← hinit]
  simpa only [List.append_nil] using
    affineExactlyOneStructuredRowFamily_runFrom
      labelWidth stateWidth cellCounts seeds []

end CLRS.Chapter34.Turing.PolyBuilder
