import CLRSLean.Chapter_34.Section_34_5_NP_Complete_Problems.HamiltonianCycle.ReductionMachine.Incidence.Scanner.FinalCleanup

/-!
# HAM-CYCLE incidence scanner: complete execution
-/

noncomputable section

open StateTransition

namespace CLRS.Chapter34.Turing.HamiltonianCycle.ReductionMachine.Incidence.Scanner

open PolyBuilder

/-- Row stream generated by an explicit list of vertex queries. -/
def queryRowsStream (I : VertexCoverInstance) (queries : List Nat) :
    List UnaryFrameSym :=
  queries.flatMap fun query => incidenceRow I query ++ [.frameEnd]

theorem queryRowsStream_append (I : VertexCoverInstance)
    (left right : List Nat) :
    queryRowsStream I (left ++ right) =
      queryRowsStream I left ++ queryRowsStream I right := by
  simp [queryRowsStream, List.flatMap_append]

/-- Exact accumulated cost after the query stream has been loaded. -/
def iterationsSteps : List Nat → VertexCoverInstance → Nat
  | [], I => (encodeVertexCoverInstance I).length + 8
  | query :: queries, I =>
      iterationSteps query I + iterationsSteps queries I

/-- Execute every reversed vertex record above the terminal certificate
marker. -/
def iterations_run (queries : List Nat) (I : VertexCoverInstance)
    (buffer₁ buffer₂ : Option (Option CliqueSym)) (test : Bool)
    (output : List UnaryFrameSym) :
    EvalsToInTime (step program)
      (cfg .nextQuery buffer₁ buffer₂ test
        ((encodeVertexCoverInstance I).map some) output
        (encodeVertexQueryWork queries ++ [some CliqueSym.certificateMark])
        [] [] [] [])
      (some (haltCfg program ((queryRowsStream I queries).reverse ++ output)))
      (iterationsSteps queries I) := by
  induction queries generalizing buffer₁ buffer₂ test output with
  | nil =>
      simpa [encodeVertexQueryWork, queryRowsStream, iterationsSteps] using
        terminal_run ((encodeVertexCoverInstance I).map some) output
          buffer₁ buffer₂ test
  | cons query queries ih =>
      have first := iteration_run query
        (encodeVertexQueryWork queries ++ [some CliqueSym.certificateMark])
        I output buffer₁ buffer₂ test
      have rest := ih
        (buffer₁ := some (some CliqueSym.vertexMark))
        (buffer₂ := none) (test := false)
        (output := (incidenceRow I query ++ [UnaryFrameSym.frameEnd]).reverse ++ output)
      let full := EvalsToInTime.trans (step program)
        (iterationSteps query I) (iterationsSteps queries I)
        _ _ _ first rest
      simpa [encodeVertexQueryWork, queryRowsStream, iterationsSteps,
        List.reverse_append, List.append_assoc, Nat.add_assoc,
        Nat.add_comm] using full

/-- Exact cost of the raw fixed incidence scan. -/
def scannerSteps (I : VertexCoverInstance) : Nat :=
  loadSteps I + iterationsSteps (List.range I.vertexCount).reverse I

private theorem loadedWork_eq (I : VertexCoverInstance) :
    ((Incidence.vertexQueryStream I).map some).reverse =
      encodeVertexQueryWork (List.range I.vertexCount).reverse ++
        [some CliqueSym.certificateMark] := by
  rw [encodeVertexQueryWork_reverse]
  simp [Incidence.vertexQueryStream, encodeCliqueCertificate,
    List.reverse_append]

private theorem queryRowsStream_range_reverse (I : VertexCoverInstance) :
    queryRowsStream I (List.range I.vertexCount).reverse =
      descendingStream I := by
  unfold queryRowsStream descendingStream
  simp only [encodeUnaryFrameMarkedRowOrderReverse, incidenceFamily]
  rw [← List.map_reverse]
  rw [List.flatMap_map]

/-- The fixed controller computes the raw reverse of the descending incidence
row stream from the shared query/graph input. -/
def scanner_run (I : VertexCoverInstance) :
    EvalsToInTime (step program)
      (initialCfg program (Incidence.inputStream I))
      (some (haltCfg program (rawOutput I)))
      (scannerSteps I) := by
  have loaded := load_run I
  rw [loadedWork_eq I] at loaded
  have repeated := iterations_run (List.range I.vertexCount).reverse I
    (some none) none false []
  rw [queryRowsStream_range_reverse I] at repeated
  let full := EvalsToInTime.trans (step program)
    (loadSteps I) (iterationsSteps (List.range I.vertexCount).reverse I)
    _ _ _ loaded repeated
  simpa [scannerSteps, rawOutput, Nat.add_comm] using full

end CLRS.Chapter34.Turing.HamiltonianCycle.ReductionMachine.Incidence.Scanner
