import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationLabelMajorDescriptorSource

open CLRS.Chapter34.Turing.CookLevin

#check transitionDispatchMuxInvocationLabelMajorDescriptorFormGroups
#check transitionDispatchMuxInvocationLabelMajorDescriptorForms
#check transitionDispatchMuxInvocationLabelMajorDescriptorFormGroups_nonempty
#check transitionDispatchMuxInvocationLabelMajorDescriptorValueGroups
#check transitionDispatchMuxInvocationLabelMajorDescriptorForms_value
#check transitionDispatchMuxInvocationLabelMajorDescriptorDelimiterTable
#check transitionDispatchMuxInvocationLabelMajorDescriptorDelimiterTable_nonempty
#check transitionDispatchMuxInvocationLabelMajorDescriptorDelimiterTable_length
#check verifierTransitionDispatchMuxInvocationLabelMajorDescriptorFrames
#check verifierTransitionDispatchMuxInvocationLabelMajorDescriptorFrames_eq
#check verifierTransitionDispatchMuxInvocationLabelMajorMarkedDescriptorFrames
#check verifierTransitionDispatchMuxInvocationLabelMajorMarkedDescriptorFrames_computableInPolyTime

#print axioms transitionDispatchMuxInvocationLabelMajorDescriptorForms_value
#print axioms transitionDispatchMuxInvocationLabelMajorDescriptorDelimiterTable_nonempty
#print axioms transitionDispatchMuxInvocationLabelMajorDescriptorDelimiterTable_length
#print axioms verifierTransitionDispatchMuxInvocationLabelMajorDescriptorFrames_eq
#print axioms verifierTransitionDispatchMuxInvocationLabelMajorMarkedDescriptorFrames_computableInPolyTime
