import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorValidity

open CLRS Chapter34
open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.CookLevin

#check verifierValidityGateStream
#check verifierValidityGateStream_eq
#check verifierRowWire_eq
#check verifierRowHaltedWire_eq
#check verifierRowLabelWire_eq
#check verifierRowStateWire_eq
#check verifierRowStackHeightWire_eq
#check verifierRowStackCellWire_eq
#check verifierPoolGateCount_eq
#check verifierValidityRowStart
#check verifierRowValidityGateStream
#check verifierValidityGateStream_rows_eq
#check validCfgGatePolynomial
#check validCfgGatePolynomial_eval
#check verifierValidityRowCostPolynomial
#check verifierValidityRowCostPolynomial_eval
#check verifierValidityRowCostClock
#check verifierValidityRowCostClock_length
#check verifierValidityRowCostClock_computableInPolyTime
#check verifierValidityGateCountPolynomial
#check verifierValidityGateCountPolynomial_eval
#check verifierValidityGateCountClock
#check verifierValidityGateCountClock_length
#check verifierValidityGateCountClock_computableInPolyTime
#check validityGateStreamAt
#check verifierValidityGateStreamByLength
#check verifierValidityGateStream_eq_byLength
#check verifierCircuitValidityPrefix
#check verifierCircuitValidityPrefix_eq
#check verifierCircuitValidityPrefix_isPrefix

#print axioms verifierValidityGateStream_eq
#print axioms verifierRowWire_eq
#print axioms verifierRowHaltedWire_eq
#print axioms verifierRowLabelWire_eq
#print axioms verifierRowStateWire_eq
#print axioms verifierRowStackHeightWire_eq
#print axioms verifierRowStackCellWire_eq
#print axioms verifierPoolGateCount_eq
#print axioms verifierValidityGateStream_rows_eq
#print axioms validCfgGatePolynomial_eval
#print axioms verifierValidityRowCostPolynomial_eval
#print axioms verifierValidityRowCostClock_computableInPolyTime
#print axioms verifierValidityGateCountPolynomial_eval
#print axioms verifierValidityGateCountClock_computableInPolyTime
#print axioms verifierValidityGateStream_eq_byLength
#print axioms verifierCircuitValidityPrefix_eq
#print axioms verifierCircuitValidityPrefix_isPrefix
