import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.PolyBuilder.AffineValidityTailPrefixedFamilySource

open CLRS.Chapter34.Turing.PolyBuilder

#check AffineValidityTailPrefixedSourceRow
#check AffineValidityTailPrefixedSourceFamily
#check encodeAffineValidityTailPrefixedSourceInput
#check encodeAffineValidityTailPrefixedSourceOutput
#check affineValidityTailPrefixedSourceHaltCfg
#check affineValidityTailPrefixedSource_runToFinish
#check affineValidityTailPrefixedSourceStepsToFinish_le
#check affineValidityTailPrefixedSource_computableInPolyTime

#print axioms affineValidityTailPrefixedSource_runToFinish
#print axioms affineValidityTailPrefixedSourceStepsToFinish_le
#print axioms affineValidityTailPrefixedSource_computableInPolyTime
