import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.PolyBuilder.AffineMuxInvocationProgressionControllerRun

open CLRS.Chapter34.Turing.PolyBuilder

#check affineMuxInvocationProgressionControllerRevProgram
#check affineMuxInvocationProgressionController_row_emit
#check affineMuxInvocationProgressionController_rows_emit
#check affineMuxInvocationProgressionController_clearSegment
#check affineMuxInvocationProgressionController_segment_emit
#check affineMuxInvocationProgressionControllerRev_run

#print axioms affineMuxInvocationProgressionController_row_emit
#print axioms affineMuxInvocationProgressionController_segment_emit
#print axioms affineMuxInvocationProgressionControllerRev_run
