import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationDescriptorCoordinateExecute

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.PolyBuilder
open CLRS.Chapter34.Turing.CookLevin

#check verifierTransitionDispatchMuxInvocationDescriptorCoordinateMarkedRows_eq
#check verifierTransitionDispatchMuxInvocationDescriptorCoordinateFrames_eq
#check verifierTransitionDispatchMuxInvocationDescriptorCoordinateProgressionFrames_eq
#check verifierTransitionDispatchMuxInvocationDescriptorCoordinateProgressionFrames_computableInPolyTime

#print axioms verifierTransitionDispatchMuxInvocationDescriptorCoordinateMarkedRows_eq
#print axioms verifierTransitionDispatchMuxInvocationDescriptorCoordinateFrames_eq
#print axioms verifierTransitionDispatchMuxInvocationDescriptorCoordinateProgressionFrames_eq
#print axioms verifierTransitionDispatchMuxInvocationDescriptorCoordinateProgressionFrames_computableInPolyTime
