import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionStatementRecursiveDescriptorSemantics

open CLRS.Chapter34 Turing
open CLRS.Chapter34.Turing CookLevin PolyBuilder

#check transitionStmtRecursiveHeadNumericDescriptorRow
#check transitionStmtRecursiveNumericDescriptorRow
#check verifierTransitionStmtRecursiveDescriptorSeedRowSource_row_eq
#check verifierTransitionStmtRecursiveDescriptorFamily_rows_eq_semantics

#print axioms verifierTransitionStmtRecursiveDescriptorSeedRowSource_row_eq
#print axioms verifierTransitionStmtRecursiveDescriptorFamily_rows_eq_semantics
