import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionStatementStackRoutePopSlices

open CLRS.Chapter34.Turing.CookLevin

#check transitionStackRoutePopHeightSliceFrames_eq
#check transitionStackRoutePopCellSliceFrames_eq
#check transitionStackRoutePopHeightSliceFrames_computableInPolyTime_of_source
#check transitionStackRoutePopCellSliceFrames_computableInPolyTime_of_source

#print axioms transitionStackRoutePopHeightSliceFrames_eq
#print axioms transitionStackRoutePopCellSliceFrames_eq
#print axioms transitionStackRoutePopHeightSliceFrames_computableInPolyTime_of_source
#print axioms transitionStackRoutePopCellSliceFrames_computableInPolyTime_of_source
