import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationLabelSourceRows

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.PolyBuilder
open CLRS.Chapter34.Turing.CookLevin

#check affineMuxInvocationEmptySegment_sourceFrames
#check affineMuxInvocationSingletonSegment_sourceFrames
#check TransitionDispatchMuxInvocationView.sourceFrames_eq_rows
#check verifierTransitionDispatchMuxDescriptorInvocationSourceFrames_eq_labelRows

#print axioms affineMuxInvocationEmptySegment_sourceFrames
#print axioms affineMuxInvocationSingletonSegment_sourceFrames
#print axioms TransitionDispatchMuxInvocationView.sourceFrames_eq_rows
#print axioms verifierTransitionDispatchMuxDescriptorInvocationSourceFrames_eq_labelRows
