import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationDescriptorPacketNormalize

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.PolyBuilder
open CLRS.Chapter34.Turing.CookLevin

#check restoreUnaryFrameFixedWidthPacketSeparators_encode
#check restoreUnaryFrameFixedWidthPacketSeparators_computableInPolyTime
#check verifierTransitionDispatchMuxInvocationDescriptorStandardDuplicatedPacketFrames_eq
#check verifierTransitionDispatchMuxInvocationDescriptorStandardDuplicatedPacketFrames_computableInPolyTime

#print axioms restoreUnaryFrameFixedWidthPacketSeparators_encode
#print axioms verifierTransitionDispatchMuxInvocationDescriptorStandardDuplicatedPacketFrames_eq
#print axioms verifierTransitionDispatchMuxInvocationDescriptorStandardDuplicatedPacketFrames_computableInPolyTime
