import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.PolyBuilder.AffineExactlyOneLeadingFixedCompactProjection

open CLRS.Chapter34.Turing.PolyBuilder

#check affineExactlyOneLeadingFixedCompactProjectionRev_run
#check affineExactlyOneLeadingFixedCompactProjectionSteps_le
#check affineExactlyOneLeadingFixedCompactProjection_computableInPolyTime

#print axioms affineExactlyOneLeadingFixedCompactProjectionRev_run
#print axioms affineExactlyOneLeadingFixedCompactProjectionSteps_le
#print axioms affineExactlyOneLeadingFixedCompactProjection_computableInPolyTime
