import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionStatementAffineContextLinearResultAffineSpan

open CLRS.Chapter34
open CLRS.Chapter34.Turing.CookLevin

#check TransitionStmtLinearResult.completeAffineSpanSegments
#check TransitionStmtLinearResult.completeAffineSpanDropAmounts
#check TransitionStmtLinearResult.completeAffineSpanSegments_values
#check verifierTransitionLinearResultAffineSpanFrames
#check verifierTransitionLinearResultAffineSpanFrames_computableInPolyTime
#check TransitionStmtLinearResult.verifierLinearResultAffineSpanFrames_eq
#print axioms TransitionStmtLinearResult.verifierLinearResultAffineSpanFrames_eq
