import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationDescriptorSource

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.PolyBuilder
open CLRS.Chapter34.Turing.CookLevin

#check transitionDispatchTrueArmSpanDescriptorBlock_value
#check TransitionDispatchTrueArmNormalizedLayout.affineSpanDescriptorForms_value
#check transitionDispatchTrueArmSpanDescriptorForms_value
#check transitionDispatchMuxInvocationDescriptorForms_value
#check verifierTransitionDispatchMuxInvocationDescriptorFrames_eq
#check verifierTransitionDispatchMuxInvocationDescriptorFrames_computableInPolyTime

#print axioms transitionDispatchMuxInvocationDescriptorForms_value
#print axioms verifierTransitionDispatchMuxInvocationDescriptorFrames_eq
#print axioms verifierTransitionDispatchMuxInvocationDescriptorFrames_computableInPolyTime
