import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransition

open CLRS.Chapter34
open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.CookLevin

#check arithmeticRowsAt
#check arithmeticPoolAt
#check arithmeticValidityAt
#check arithmeticTransitionsAt
#check transitionGateListAt
#check transitionGateStreamAt
#check arithmeticValidity_append_transitionGateStream
#check transitionGateListAt_length
#check verifierTransitionGateStreamByLength
#check verifierTransitionGateStream
#check verifierTransitionGateStream_eq_byLength
#check verifierValidity_append_transitionGateStream
#check verifierCircuitTransitionPrefix
#check verifierCircuitTransitionPrefix_eq

#print axioms arithmeticValidity_append_transitionGateStream
#print axioms transitionGateListAt_length
#print axioms verifierValidity_append_transitionGateStream
#print axioms verifierCircuitTransitionPrefix_eq
