import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationLabelPacketAssemblerRuntime

namespace CLRS.Chapter34.Turing.CookLevin

#check AlignedTransitionDispatchMuxInvocationViewFamily
#check AlignedTransitionDispatchMuxInvocationViewFamily.preparedFrames
#check AlignedTransitionDispatchMuxInvocationViewFamily.segments
#check transitionDispatchMuxInvocationLabelPacketAssemblerAligned_rev_computableInPolyTime
#check transitionDispatchMuxInvocationLabelPacketAssemblerAligned_computableInPolyTime
#check transitionDispatchMuxInvocationFrames_fromAlignedViews_computableInPolyTime

#print axioms transitionDispatchMuxInvocationLabelPacketAssemblerAligned_rev_computableInPolyTime
#print axioms transitionDispatchMuxInvocationFrames_fromAlignedViews_computableInPolyTime

end CLRS.Chapter34.Turing.CookLevin
