import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationDescriptorFalseLabelFrames

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.PolyBuilder
open CLRS.Chapter34.Turing.CookLevin

#check transitionDispatchFalseArmLabelBoundarySelection_length
#check transitionDispatchFalseArmLabelBoundarySelection_nonempty
#check verifierTransitionDispatchMuxInvocationDescriptorFalseRawMarkedFrames_eq
#check verifierTransitionDispatchMuxInvocationDescriptorFalseLabelFrames_eq
#check verifierTransitionDispatchMuxInvocationDescriptorFalseLabelFrames_computableInPolyTime

#print axioms transitionDispatchFalseArmLabelBoundarySelection_length
#print axioms verifierTransitionDispatchMuxInvocationDescriptorFalseRawMarkedFrames_eq
#print axioms verifierTransitionDispatchMuxInvocationDescriptorFalseLabelFrames_eq
#print axioms verifierTransitionDispatchMuxInvocationDescriptorFalseLabelFrames_computableInPolyTime
