import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationLabelMajorDescriptorSemantics

open CLRS.Chapter34.Turing.CookLevin

#check transitionDispatchMuxInvocationLabelMajorCanonicalDescriptorValueGroups
#check transitionDispatchMuxInvocationLabelMajorDescriptorValueGroups_eq_canonical
#check verifierTransitionDispatchMuxInvocationLabelMajorDescriptorFrames_eq_canonical

#print axioms transitionDispatchMuxInvocationLabelMajorDescriptorValueGroups_eq_canonical
#print axioms verifierTransitionDispatchMuxInvocationLabelMajorDescriptorFrames_eq_canonical
