import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionLabelRecursiveDescriptorSource

open CLRS.Chapter34 Turing
open CLRS.Chapter34.Turing CookLevin PolyBuilder

#check verifierTransitionLabelRecursiveDescriptorSeedRowSource
#check verifierTransitionLabelRecursiveDescriptorFamily
#check verifierTransitionLabelRecursiveDescriptorFamily_rows
#check verifierTransitionLabelRecursiveDescriptorFamily_computableInPolyTime

#print axioms verifierTransitionLabelRecursiveDescriptorFamily_rows
#print axioms verifierTransitionLabelRecursiveDescriptorFamily_computableInPolyTime
