import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionStatementAffineContextBranchRoute

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.CookLevin

#check transitionStmtBranchRouteValues
#check transitionStmtBranchRouteValues_length
#check transitionStmtBranchRouteValues_eq_output

#print axioms transitionStmtBranchRouteValues_eq_output
