import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationLabelPacketAssemblerCore

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.CookLevin

#check transitionDispatchMuxInvocationLabelPacketAssemblerRevProgram
#check transitionDispatchMuxInvocationLabelPacketAssemblerLoopCfg
#check transitionDispatchMuxInvocationLabelPacketAssemblerLoadedCfg
#check transitionDispatchMuxInvocationLabelPacketAssemblerLoadSteps
#check transitionDispatchMuxInvocationLabelPacketAssembler_load

#print axioms transitionDispatchMuxInvocationLabelPacketAssembler_load
