import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxTrueArmAffineSpanFrames

open CLRS.Chapter34.Turing.CookLevin

#check verifierTransitionDispatchTrueArmAffineSpanFrames_computableInPolyTime
#check transitionDispatchTrueArmAffineSpanValues
#check verifierTransitionDispatchTrueArmAffineSpanFrames_eq
#check verifierTransitionDispatchTrueArmAffineSpanFrames_eq_semantic

#print axioms verifierTransitionDispatchTrueArmAffineSpanFrames_eq_semantic
