import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionStatementStackRoutePushTrimFrames

open CLRS.Chapter34.Turing.CookLevin

#check transitionStackRoutePushTrimFrames_eq_descriptorTails
#check verifierTransitionStackRoutePushTrimFrames_eq
#check verifierTransitionStackRoutePushTrimFrames_computableInPolyTime

#print axioms transitionStackRoutePushTrimFrames_eq_descriptorTails
#print axioms verifierTransitionStackRoutePushTrimFrames_computableInPolyTime
