import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionStatementAffineContextRecursiveBranchDescriptorSource

open CLRS.Chapter34
open CLRS.Chapter34.Turing.CookLevin

#check TransitionDispatchMuxInvocationView.numericDescriptorRow
#check verifierTransitionRecursiveBranchDescriptorFamily
#check verifierTransitionRecursiveBranchDescriptorFamily_rows
#check verifierTransitionRecursiveBranchDescriptorFamily_computableInPolyTime
#print axioms verifierTransitionRecursiveBranchDescriptorFamily_computableInPolyTime
