import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionStatementStackRouteAffineSpanBounds

open CLRS.Chapter34.Turing.CookLevin

#check transitionStmtSelectedStackAffineActionSpans_sourceDrop_le
#check transitionStmtSelectedStackAffineActionSpans_sourceRdrop_le
#check TransitionStmtTerminalRowLayout.stackAffineSpanRoute_sourceDrop_le
#check TransitionStmtTerminalRowLayout.stackAffineSpanRoute_sourceRdrop_le

#print axioms TransitionStmtTerminalRowLayout.stackAffineSpanRoute_sourceRdrop_le
