import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationLabelMajorLabelPacketCompiler

open CLRS.Chapter34.Turing
open CookLevin PolyBuilder

#check verifierTransitionDispatchMuxInvocationLabelMajorPacketFamily
#check verifierTransitionDispatchMuxInvocationLabelMajorPacketFamily_encoding_eq
#check verifierTransitionDispatchMuxInvocationLabelMajorPacketFamily_computableInPolyTime
#check verifierTransitionDispatchMuxInvocationFrames_labelMajor_computableInPolyTime

#print axioms verifierTransitionDispatchMuxInvocationFrames_labelMajor_computableInPolyTime
