import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionStatementStackRouteDescriptorExecution

open CLRS.Chapter34.Turing.PolyBuilder
open CLRS.Chapter34.Turing.CookLevin

#check verifierTransitionStackRouteHeightDescriptorFrames_eq
#check verifierTransitionStackRouteCellDescriptorFrames_eq
#check verifierTransitionStackRouteHeightDescriptorFrames_computableInPolyTime
#check verifierTransitionStackRouteCellDescriptorFrames_computableInPolyTime
#check verifierTransitionStackRouteHeightProgressionFrameStream_computableInPolyTime
#check verifierTransitionStackRouteCellProgressionFrameStream_computableInPolyTime

#print axioms verifierTransitionStackRouteHeightDescriptorFrames_eq
#print axioms verifierTransitionStackRouteCellDescriptorFrames_eq
#print axioms verifierTransitionStackRouteHeightProgressionFrameStream_computableInPolyTime
#print axioms verifierTransitionStackRouteCellProgressionFrameStream_computableInPolyTime
