import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionAffineStmtScriptTotal

namespace CLRS.Chapter34.Turing.CookLevin

#check verifierTransitionAffineStmtScript_eq_target
#check verifierTransitionAffineStmtScriptTarget_computableInPolyTime

end CLRS.Chapter34.Turing.CookLevin
