import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionStatementAffineContextRecursiveBranchCoordinateSource

open CLRS.Chapter34
open CLRS.Chapter34.Turing.CookLevin

#check transitionStmtRecursiveBranchCoordinateProgression
#check transitionStmtRecursiveBranchCoordinateProgression_rows
#check transitionStmtRecursiveBranchCoordinateDescriptorForms
#check verifierTransitionRecursiveBranchCoordinateFamily
#check verifierTransitionRecursiveBranchCoordinateFamily_encoding_eq
#check verifierTransitionRecursiveBranchCoordinateFamily_computableInPolyTime
#print axioms verifierTransitionRecursiveBranchCoordinateFamily_computableInPolyTime
