import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationDescriptorTrueProgressionFrames

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.PolyBuilder
open CLRS.Chapter34.Turing.CookLevin

#check transitionDispatchTrueArmSpanDescriptorBlocks_flatten
#check transitionDispatchTrueArmSpanDescriptorBlocks_drop
#check verifierTransitionDispatchMuxInvocationDescriptorTruePacketFrames_eq
#check verifierTransitionDispatchMuxInvocationDescriptorTrueDroppedPacketFrames_eq
#check verifierTransitionDispatchMuxInvocationDescriptorTrueProgressionFrames_eq
#check verifierTransitionDispatchMuxInvocationDescriptorTrueProgressionFrames_computableInPolyTime

#print axioms transitionDispatchTrueArmSpanDescriptorBlocks_flatten
#print axioms transitionDispatchTrueArmSpanDescriptorBlocks_drop
#print axioms verifierTransitionDispatchMuxInvocationDescriptorTruePacketFrames_eq
#print axioms verifierTransitionDispatchMuxInvocationDescriptorTrueDroppedPacketFrames_eq
#print axioms verifierTransitionDispatchMuxInvocationDescriptorTrueProgressionFrames_eq
#print axioms verifierTransitionDispatchMuxInvocationDescriptorTrueProgressionFrames_computableInPolyTime
