import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionStatementDescriptorSeedSources

open CLRS.Chapter34 Turing
open CLRS.Chapter34.Turing CookLevin PolyBuilder

#check verifierTransitionAffineFormSeedRowSource
#check verifierTransitionRecursiveBranchSeedRowSource

#print axioms verifierTransitionAffineFormSeedRowSource
#print axioms verifierTransitionRecursiveBranchSeedRowSource
