import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationSegments

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.PolyBuilder
open CLRS.Chapter34.Turing.CookLevin

#check affineMuxInvocationSingletonSegments_frames
#check affineMuxFinCanonicalFrames_falseArm
#check transitionDispatchArtifactsFromSeed_muxInvocationSegments_frames
#check transitionDispatchMuxInvocationSegmentsFromSeed_frames
#check verifierTransitionDispatchMuxInvocationSegments_frames
#check verifierTransitionDispatchMuxInvocationFrames_fromSource_computableInPolyTime

#print axioms verifierTransitionDispatchMuxInvocationSegments_frames
#print axioms verifierTransitionDispatchMuxInvocationFrames_fromSource_computableInPolyTime
