import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.PolyBuilder.UnaryFrameLeadingSegmentFixedPrefixSplice

open CLRS.Chapter34.Turing.PolyBuilder

#check UnaryFrameLeadingSegmentFixedPrefixRow
#check UnaryFrameLeadingSegmentFixedPrefixFamily
#check encodeUnaryFrameLeadingSegmentFixedPrefixInput
#check encodeUnaryFrameLeadingSegmentFixedPrefixOutput
#check rewriteUnaryFrameLeadingSegmentFixedPrefix_family
#check unaryFrameLeadingSegmentFixedPrefixRevProgram
#check unaryFrameLeadingSegmentFixedPrefixRev_run
#check unaryFrameLeadingSegmentFixedPrefixSteps_le
#check unaryFrameLeadingSegmentFixedPrefixRev_computableInPolyTime
#check unaryFrameLeadingSegmentFixedPrefix_computableInPolyTime

#print axioms rewriteUnaryFrameLeadingSegmentFixedPrefix_family
#print axioms unaryFrameLeadingSegmentFixedPrefixRev_run
#print axioms unaryFrameLeadingSegmentFixedPrefixSteps_le
#print axioms unaryFrameLeadingSegmentFixedPrefixRev_computableInPolyTime
#print axioms unaryFrameLeadingSegmentFixedPrefix_computableInPolyTime
