import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionStatementAffineContextRecursiveBranchRoutePairSource

open CLRS.Chapter34
open CLRS.Chapter34.Turing.CookLevin

#check verifierTransitionStmtOutputRouteFamily_rows_length
#check verifierTransitionRecursiveBranchRoutePairFamily
#check verifierTransitionRecursiveBranchRoutePairFamily_rows
#check verifierTransitionRecursiveBranchRoutePairFamily_computableInPolyTime
#print axioms verifierTransitionRecursiveBranchRoutePairFamily_computableInPolyTime
