import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionAffineDelimitedMap

open CLRS.Chapter34
open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.CookLevin

#check transitionAffineDelimitedMapRow
#check verifierTransitionAffineDelimitedMapFrames_eq_rows
#check verifierTransitionAffineDelimitedMapFrames_computableInPolyTime

#print axioms verifierTransitionAffineDelimitedMapFrames_computableInPolyTime
