import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionStatementStackRouteCountSemantics

open CLRS.Chapter34.Turing.CookLevin

#check transitionStackRouteSubtractCount_rows
#print axioms transitionStackRouteSubtractCount_rows
