import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxOutput

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.CookLevin
open CLRS.Chapter34.Turing.PolyBuilder

#check transitionDispatchSelectorForms_value
#check transitionDispatchMuxRuntime_layout_eq
#check transitionDispatchMuxRuntimes_layouts_eq
#check arithmeticWidening_dispatchArtifact_muxRuntimeLayouts_eq
#check transitionDispatchMuxDescriptorBlock_value
#check transitionDispatchMuxDescriptorForms_value
#check encode_transitionDispatchMuxDescriptorForms
#check transitionDispatchMuxAffineProgressions_eq_runtimes
#check verifierTransitionDispatchMuxDescriptorFrames_eq
#check verifierTransitionDispatchMuxDescriptorFrames_computableInPolyTime
#check verifierTransitionDispatchSelectorFrames_eq
#check verifierTransitionDispatchSelectorFrames_computableInPolyTime
#check transitionDispatchMuxProgressionFrameStream_eq_coordinateSeeds
#check transitionDispatchMuxCoordinateRows_eq_layouts
#check transitionDispatchMuxCoordinateSeeds_eq_layout
#check verifierTransitionDispatchMuxCoordinateFrameStream_eq
#check verifierTransitionDispatchMuxCoordinateFrameStream_eq_layouts
#check verifierTransitionDispatchMuxCoordinateFrameStream_computableInPolyTime
#check transitionDispatchMuxOutputValues_eq_layout
#check TransitionDispatchLabelArtifact.muxOutputValues_eq_layout
#check arithmeticWidening_dispatchArtifact_muxOutputValues_eq
#check verifierTransitionDispatchMuxOutputValueFrames_eq_layouts
#check verifierTransitionDispatchMuxOutputValueFrames_computableInPolyTime

#print axioms transitionDispatchSelectorForms_value
#print axioms transitionDispatchMuxRuntimes_layouts_eq
#print axioms arithmeticWidening_dispatchArtifact_muxRuntimeLayouts_eq
#print axioms transitionDispatchMuxDescriptorForms_value
#print axioms transitionDispatchMuxAffineProgressions_eq_runtimes
#print axioms verifierTransitionDispatchMuxDescriptorFrames_eq
#print axioms verifierTransitionDispatchMuxDescriptorFrames_computableInPolyTime
#print axioms verifierTransitionDispatchSelectorFrames_eq
#print axioms verifierTransitionDispatchSelectorFrames_computableInPolyTime
#print axioms transitionDispatchMuxCoordinateSeeds_eq_layout
#print axioms verifierTransitionDispatchMuxCoordinateFrameStream_eq_layouts
#print axioms verifierTransitionDispatchMuxCoordinateFrameStream_computableInPolyTime
#print axioms transitionDispatchMuxOutputValues_eq_layout
#print axioms arithmeticWidening_dispatchArtifact_muxOutputValues_eq
#print axioms verifierTransitionDispatchMuxOutputValueFrames_eq_layouts
#print axioms verifierTransitionDispatchMuxOutputValueFrames_computableInPolyTime
