import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxTrueArmBranchAffine

open CLRS.Chapter34.Turing.CookLevin

#check transitionDispatchBranchOutputProgressions
#check transitionDispatchBranchOutputDescriptorForms_value
#check transitionDispatchBranchOutputProgressions_values

#print axioms transitionDispatchBranchOutputProgressions_values
