import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionStatementHead

open CLRS.Chapter34.Turing.CookLevin

#check arithmeticPeekCfgWires
#check transitionStmtHeadPhase
#check compileStmtScript_head?_eq_transitionStmtHeadPhase
#check transitionDispatchStatementHeads
#check compileDispatchLabelsListArtifacts_statementHeads_eq
#check transitionDispatchStatementHeadsFromSeed
#check arithmeticWidening_dispatchArtifact_statementHeads_eq_seed
#check TransitionStmtPhaseKind
#check transitionStmtPhaseKind
#check transitionStmtPhaseKinds
#check compileStmtScript_phaseKinds_eq
#check transitionDispatchPhaseKindsForLabels
#check transitionDispatchPhaseKinds
#check compileDispatchLabelsListScript_phaseKinds_eq
#check compileDispatchScript_phaseKinds_eq
#check transitionScriptDispatchPhaseKinds
#check compileTransitionScript_dispatchPhaseKinds_eq
#check compileTransitionFamilyScripts_dispatchPhaseKinds_eq_ofFn
#check compileTransitionFamilyScriptsAt_dispatchPhaseKinds_eq_ofFn

#print axioms compileStmtScript_head?_eq_transitionStmtHeadPhase
#print axioms compileDispatchLabelsListArtifacts_statementHeads_eq
#print axioms arithmeticWidening_dispatchArtifact_statementHeads_eq_seed
#print axioms compileStmtScript_phaseKinds_eq
#print axioms compileDispatchLabelsListScript_phaseKinds_eq
#print axioms compileDispatchScript_phaseKinds_eq
#print axioms compileTransitionScript_dispatchPhaseKinds_eq
#print axioms compileTransitionFamilyScripts_dispatchPhaseKinds_eq_ofFn
#print axioms compileTransitionFamilyScriptsAt_dispatchPhaseKinds_eq_ofFn
