import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionStatementTerminalStackActionBounds

open CLRS.Chapter34.Turing.CookLevin

#check transitionStmtTerminalStackActions_pushCount_eq_stmtMaxPushes
#check transitionStmtStackActionsFor_pushCount_eq
#check TransitionStmtTerminalRowLayout.selectedPushCount_le_maxPushesPerStep
#check TransitionStmtTerminalRowLayout.selectedPushCount_le_workHeight

#print axioms transitionStmtTerminalStackActions_pushCount_eq_stmtMaxPushes
#print axioms TransitionStmtTerminalRowLayout.selectedPushCount_le_workHeight
