import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionStatementAffineContextRecursiveBranchPacketSource

open CLRS.Chapter34
open CLRS.Chapter34.Turing.CookLevin

#check verifierTransitionRecursiveBranchViews
#check verifierTransitionRecursiveBranchPacketFamily
#check verifierTransitionRecursiveBranchPacketFamily_rows
#check verifierTransitionRecursiveBranchPacketFamily_encoding_eq
#check verifierTransitionRecursiveBranchPacketFamily_computableInPolyTime
#print axioms verifierTransitionRecursiveBranchPacketFamily_computableInPolyTime
