import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationLabelPacketAssemblerCoordinate

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.CookLevin

#check transitionDispatchMuxInvocationLabelPacketAssemblerCoordinateStartCfg
#check transitionDispatchMuxInvocationLabelPacketAssemblerCoordinateFinishCfg
#check transitionDispatchMuxInvocationLabelPacketAssemblerCoordinateSteps
#check transitionDispatchMuxInvocationLabelPacketAssembler_coordinate

#print axioms transitionDispatchMuxInvocationLabelPacketAssembler_coordinate
