import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationDescriptorCoordinateLabelFrames

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.PolyBuilder
open CLRS.Chapter34.Turing.CookLevin

#check affineUnaryTripleProgressionFixedGroupZeroFrameStream_eq
#check verifierTransitionDispatchMuxInvocationDescriptorCoordinateLabelFrames_eq
#check verifierTransitionDispatchMuxInvocationDescriptorCoordinateLabelFrames_eq_layouts
#check verifierTransitionDispatchMuxInvocationDescriptorCoordinateLabelFrames_computableInPolyTime

#print axioms affineUnaryTripleProgressionFixedGroupZeroFrameStream_eq
#print axioms verifierTransitionDispatchMuxInvocationDescriptorCoordinateLabelFrames_eq
#print axioms verifierTransitionDispatchMuxInvocationDescriptorCoordinateLabelFrames_eq_layouts
#print axioms verifierTransitionDispatchMuxInvocationDescriptorCoordinateLabelFrames_computableInPolyTime
