import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationLabelMajorCoordinateLabelFrames

open CLRS.Chapter34.Turing.CookLevin

#check transitionDispatchMuxInvocationLabelMajorDescriptorPackets_coordinateProgressions
#check verifierTransitionDispatchMuxInvocationLabelMajorCoordinateProgressions_eq
#check verifierTransitionDispatchMuxInvocationLabelMajorCoordinateLabelFrames_eq_existing
#check verifierTransitionDispatchMuxInvocationLabelMajorCoordinateLabelFrames_computableInPolyTime

#print axioms transitionDispatchMuxInvocationLabelMajorDescriptorPackets_coordinateProgressions
#print axioms verifierTransitionDispatchMuxInvocationLabelMajorCoordinateProgressions_eq
#print axioms verifierTransitionDispatchMuxInvocationLabelMajorCoordinateLabelFrames_eq_existing
#print axioms verifierTransitionDispatchMuxInvocationLabelMajorCoordinateLabelFrames_computableInPolyTime
