import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationDescriptorLabelReassembly

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.PolyBuilder
open CLRS.Chapter34.Turing.CookLevin

#check TransitionDispatchMuxInvocationView.labelPacketFrames
#check transitionDispatchMuxInvocationViewsSourceFrames_eq
#check verifierTransitionDispatchMuxInvocationDescriptorLabelPacketFrames_eq_artifacts
#check verifierTransitionDispatchMuxDescriptorInvocationSourceFrames_eq_reassembledViews

#print axioms transitionDispatchMuxInvocationViewsSourceFrames_eq
#print axioms verifierTransitionDispatchMuxInvocationDescriptorLabelPacketFrames_eq_artifacts
#print axioms verifierTransitionDispatchMuxDescriptorInvocationSourceFrames_eq_reassembledViews
