import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationLabelPacketReverse

open CLRS.Chapter34.Turing.CookLevin

#check TransitionDispatchMuxInvocationView.labelPacketRows
#check transitionDispatchMuxInvocationLabelPacketFamily
#check encode_transitionDispatchMuxInvocationLabelPacketFamily
#check encode_transitionDispatchMuxInvocationLabelPacketFamily_reverse
#check encode_verifierTransitionDispatchMuxInvocationDescriptorLabelPacketFamily
#check verifierTransitionDispatchMuxInvocationDescriptorLabelPacketReverse_run
#check encode_verifierTransitionDispatchMuxInvocationDescriptorLabelPacketFamily_reverse

#print axioms encode_transitionDispatchMuxInvocationLabelPacketFamily
#print axioms encode_transitionDispatchMuxInvocationLabelPacketFamily_reverse
#print axioms encode_verifierTransitionDispatchMuxInvocationDescriptorLabelPacketFamily
#print axioms verifierTransitionDispatchMuxInvocationDescriptorLabelPacketReverse_run
#print axioms encode_verifierTransitionDispatchMuxInvocationDescriptorLabelPacketFamily_reverse
