import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationLabelMajorPacketEncoding

open CLRS.Chapter34.Turing.CookLevin

#check TransitionDispatchMuxInvocationLabelMajorDescriptorPacket.frames
#check verifierTransitionDispatchMuxInvocationLabelMajorDescriptorPacketFamily
#check verifierTransitionDispatchMuxInvocationLabelMajorMarkedDescriptorFrames_eq_packets
#check verifierTransitionDispatchMuxInvocationLabelMajorDescriptorPacketFamily_encoding_eq
#check verifierTransitionDispatchMuxInvocationLabelMajorDescriptorPacketFamily_computableInPolyTime

#print axioms verifierTransitionDispatchMuxInvocationLabelMajorMarkedDescriptorFrames_eq_packets
#print axioms verifierTransitionDispatchMuxInvocationLabelMajorDescriptorPacketFamily_encoding_eq
#print axioms verifierTransitionDispatchMuxInvocationLabelMajorDescriptorPacketFamily_computableInPolyTime
