import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionInputCompiler

open CLRS.Chapter34.Turing.CookLevin

#check TransitionStmtStackAction
#check transitionStmtTerminalStackActions
#check transitionStmtStackActions_eval
#check transitionStmtOutputWires_terminal_stack

#print axioms transitionStmtOutputWires_terminal_stack
