import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationLayout

open CLRS.Chapter34.Turing.CookLevin

#check affineMuxFinCanonicalFrames_reassemble
#check transitionDispatchArtifactsFromSeed_muxInvocationView_frames
#check transitionDispatchArtifactsFromSeed_muxInvocationView_encode
#check transitionDispatchArtifactsFromSeed_muxInvocationViews_encode

#print axioms transitionDispatchArtifactsFromSeed_muxInvocationViews_encode
