import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationLabelMajorSelectorLabelFrames

open CLRS.Chapter34.Turing.CookLevin

#check transitionDispatchMuxInvocationLabelMajorDescriptorPackets_selectors
#check verifierTransitionDispatchMuxInvocationLabelMajorSelectorLabelFrames_eq
#check verifierTransitionDispatchMuxInvocationLabelMajorSelectorLabelFrames_eq_existing
#check verifierTransitionDispatchMuxInvocationLabelMajorSelectorLabelFrames_computableInPolyTime

#print axioms transitionDispatchMuxInvocationLabelMajorDescriptorPackets_selectors
#print axioms verifierTransitionDispatchMuxInvocationLabelMajorSelectorLabelFrames_eq
#print axioms verifierTransitionDispatchMuxInvocationLabelMajorSelectorLabelFrames_eq_existing
#print axioms verifierTransitionDispatchMuxInvocationLabelMajorSelectorLabelFrames_computableInPolyTime
