import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationDescriptorViews

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.PolyBuilder
open CLRS.Chapter34.Turing.CookLevin

#check transitionDispatchArtifactsFromSeed_selectors
#check transitionDispatchArtifactsFromSeed_muxFreshLayouts
#check transitionDispatchMuxInvocationViewsFromRows_maps
#check transitionDispatchMuxDescriptorInvocationViews_eq_artifacts
#check transitionDispatchMuxDescriptorInvocationSegments_eq_artifacts
#check transitionDispatchMuxDescriptorInvocationSegments_frames
#check verifierTransitionDispatchMuxDescriptorInvocationSegments_eq
#check verifierTransitionDispatchMuxDescriptorInvocationSourceFrames_eq

#print axioms transitionDispatchMuxDescriptorInvocationViews_eq_artifacts
#print axioms transitionDispatchMuxDescriptorInvocationSegments_eq_artifacts
#print axioms transitionDispatchMuxDescriptorInvocationSegments_frames
#print axioms verifierTransitionDispatchMuxDescriptorInvocationSourceFrames_eq
