import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionStatementAffineContextRecursiveBranchSelectorSource

open CLRS.Chapter34
open CLRS.Chapter34.Turing.CookLevin

#check transitionStmtRecursiveBranchSelectorSegment
#check transitionStmtRecursiveBranchSelectorSegment_values
#check verifierTransitionRecursiveBranchSelectorFamily
#check verifierTransitionRecursiveBranchSelectorFamily_encoding_eq
#check verifierTransitionRecursiveBranchSelectorFamily_computableInPolyTime
#print axioms verifierTransitionRecursiveBranchSelectorFamily_computableInPolyTime
