import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationDescriptorTrueLabelFrames

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.PolyBuilder
open CLRS.Chapter34.Turing.CookLevin

#check transitionDispatchTrueArmSpanLabelBoundarySelection_length
#check transitionDispatchTrueArmSpanLabelBoundarySelection_nonempty
#check verifierTransitionDispatchMuxInvocationDescriptorTrueDroppedSpanMarkedFrames_eq_rows
#check verifierTransitionDispatchMuxInvocationDescriptorTrueLabelFrames_eq
#check verifierTransitionDispatchMuxInvocationDescriptorTrueLabelFrames_computableInPolyTime

#print axioms transitionDispatchTrueArmSpanLabelBoundarySelection_length
#print axioms verifierTransitionDispatchMuxInvocationDescriptorTrueDroppedSpanMarkedFrames_eq_rows
#print axioms verifierTransitionDispatchMuxInvocationDescriptorTrueLabelFrames_eq
#print axioms verifierTransitionDispatchMuxInvocationDescriptorTrueLabelFrames_computableInPolyTime
