import CLRSLean.FourthEdition.Chapter_03.Section_03_2_Standard_Functions

#check CLRS.Chapter03.MonotonicallyIncreasing
#check CLRS.Chapter03.MonotonicallyDecreasing
#check CLRS.Chapter03.StrictlyIncreasing
#check CLRS.Chapter03.StrictlyDecreasing
#check CLRS.Chapter03.floor_ceil_int
#check CLRS.Chapter03.clrs_floor_bounds
#check CLRS.Chapter03.clrs_ceil_bounds
#check CLRS.Chapter03.neg_floor_eq_ceil_neg
#check CLRS.Chapter03.neg_ceil_eq_floor_neg
#check CLRS.Chapter03.floor_add_ceil_half
#check CLRS.Chapter03.floor_nested_div
#check CLRS.Chapter03.ceil_nested_div
#check CLRS.Chapter03.floor_nested_div_real
#check CLRS.Chapter03.ceil_nested_div_real
#check CLRS.Chapter03.ceilDiv_le_add_pred_div
#check CLRS.Chapter03.sub_pred_div_le_ceilDiv
#check CLRS.Chapter03.floor_int_add
#check CLRS.Chapter03.ceil_int_add
#check CLRS.Chapter03.mod_eq_sub_mul_div
#check CLRS.Chapter03.mod_lt_divisor
#check CLRS.Chapter03.int_mod_eq_sub_mul_floor
#check CLRS.Chapter03.int_mod_bounds
#check CLRS.Chapter03.pow_zero_identity
#check CLRS.Chapter03.pow_add_identity
#check CLRS.Chapter03.pow_mul_identity
#check CLRS.Chapter03.mul_pow_identity
#check CLRS.Chapter03.rpow_zero_identity
#check CLRS.Chapter03.rpow_one_identity
#check CLRS.Chapter03.rpow_neg_one_identity
#check CLRS.Chapter03.rpow_mul_identity
#check CLRS.Chapter03.rpow_swap_identity
#check CLRS.Chapter03.rpow_add_identity
#check CLRS.Chapter03.one_add_le_exp
#check CLRS.Chapter03.exp_series
#check CLRS.Chapter03.tendsto_one_add_inv_pow
#check CLRS.Chapter03.exp_sub_one_sub_id_isTheta_sq
#check CLRS.Chapter03.lg
#check CLRS.Chapter03.ln
#check CLRS.Chapter03.lgPow
#check CLRS.Chapter03.lgIterate
#check CLRS.Chapter03.log_mul_identity
#check CLRS.Chapter03.log_div_identity
#check CLRS.Chapter03.log_pow_identity
#check CLRS.Chapter03.rpow_logb_identity
#check CLRS.Chapter03.logb_mul_identity
#check CLRS.Chapter03.logb_rpow_identity
#check CLRS.Chapter03.logb_change_base
#check CLRS.Chapter03.logb_reciprocal
#check CLRS.Chapter03.logb_inv_identity
#check CLRS.Chapter03.rpow_logb_swap
#check CLRS.Chapter03.log_one_add_series
#check CLRS.Chapter03.log_one_add_le
#check CLRS.Chapter03.div_one_add_le_log_one_add
#check CLRS.Chapter03.factorial_recurrence
#check CLRS.Chapter03.stirling_formula
#check CLRS.Chapter03.stirling_lower_bound
#check CLRS.Chapter03.robbins_stirling_log_error_step
#check CLRS.Chapter03.robbinsAlpha
#check CLRS.Chapter03.robbinsAlpha_bounds
#check CLRS.Chapter03.factorial_eq_stirling_mul_exp_robbinsAlpha
#check CLRS.Chapter03.iterateFunction
#check CLRS.Chapter03.iterateFunction_zero
#check CLRS.Chapter03.iterateFunction_succ
#check CLRS.Chapter03.fibonacci_recurrence
#check CLRS.Chapter03.fibonacci_zero
#check CLRS.Chapter03.fibonacci_one
#check CLRS.Chapter03.goldenRatio_definition
#check CLRS.Chapter03.goldenConj_definition
#check CLRS.Chapter03.lgStar_four
#check CLRS.Chapter03.lgStar_sixteen
#check CLRS.Chapter03.lgStar_65536
#check CLRS.Chapter03.lgStar_two_pow_65536
