import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxFalseArmFrames

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.CookLevin
open CLRS.Chapter34.Turing.PolyBuilder

#check affineMuxFinCanonicalFrames_whenFalse_values
#check transitionDispatchLabelArtifacts_falseArmRows
#check transitionDispatchArtifactsFromSeed_falseArmRows
#check transitionDispatchFalseArmRowsFromSeed_head
#check transitionDispatchPreviousOutputDescriptorForms_value
#check encode_transitionDispatchPreviousOutputDescriptorForms
#check transitionDispatchPreviousOutputProgression_values
#check transitionDispatchPreviousOutputProgressionsForLabels_values
#check transitionDispatchFalseArmProgressions_values
#check transitionDispatchFalseArmDescriptorForms_value
#check encode_transitionDispatchFalseArmDescriptorForms
#check transitionDispatchFalseArmCoordinateSeeds_projection
#check verifierTransitionDispatchFalseArmDescriptorFrames_eq
#check verifierTransitionDispatchFalseArmDescriptorFrames_computableInPolyTime
#check verifierTransitionDispatchFalseArmCoordinateFrameStream_eq
#check verifierTransitionDispatchFalseArmCoordinateFrameStream_computableInPolyTime
#check verifierTransitionDispatchFalseArmValueFrames_eq_artifacts
#check verifierTransitionDispatchFalseArmValueFrames_computableInPolyTime

#print axioms affineMuxFinCanonicalFrames_whenFalse_values
#print axioms transitionDispatchLabelArtifacts_falseArmRows
#print axioms transitionDispatchArtifactsFromSeed_falseArmRows
#print axioms transitionDispatchFalseArmRowsFromSeed_head
#print axioms transitionDispatchPreviousOutputDescriptorForms_value
#print axioms encode_transitionDispatchPreviousOutputDescriptorForms
#print axioms transitionDispatchPreviousOutputProgression_values
#print axioms transitionDispatchPreviousOutputProgressionsForLabels_values
#print axioms transitionDispatchFalseArmProgressions_values
#print axioms transitionDispatchFalseArmDescriptorForms_value
#print axioms encode_transitionDispatchFalseArmDescriptorForms
#print axioms transitionDispatchFalseArmCoordinateSeeds_projection
#print axioms verifierTransitionDispatchFalseArmDescriptorFrames_eq
#print axioms verifierTransitionDispatchFalseArmDescriptorFrames_computableInPolyTime
#print axioms verifierTransitionDispatchFalseArmCoordinateFrameStream_eq
#print axioms verifierTransitionDispatchFalseArmCoordinateFrameStream_computableInPolyTime
#print axioms verifierTransitionDispatchFalseArmValueFrames_eq_artifacts
#print axioms verifierTransitionDispatchFalseArmValueFrames_computableInPolyTime
