import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationLabelPacketAssemblerBounds

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.CookLevin

#check TransitionDispatchMuxInvocationView.preparedLabelPacketFrames_length
#check transitionDispatchMuxInvocationLabelPacketAssemblerRowsSteps_le
#check transitionDispatchMuxInvocationLabelPacketAssemblerLabelSteps_le
#check transitionDispatchMuxInvocationLabelPacketAssemblerFamilySteps_le
#check verifierTransitionDispatchMuxInvocationLabelPacketAssemblerSteps_le

#print axioms transitionDispatchMuxInvocationLabelPacketAssemblerFamilySteps_le
#print axioms verifierTransitionDispatchMuxInvocationLabelPacketAssemblerSteps_le
