import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationLabelMajorFourRowDescriptorSource

open CLRS.Chapter34.Turing.CookLevin

#check transitionDispatchMuxInvocationLabelMajorFourRowDescriptorDelimiterTable_length
#check verifierTransitionDispatchMuxInvocationLabelMajorFourRowDescriptorFrames_eq
#check verifierTransitionDispatchMuxInvocationLabelMajorFourRowDescriptorFrames_computableInPolyTime

#print axioms transitionDispatchMuxInvocationLabelMajorFourRowDescriptorDelimiterTable_length
#print axioms verifierTransitionDispatchMuxInvocationLabelMajorFourRowDescriptorFrames_eq
#print axioms verifierTransitionDispatchMuxInvocationLabelMajorFourRowDescriptorFrames_computableInPolyTime
