import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionWidenedFallbackMarkedDescriptors

open CLRS.Chapter34.Turing.CookLevin

#check verifierTransitionWidenedFallbackMarkedDescriptorFrames_eq
#check verifierTransitionWidenedFallbackMarkedDescriptorFrames_computableInPolyTime

#print axioms verifierTransitionWidenedFallbackMarkedDescriptorFrames_eq
#print axioms verifierTransitionWidenedFallbackMarkedDescriptorFrames_computableInPolyTime
