import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationDescriptorFourWayRoute

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.PolyBuilder
open CLRS.Chapter34.Turing.CookLevin

#check verifierTransitionDispatchMuxInvocationDescriptorFourWaySuffixGroups_encoding_eq
#check verifierTransitionDispatchMuxInvocationDescriptorFourWayRows_eq
#check verifierTransitionDispatchMuxInvocationDescriptorFourWayRows_computableInPolyTime

#print axioms verifierTransitionDispatchMuxInvocationDescriptorFourWaySuffixGroups_encoding_eq
#print axioms verifierTransitionDispatchMuxInvocationDescriptorFourWayRows_eq
#print axioms verifierTransitionDispatchMuxInvocationDescriptorFourWayRows_computableInPolyTime
