import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationDescriptorSelectorLabelFrames

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.PolyBuilder
open CLRS.Chapter34.Turing.CookLevin

#check verifierTransitionDispatchMuxInvocationDescriptorSelectorValueRows
#check verifierTransitionDispatchMuxInvocationDescriptorSelectorLabelFrames_eq_semantic
#check verifierTransitionDispatchMuxInvocationDescriptorSelectorLabelFrames_computableInPolyTime

#print axioms verifierTransitionDispatchMuxInvocationDescriptorSelectorLabelFrames_eq_semantic
#print axioms verifierTransitionDispatchMuxInvocationDescriptorSelectorLabelFrames_computableInPolyTime
