import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionProgramStatementDescriptorSource

open CLRS.Chapter34 Turing
open CLRS.Chapter34.Turing CookLevin PolyBuilder

#check verifierTransitionLabelListStatementDescriptorSeedRowSource
#check verifierTransitionProgramStatementDescriptorSeedRowSource
#check verifierTransitionProgramStatementDescriptorFamily
#check verifierTransitionProgramStatementDescriptorFamily_rows
#check verifierTransitionProgramStatementDescriptorFamily_computableInPolyTime

#print axioms verifierTransitionProgramStatementDescriptorFamily_rows
#print axioms verifierTransitionProgramStatementDescriptorFamily_computableInPolyTime
