import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationLabelPacketAssemblerTerminal

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.CookLevin

#check transitionDispatchMuxInvocationLabelPacketAssemblerEmptySteps
#check transitionDispatchMuxInvocationLabelPacketAssembler_empty
#check transitionDispatchMuxInvocationLabelPacketAssemblerFinishSteps
#check transitionDispatchMuxInvocationLabelPacketAssembler_finish

#print axioms transitionDispatchMuxInvocationLabelPacketAssembler_empty
#print axioms transitionDispatchMuxInvocationLabelPacketAssembler_finish
