import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationLabelPacketAssemblerFamily

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.CookLevin

#check transitionDispatchMuxInvocationLabelPacketAssemblerFamilySteps
#check transitionDispatchMuxInvocationLabelPacketAssembler_views
#check transitionDispatchMuxInvocationLabelPacketAssembler_views_sourceFrames

#print axioms transitionDispatchMuxInvocationLabelPacketAssembler_views
#print axioms transitionDispatchMuxInvocationLabelPacketAssembler_views_sourceFrames
