import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorValidityRowOneHotOperands

open CLRS.Chapter34.Turing.CookLevin

#check affineExactlyOneRuntimeFrameAt
#check affineExactlyOnePrefixCost_succ
#check affineExactlyOneRuntimeFrameAt_succ_start
#check affineExactlyOneRuntimeFrameAt_add_const_start
#check affineExactlyOneRuntimeFrames_eq_ofFn
#check arithmeticOneHotGroupFrame
#check arithmeticStackCellOneHotProgression
#check arithmeticOneHotGroupFrame_stackCell_rowBase
#check arithmeticOneHotGroupFrame_stackCell_count
#check arithmeticOneHotGroupFrame_stackCell_start
#check arithmeticStackCellOneHotProgression_frames
#check arithmeticOneHotGroupFrame_label
#check arithmeticOneHotGroupFrame_state
#check arithmeticOneHotGroupFrame_stackHeight_count
#check arithmeticOneHotPrefixFrames
#check arithmeticOneHotPrefixFrames_eq_explicit
#check arithmeticStackOneHotFrames
#check arithmeticStackOneHotFrames_eq_groups
#check arithmeticStructuredOneHotFrames
#check arithmeticStructuredOneHotFrames_eq_raw
#check arithmeticRawOneHotFrames_eq_groupFrames
#check verifierOneHotCellCounts
#check affineExactlyOneStructuredRowFrames_eq_arithmeticRaw
#check validityRowSeedOneHotFrames
#check validityRowSeedOneHotFrames_eq_expand
#check validityRowSeedOneHotFamily
#check validityRowSeedOneHotFamily_eq_canonical
#check verifierValidityRowStructuredSeeds
#check verifierValidityRowOneHotSourceProgram
#check verifierValidityRowOneHotSource_run
#check verifierValidityRowStructuredSeeds_computableInPolyTime
#check verifierValidityRowOneHotCompactFamily_computableInPolyTime
#check verifierValidityRowOneHotOperands_computableInPolyTime
#check verifierValidityRowOneHotOutputInvocationFrames
#check verifierValidityRowOneHotOutputInvocationFrames_eq_canonical
#check verifierValidityRowOneHotOutputInvocationFrames_computableInPolyTime
#check verifierValidityRowSeedMarkedOneHotFrames
#check verifierValidityRowSeedMarkedOneHotFrames_eq_rows
#check verifierValidityRowSeedMarkedOneHotStructuredSeeds_computableInPolyTime
#check verifierValidityRowSeedMarkedOneHotFrames_computableInPolyTime
#check verifierValidityRowSeedCarrierOutputInvocationFrames
#check verifierValidityRowSeedCarrierOutputInvocationFrames_eq_rows
#check verifierValidityRowSeedCarrierOutputInvocationFrames_computableInPolyTime
#check verifierValidityRowSeedCarrierStructuredSeeds_computableInPolyTime
#check verifierValidityRowSeedFirstOutputInvocationFrames
#check verifierValidityRowSeedFirstOutputInvocationFrames_eq_rows
#check verifierValidityRowSeedFirstOutputInvocationFrames_computableInPolyTime

#print axioms affineExactlyOneRuntimeFrames_eq_ofFn
#print axioms arithmeticRawOneHotFrames_eq_groupFrames
#print axioms affineExactlyOneStructuredRowFrames_eq_arithmeticRaw
#print axioms arithmeticStackCellOneHotProgression_frames
#print axioms arithmeticStructuredOneHotFrames_eq_raw
#print axioms validityRowSeedOneHotFamily_eq_canonical
#print axioms verifierValidityRowOneHotSource_run
#print axioms verifierValidityRowOneHotOperands_computableInPolyTime
#print axioms verifierValidityRowOneHotOutputInvocationFrames_eq_canonical
#print axioms verifierValidityRowOneHotOutputInvocationFrames_computableInPolyTime
#print axioms verifierValidityRowSeedMarkedOneHotFrames_eq_rows
#print axioms verifierValidityRowSeedMarkedOneHotFrames_computableInPolyTime
#print axioms verifierValidityRowSeedCarrierOutputInvocationFrames_eq_rows
#print axioms verifierValidityRowSeedCarrierOutputInvocationFrames_computableInPolyTime
#print axioms verifierValidityRowSeedCarrierStructuredSeeds_computableInPolyTime
#print axioms verifierValidityRowSeedFirstOutputInvocationFrames_eq_rows
#print axioms verifierValidityRowSeedFirstOutputInvocationFrames_computableInPolyTime
