import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionAffineHeadControllerSource

open CLRS.Chapter34 Turing
open CLRS.Chapter34.Turing CookLevin PolyBuilder

#check verifierTransitionAffineHeadControllerMarkedFrames
#check verifierTransitionAffineHeadControllerMarkedFrames_eq_rows
#check verifierTransitionAffineHeadControllerMarkedFrames_computableInPolyTime

#print axioms verifierTransitionAffineHeadControllerMarkedFrames_eq_rows
#print axioms verifierTransitionAffineHeadControllerMarkedFrames_computableInPolyTime
