import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorValidityRowInputCompiler

open CLRS.Chapter34.Turing.CookLevin

#check ValidityRowOperandPacket
#check validityRowSeedFamilyInput
#check validityRowSeedFamilyInput_eq
#check verifierValidityRowFamilyInputTarget
#check verifierValidityRowFamilyInputTarget_eq_canonical
#check verifierValidityRowFamilyInputTarget_eq_packets
#check verifierValidityRowOperandPackets_oneHot
#check verifierValidityRowOperandPackets_halted
#check verifierValidityRowOperandPackets_tail
#check arithmeticValidityRowFixedOperandForms_eq
#check verifierValidityRowUnifiedPayloadFamily_encoding_eq
#check verifierValidityRowUnifiedOperandPayloadFrames
#check verifierValidityRowUnifiedOperandPayloadFrames_eq_rows
#check verifierValidityRowUnifiedOperandPayloadFrames_computableInPolyTime

#print axioms validityRowSeedFamilyInput_eq
#print axioms verifierValidityRowFamilyInputTarget_eq_canonical
#print axioms verifierValidityRowFamilyInputTarget_eq_packets
#print axioms verifierValidityRowOperandPackets_oneHot
#print axioms verifierValidityRowOperandPackets_halted
#print axioms verifierValidityRowOperandPackets_tail
#print axioms arithmeticValidityRowFixedOperandForms_eq
#print axioms verifierValidityRowUnifiedPayloadFamily_encoding_eq
#print axioms verifierValidityRowUnifiedOperandPayloadFrames_eq_rows
#print axioms verifierValidityRowUnifiedOperandPayloadFrames_computableInPolyTime
