import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.PolyBuilder.TransitionFamilyController

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.PolyBuilder

#check AffineTransitionFamilyLabel
#check affineTransitionFamilyRevProgram
#check encodeAffineTransitionFamily
#check affineTransitionFamilyGateStream
#check affineTransitionFamilyRunSteps
#check affineTransitionFamily_run
#check affineTransitionFamily_steps_le

#print axioms affineTransitionFamily_run
#print axioms affineTransitionFamily_steps_le
