import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorValidityRowInputCompiler

open CLRS.Chapter34.Turing.CookLevin

#check ValidityRowOperandPacket
#check validityRowSeedFamilyInput
#check validityRowSeedFamilyInput_eq
#check verifierValidityRowFamilyInputTarget
#check verifierValidityRowFamilyInputTarget_eq_canonical
#check verifierValidityRowFamilyInputTarget_eq_packets
#check verifierValidityRowOperandPackets_oneHot
#check verifierValidityRowOperandPackets_halted
#check verifierValidityRowOperandPackets_tail
#check arithmeticValidityRowFixedOperandForms_eq
#check verifierValidityRowUnifiedPayloadFamily_encoding_eq
#check verifierValidityRowUnifiedOperandPayloadFrames
#check verifierValidityRowUnifiedOperandPayloadFrames_eq_rows
#check verifierValidityRowUnifiedOperandPayloadFrames_computableInPolyTime
#check arithmeticValidityRowFixedOperandDelimiters_length
#check verifierValidityRowUnifiedOperandPayloadFrames_eq_spliceInput
#check verifierValidityRowSplicedOperandPayloadFrames
#check verifierValidityRowSplicedOperandPayloadFrames_eq_rows
#check arithmeticValidityRowFixedEncoding_eq
#check verifierValidityRowSplicedOperandPayloadFrames_eq_explicit
#check verifierValidityRowSplicedOperandPayloadFrames_computableInPolyTime
#check arithmeticValidityRowPlainOperandDelimiters_length
#check verifierValidityRowPlainOperandPayloadFrames
#check verifierValidityRowPlainOperandPayloadFrames_eq_rows
#check verifierValidityRowPlainOperandPayloadFrames_computableInPolyTime
#check verifierValidityRowPlainOperandPayloadFamily_encoding_eq
#check verifierValidityRowDuplicatedPlainOperandPayloadFrames
#check verifierValidityRowDuplicatedPlainOperandPayloadFrames_eq_rows
#check verifierValidityRowDuplicatedPlainOperandPayloadFrames_computableInPolyTime
#check verifierValidityRowDuplicatedRouteFamily
#check verifierValidityRowDuplicatedRouteFamily_encoding_eq
#check verifierValidityRowRoutedOperandPayloadFrames
#check verifierValidityRowRoutedOperandPayloadFrames_eq_rows
#check verifierValidityRowRoutedOperandPayloadFrames_computableInPolyTime
#check verifierValidityRowExpandedPrefixPayloadFamily
#check verifierValidityRowExpandedPrefixPayloadFamily_encoding_eq
#check verifierValidityRowExpandedPrefixPayloadFrames
#check verifierValidityRowExpandedPrefixPayloadFrames_eq_rows
#check verifierValidityRowExpandedPrefixPayloadFrames_computableInPolyTime
#check verifierValidityRowCompactProjectionFamily
#check verifierValidityRowCompactProjectionFamily_encoding_eq
#check verifierValidityRowProjectedOperandFrames
#check verifierValidityRowProjectedOperandFrames_eq_rows
#check verifierValidityRowProjectedOperandFrames_computableInPolyTime
#check verifierValidityRowProjectedFixedPrefixFamily
#check verifierValidityRowProjectedFixedPrefixFamily_encoding_eq
#check verifierValidityRowCompactSourceFrames
#check verifierValidityRowCompactSourceFrames_eq_rows
#check verifierValidityRowCompactSourceFrames_eq_explicit
#check arithmeticValidityTailSplicedRow_eq_sourceInvocation
#check verifierValidityRowCompactSourceFrames_eq_invocations
#check verifierValidityRowCompactSourceFrames_computableInPolyTime
#check verifierValidityRowLeadingFixedPrefixFamily
#check verifierValidityRowLeadingFixedPrefixFamily_encoding_eq
#check verifierValidityRowFixedPrefixMaterializedFrames
#check verifierValidityRowFixedPrefixMaterializedFrames_eq_rows
#check verifierValidityRowFixedPrefixMaterializedFrames_eq_explicit
#check verifierValidityRowFixedPrefixMaterializedFrames_computableInPolyTime

#print axioms validityRowSeedFamilyInput_eq
#print axioms verifierValidityRowFamilyInputTarget_eq_canonical
#print axioms verifierValidityRowFamilyInputTarget_eq_packets
#print axioms verifierValidityRowOperandPackets_oneHot
#print axioms verifierValidityRowOperandPackets_halted
#print axioms verifierValidityRowOperandPackets_tail
#print axioms arithmeticValidityRowFixedOperandForms_eq
#print axioms verifierValidityRowUnifiedPayloadFamily_encoding_eq
#print axioms verifierValidityRowUnifiedOperandPayloadFrames_eq_rows
#print axioms verifierValidityRowUnifiedOperandPayloadFrames_computableInPolyTime
#print axioms arithmeticValidityRowFixedOperandDelimiters_length
#print axioms verifierValidityRowUnifiedOperandPayloadFrames_eq_spliceInput
#print axioms verifierValidityRowSplicedOperandPayloadFrames_eq_rows
#print axioms arithmeticValidityRowFixedEncoding_eq
#print axioms verifierValidityRowSplicedOperandPayloadFrames_eq_explicit
#print axioms verifierValidityRowSplicedOperandPayloadFrames_computableInPolyTime
#print axioms arithmeticValidityRowPlainOperandDelimiters_length
#print axioms verifierValidityRowPlainOperandPayloadFrames_eq_rows
#print axioms verifierValidityRowPlainOperandPayloadFrames_computableInPolyTime
#print axioms verifierValidityRowPlainOperandPayloadFamily_encoding_eq
#print axioms verifierValidityRowDuplicatedPlainOperandPayloadFrames_eq_rows
#print axioms verifierValidityRowDuplicatedPlainOperandPayloadFrames_computableInPolyTime
#print axioms verifierValidityRowDuplicatedRouteFamily_encoding_eq
#print axioms verifierValidityRowRoutedOperandPayloadFrames_eq_rows
#print axioms verifierValidityRowRoutedOperandPayloadFrames_computableInPolyTime
#print axioms verifierValidityRowExpandedPrefixPayloadFamily_encoding_eq
#print axioms verifierValidityRowExpandedPrefixPayloadFrames_eq_rows
#print axioms verifierValidityRowExpandedPrefixPayloadFrames_computableInPolyTime
#print axioms verifierValidityRowCompactProjectionFamily_encoding_eq
#print axioms verifierValidityRowProjectedOperandFrames_eq_rows
#print axioms verifierValidityRowProjectedOperandFrames_computableInPolyTime
#print axioms verifierValidityRowProjectedFixedPrefixFamily_encoding_eq
#print axioms verifierValidityRowCompactSourceFrames_eq_rows
#print axioms verifierValidityRowCompactSourceFrames_eq_explicit
#print axioms arithmeticValidityTailSplicedRow_eq_sourceInvocation
#print axioms verifierValidityRowCompactSourceFrames_eq_invocations
#print axioms verifierValidityRowCompactSourceFrames_computableInPolyTime
#print axioms verifierValidityRowLeadingFixedPrefixFamily_encoding_eq
#print axioms verifierValidityRowFixedPrefixMaterializedFrames_eq_rows
#print axioms verifierValidityRowFixedPrefixMaterializedFrames_eq_explicit
#print axioms verifierValidityRowFixedPrefixMaterializedFrames_computableInPolyTime
