import CLRSLean.FourthEdition.Chapter_25

#check CLRS.Chapter26.Matching.matchedLeft
#check CLRS.Chapter26.Matching.matchedRight
#check CLRS.Chapter26.Matching.IsMatchedLeft
#check CLRS.Chapter26.Matching.IsMatchedRight
#check CLRS.Chapter26.Matching.IsUnmatchedLeft
#check CLRS.Chapter26.Matching.IsUnmatchedRight
#check CLRS.Chapter26.Matching.IsMaximum
#check CLRS.Chapter26.Matching.empty
#check CLRS.Chapter26.Matching.empty_size
#check CLRS.Chapter26.Matching.matchedLeft_card
#check CLRS.Chapter26.Matching.matchedRight_card
#check CLRS.Chapter26.Matching.mem_matchedLeft_iff
#check CLRS.Chapter26.Matching.mem_matchedRight_iff
#check CLRS.Chapter26.Matching.isUnmatchedLeft_iff_not_matched
#check CLRS.Chapter26.Matching.isUnmatchedRight_iff_not_matched
#check CLRS.Chapter26.Matching.mem_L_of_isMatchedLeft
#check CLRS.Chapter26.Matching.mem_R_of_isMatchedRight
#check CLRS.Chapter26.Matching.not_mem_R_of_mem_L
#check CLRS.Chapter26.Matching.not_mem_L_of_mem_R

#check CLRS.Matchings.altEdges
#check CLRS.Matchings.IsAugmentingPath
#check CLRS.Matchings.exists_augment_single
#check CLRS.Matchings.exists_swap
#check CLRS.Matchings.exists_augment
#check CLRS.Matchings.not_isMaximum_of_isAugmentingPath
#check CLRS.Matchings.exists_isChain_of_reflTransGen
#check CLRS.Matchings.exists_nodup_isChain
#check CLRS.Matchings.exists_nodup_path_of_reflTransGen
#check CLRS.Matchings.matchingToFlow_f_source
#check CLRS.Matchings.matchingToFlow_f_right
#check CLRS.Matchings.matchingToFlow_f_lr
#check CLRS.Matchings.matchingToFlow_residualEdge_source
#check CLRS.Matchings.matchingToFlow_residualEdge_inl_inl
#check CLRS.Matchings.matchingToFlow_residualEdge_right
#check CLRS.Matchings.matchingToFlow_not_residualEdge_source_inr
#check CLRS.Matchings.matchingToFlow_not_residualEdge_left_sink
#check CLRS.Matchings.matchingToFlow_not_residualEdge_right_source
#check CLRS.Matchings.translation_inner
#check CLRS.Matchings.augmentingPath_of_hasAugmentingPath
#check CLRS.Matchings.berge_maximum_iff_no_augmentingPath
#check CLRS.Matchings.flowMethod_finds_maximum_matching

#check CLRS.Matchings.PreferenceProfile
#check CLRS.Matchings.Pairing
#check CLRS.Matchings.Pairing.IsPerfect
#check CLRS.Matchings.Pairing.BlockingPair
#check CLRS.Matchings.Pairing.Stable
#check CLRS.StableMarriage.GSState
#check CLRS.StableMarriage.gs
#check CLRS.StableMarriage.gs_terminates_le_n_sq
#check CLRS.StableMarriage.gs_stable
#check CLRS.StableMarriage.stable_matching_exists
