import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationLabelMajorFourRowDescriptorSemantics

open CLRS.Chapter34.Turing.CookLevin

#check TransitionDispatchMuxInvocationLabelMajorDescriptorPacket.fourRowDescriptorValueGroups
#check verifierTransitionDispatchMuxInvocationLabelMajorFourRowDescriptorFrames_eq_packets

#print axioms TransitionDispatchMuxInvocationLabelMajorDescriptorPacket.fourRowDescriptorValueGroups
#print axioms verifierTransitionDispatchMuxInvocationLabelMajorFourRowDescriptorFrames_eq_packets
