import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationLabelMajorPacketSemantics

open CLRS.Chapter34.Turing.CookLevin

#check TransitionDispatchMuxInvocationLabelMajorDescriptorPacket.descriptorValues
#check TransitionDispatchMuxInvocationLabelMajorDescriptorPacket.view
#check transitionDispatchMuxInvocationLabelMajorDescriptorPackets_values
#check transitionDispatchMuxInvocationLabelMajorDescriptorPackets_views
#check verifierTransitionDispatchMuxInvocationLabelMajorDescriptorPackets_labelPacketFrames

#print axioms transitionDispatchMuxInvocationLabelMajorDescriptorPackets_values
#print axioms transitionDispatchMuxInvocationLabelMajorDescriptorPackets_views
#print axioms verifierTransitionDispatchMuxInvocationLabelMajorDescriptorPackets_labelPacketFrames
