import CLRSLean.Chapter_34.Section_34_5_NP_Complete_Problems.HamiltonianCycle.ReductionMachine.Incidence.Scanner.Runtime

#check CLRS.Chapter34.Turing.HamiltonianCycle.ReductionMachine.Incidence.Scanner.computableInPolyTime
#check CLRS.Chapter34.Turing.HamiltonianCycle.ReductionMachine.Incidence.Scanner.stream_encode

#print axioms CLRS.Chapter34.Turing.HamiltonianCycle.ReductionMachine.Incidence.Scanner.stream_encode
#print axioms CLRS.Chapter34.Turing.HamiltonianCycle.ReductionMachine.Incidence.Scanner.computableInPolyTime
