import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationDescriptorSemantics

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.PolyBuilder
open CLRS.Chapter34.Turing.CookLevin

#check transitionDispatchTrueArmSpanProgression_firstValues
#check transitionDispatchTrueArmSpanProgressionsFrom_firstValues
#check TransitionDispatchTrueArmNormalizedLayout.affineSpanProgressions_values
#check transitionDispatchTrueArmSpanProgressionGroups_values
#check transitionDispatchTrueArmSpanProgressionGroups_eq_seed

#print axioms transitionDispatchTrueArmSpanProgressionsFrom_firstValues
#print axioms TransitionDispatchTrueArmNormalizedLayout.affineSpanProgressions_values
#print axioms transitionDispatchTrueArmSpanProgressionGroups_eq_seed
