import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationLabelPacketAssemblerVerifier

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.CookLevin

#check verifierTransitionDispatchMuxInvocationViews
#check verifierTransitionDispatchMuxInvocationViews_rowAligned
#check transitionDispatchMuxInvocationLabelPacketAssembler_halt
#check verifierTransitionDispatchMuxInvocationLabelPacketAssembler_rev
#check verifierTransitionDispatchMuxInvocationLabelPacketAssembler_rev_source

#print axioms verifierTransitionDispatchMuxInvocationViews_rowAligned
#print axioms transitionDispatchMuxInvocationLabelPacketAssembler_halt
#print axioms verifierTransitionDispatchMuxInvocationLabelPacketAssembler_rev
#print axioms verifierTransitionDispatchMuxInvocationLabelPacketAssembler_rev_source
