import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationLabelMajorFalseLabelFrames

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.CookLevin

#check verifierTransitionDispatchMuxInvocationLabelMajorFalseLabelFrames_eq_existing
#check verifierTransitionDispatchMuxInvocationLabelMajorFalseLabelFrames_computableInPolyTime
#print axioms verifierTransitionDispatchMuxInvocationLabelMajorFalseLabelFrames_eq_existing
