import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationLabelPacketPipeline

namespace CLRS.Chapter34.Turing.CookLevin

#check verifierTransitionDispatchMuxInvocationFrames_computableInPolyTime_of_preparedLabelPacketCompiler
#check verifierTransitionDispatchMuxInvocationPreparedLabelPacketFrames_computableInPolyTime_of_labelPacketCompiler
#check verifierTransitionDispatchMuxInvocationFrames_computableInPolyTime_of_labelPacketCompiler

#print axioms verifierTransitionDispatchMuxInvocationFrames_computableInPolyTime_of_labelPacketCompiler

end CLRS.Chapter34.Turing.CookLevin
