import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionStatementStackRouteDescriptorSelectionSemantics

open CLRS.Chapter34.Turing.PolyBuilder
open CLRS.Chapter34.Turing.CookLevin

#check selectListByBool
#check encodeUnaryFramePeriodicSelectedMarkedRows_eq
#check encodeUnaryFramePeriodicSelectedMarkedProgressions
#check transitionStackRouteHeightDescriptorSelection_progressions
#check transitionStackRouteCellDescriptorSelection_progressions
#check verifierTransitionStackRouteHeightMarkedDescriptorFrames_eq_routeProgressions
#check verifierTransitionStackRouteCellMarkedDescriptorFrames_eq_routeProgressions

#print axioms transitionStackRouteHeightDescriptorSelection_progressions
#print axioms transitionStackRouteCellDescriptorSelection_progressions
#print axioms verifierTransitionStackRouteHeightMarkedDescriptorFrames_eq_routeProgressions
#print axioms verifierTransitionStackRouteCellMarkedDescriptorFrames_eq_routeProgressions
