import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.PolyBuilder.TransitionFamilyScript

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.PolyBuilder

#check compileTransitionFamilyScripts
#check compileTransitionFamilyScripts_length
#check compileTransitionFamilyScripts_gateStream_eq_trace
#check compileTransitionFamilyScriptsAt
#check compileTransitionFamilyScriptsAt_length
#check compileTransitionFamilyScriptsAt_gateStream_eq
#check compileTransitionFamilyScriptsAt_run
#check compileTransitionFamilyScriptsAt_steps_le

#print axioms compileTransitionFamilyScripts_gateStream_eq_trace
#print axioms compileTransitionFamilyScriptsAt_gateStream_eq
#print axioms compileTransitionFamilyScriptsAt_run
#print axioms compileTransitionFamilyScriptsAt_steps_le
