import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionStatementStackRouteAffineSpanTerminal

open CLRS.Chapter34.Turing.CookLevin

#check TransitionStmtTerminalRowLayout.stackAffineSpanRoute
#check TransitionStmtTerminalRowLayout.stackAffineSpanRoute_eval

#print axioms TransitionStmtTerminalRowLayout.stackAffineSpanRoute_eval
