import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionInputCompiler

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.CookLevin

#check transitionSeedFamilyScripts
#check transitionSeedFamilyInput
#check transitionSeedFamilyUnaryInput
#check transitionSeedLocalUnaryInput
#check transitionSeedFamilyUnaryInput_eq_flatMap
#check transitionSeedFamilyInput_eq_map_data
#check verifierTransitionFamilyScripts
#check verifierTransitionFamilyInputTarget
#check verifierTransitionFamilyUnaryInputTarget
#check verifierTransitionFamilyInputTarget_eq_map_data
#check verifierTransitionFamilyUnaryInputTarget_eq_flatMap
#check transitionRowSeedTriples
#check verifierTransitionRowSeedFrames_eq_triples
#check verifierTransitionRowMarkedSeedFrames
#check verifierTransitionRowMarkedSeedFrames_eq_seeds
#check verifierTransitionRowMarkedSeedFrames_computableInPolyTime
#check verifierTransitionFamilyScripts_eq_canonical
#check verifierTransitionFamilyInputTarget_eq_canonical
#check verifierTransitionFamilyGateStream_eq
#check verifierTransitionFamily_run
#check verifierTransitionFamilyInputTarget_computableInPolyTime_of_unaryCompiler
#check verifierTransitionGateStream_computableInPolyTime_of_inputCompiler

#print axioms verifierTransitionFamilyScripts_eq_canonical
#print axioms verifierTransitionFamilyInputTarget_eq_canonical
#print axioms verifierTransitionFamilyUnaryInputTarget_eq_flatMap
#print axioms verifierTransitionRowMarkedSeedFrames_eq_seeds
#print axioms verifierTransitionRowMarkedSeedFrames_computableInPolyTime
#print axioms verifierTransitionFamilyGateStream_eq
#print axioms verifierTransitionFamily_run
#print axioms verifierTransitionFamilyInputTarget_computableInPolyTime_of_unaryCompiler
#print axioms verifierTransitionGateStream_computableInPolyTime_of_inputCompiler
