import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationDescriptorLabelChannels

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.PolyBuilder
open CLRS.Chapter34.Turing.CookLevin

#check verifierTransitionDispatchMuxInvocationDescriptorLabelPacketSelectorFrames_eq
#check verifierTransitionDispatchMuxInvocationDescriptorLabelPacketCoordinateFrames_eq
#check verifierTransitionDispatchMuxInvocationDescriptorLabelPacketTrueFrames_eq
#check verifierTransitionDispatchMuxInvocationDescriptorLabelPacketFalseFrames_eq

#print axioms verifierTransitionDispatchMuxInvocationDescriptorLabelPacketSelectorFrames_eq
#print axioms verifierTransitionDispatchMuxInvocationDescriptorLabelPacketCoordinateFrames_eq
#print axioms verifierTransitionDispatchMuxInvocationDescriptorLabelPacketTrueFrames_eq
#print axioms verifierTransitionDispatchMuxInvocationDescriptorLabelPacketFalseFrames_eq
