import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationLabelPacketPrepare

open CLRS.Chapter34.Turing.CookLevin

#check transitionDispatchMuxInvocationLabelPacketReverseAt
#check TransitionDispatchMuxInvocationView.preparedLabelPacketRows
#check transitionDispatchMuxInvocationLabelPacket_prepare_rows
#check encode_transitionDispatchMuxInvocationLabelPacketFamily_prepare
#check verifierTransitionDispatchMuxInvocationDescriptorPreparedLabelPacketFrames_eq
#check transitionDispatchMuxInvocationLabelPacketPrepare_computableInPolyTime

#print axioms transitionDispatchMuxInvocationLabelPacket_prepare_rows
#print axioms encode_transitionDispatchMuxInvocationLabelPacketFamily_prepare
#print axioms verifierTransitionDispatchMuxInvocationDescriptorPreparedLabelPacketFrames_eq
#print axioms transitionDispatchMuxInvocationLabelPacketPrepare_computableInPolyTime
