import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationLabelMajorTrueLabelFrames

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.CookLevin

#check verifierTransitionDispatchMuxInvocationLabelMajorTrueLabelFrames_eq_existing
#check verifierTransitionDispatchMuxInvocationLabelMajorTrueLabelFrames_computableInPolyTime
#print axioms verifierTransitionDispatchMuxInvocationLabelMajorTrueLabelFrames_eq_existing
