import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionWidenedFallbackFrames

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.CookLevin
open CLRS.Chapter34.Turing.PolyBuilder

#check transitionWidenedFallbackValues_eq_canonical
#check transitionWidenedFallbackStackHeightValues_eq_parts
#check transitionWidenedFallbackBlankCellValues_eq_parts
#check transitionWidenedFallbackStackCellValues_eq_parts
#check transitionWidenedFallbackSegmentDescriptorForms_value
#check transitionWidenedFallbackDescriptorForms_value
#check encode_transitionWidenedFallbackDescriptorForms
#check transitionWidenedFallbackSegments_values
#check transitionWidenedFallbackCoordinateSeeds_projection
#check verifierTransitionWidenedFallbackDescriptorFrames_eq
#check verifierTransitionWidenedFallbackDescriptorFrames_computableInPolyTime
#check verifierTransitionWidenedFallbackCoordinateFrameStream_eq
#check verifierTransitionWidenedFallbackCoordinateFrameStream_computableInPolyTime
#check verifierTransitionWidenedFallbackValueFrames_eq
#check verifierTransitionWidenedFallbackValueFrames_eq_canonical
#check verifierTransitionWidenedFallbackValueFrames_computableInPolyTime

#print axioms transitionWidenedFallbackValues_eq_canonical
#print axioms transitionWidenedFallbackStackHeightValues_eq_parts
#print axioms transitionWidenedFallbackBlankCellValues_eq_parts
#print axioms transitionWidenedFallbackStackCellValues_eq_parts
#print axioms transitionWidenedFallbackSegmentDescriptorForms_value
#print axioms transitionWidenedFallbackDescriptorForms_value
#print axioms encode_transitionWidenedFallbackDescriptorForms
#print axioms transitionWidenedFallbackSegments_values
#print axioms transitionWidenedFallbackCoordinateSeeds_projection
#print axioms verifierTransitionWidenedFallbackDescriptorFrames_eq
#print axioms verifierTransitionWidenedFallbackDescriptorFrames_computableInPolyTime
#print axioms verifierTransitionWidenedFallbackCoordinateFrameStream_eq
#print axioms verifierTransitionWidenedFallbackCoordinateFrameStream_computableInPolyTime
#print axioms verifierTransitionWidenedFallbackValueFrames_eq
#print axioms verifierTransitionWidenedFallbackValueFrames_eq_canonical
#print axioms verifierTransitionWidenedFallbackValueFrames_computableInPolyTime
