import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationDescriptorFalseExecute

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.PolyBuilder
open CLRS.Chapter34.Turing.CookLevin

#check verifierTransitionDispatchMuxInvocationDescriptorFalseMarkedRows_eq
#check verifierTransitionDispatchMuxInvocationDescriptorFalseFrames_eq
#check verifierTransitionDispatchMuxInvocationDescriptorFalseProgressionFrames_eq
#check verifierTransitionDispatchMuxInvocationDescriptorFalseProgressionFrames_computableInPolyTime

#print axioms verifierTransitionDispatchMuxInvocationDescriptorFalseMarkedRows_eq
#print axioms verifierTransitionDispatchMuxInvocationDescriptorFalseFrames_eq
#print axioms verifierTransitionDispatchMuxInvocationDescriptorFalseProgressionFrames_eq
#print axioms verifierTransitionDispatchMuxInvocationDescriptorFalseProgressionFrames_computableInPolyTime
