import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationLabelPacketAssemblerVerifierRuntime

namespace CLRS.Chapter34.Turing.CookLevin

#check verifierTransitionDispatchMuxInvocationAlignedViewFamily
#check verifierTransitionDispatchMuxInvocationAlignedViewFamily_preparedFrames
#check verifierTransitionDispatchMuxInvocationAlignedViewFamily_segments
#check verifierTransitionDispatchMuxInvocationFrames_fromPreparedLabelPackets_computableInPolyTime

#print axioms verifierTransitionDispatchMuxInvocationFrames_fromPreparedLabelPackets_computableInPolyTime

end CLRS.Chapter34.Turing.CookLevin
