import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxTrueArmTerminalPrefixFrames

open CLRS.Chapter34.Turing.CookLevin

#check verifierTransitionDispatchTerminalPrefixValueFrames_eq
#check verifierTransitionDispatchTerminalPrefixValueFrames_computableInPolyTime

#print axioms verifierTransitionDispatchTerminalPrefixValueFrames_eq
#print axioms verifierTransitionDispatchTerminalPrefixValueFrames_computableInPolyTime
