import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionInputCompiler

open CLRS.Chapter34.Turing.CookLevin

#check TransitionStmtTerminal.haltedWire
#check TransitionStmtTerminal.labelWires
#check transitionStmtOutputWires_terminal_status

#print axioms transitionStmtOutputWires_terminal_status
