import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationDescriptorPacketFrames

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.PolyBuilder
open CLRS.Chapter34.Turing.CookLevin

#check rewriteUnaryFrameFixedWidthPackets_encode
#check unaryFrameFixedWidthPacketMark_computableInPolyTime
#check transitionDispatchMuxInvocationDescriptorPacketWidth_pos
#check verifierTransitionDispatchMuxInvocationDescriptorPacketFrames_eq
#check verifierTransitionDispatchMuxInvocationDescriptorPacketFrames_computableInPolyTime

#print axioms rewriteUnaryFrameFixedWidthPackets_encode
#print axioms verifierTransitionDispatchMuxInvocationDescriptorPacketFrames_eq
#print axioms verifierTransitionDispatchMuxInvocationDescriptorPacketFrames_computableInPolyTime
