import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionStatementStackRouteBlockSourceFrames

open CLRS.Chapter34.Turing.CookLevin

#check verifierTransitionStackRouteBlockDescriptorFrames_computableInPolyTime
#check verifierTransitionStackRouteBlockSourceFrames_computableInPolyTime
#check verifierTransitionStackRouteBlockSourceFrames_eq

#print axioms verifierTransitionStackRouteBlockDescriptorFrames_computableInPolyTime
#print axioms verifierTransitionStackRouteBlockSourceFrames_computableInPolyTime
