import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationLabelPacketAssemblerLabel

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.CookLevin

#check transitionDispatchMuxInvocationLabelPacketAssemblerRows
#check transitionDispatchMuxInvocationLabelPacketAssemblerRowsSteps
#check transitionDispatchMuxInvocationLabelPacketAssembler_rows
#check transitionDispatchMuxInvocationLabelPacketAssembler_label

#print axioms transitionDispatchMuxInvocationLabelPacketAssembler_rows
#print axioms transitionDispatchMuxInvocationLabelPacketAssembler_label
