import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorValidityStack

open CLRS.Chapter34
open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.CookLevin

#check arithmeticStackOrdinal
#check arithmeticStackCount
#check arithmeticStackEquiv
#check arithmeticStackOrdinal_equiv_symm
#check arithmeticStackValidityStart
#check arithmeticStackBlockStart
#check arithmeticStackMaskWireBase
#check arithmeticStackMaskOutputWire
#check arithmeticStackBlankWire
#check arithmeticStackMaskOutputWire_eq_trace
#check arithmeticStackMaskWires_eq_range'
#check arithmeticStackMaskGateStream
#check arithmeticStackMaskGateStream_eq_semantic
#check arithmeticStackMaskRev_runFrom
#check arithmeticStackMaskRev_steps_le
#check arithmeticStackBlankWire_eq_row
#check arithmeticStackCellNotGateStream
#check arithmeticStackCellNotGateStream_eq_semantic
#check arithmeticStackCellNotRev_runFrom
#check arithmeticStackCellNotRev_steps_le
#check arithmeticStackCellBoolEqGateStream
#check arithmeticStackCellBoolEqGateStream_eq_semantic
#check arithmeticStackCellBoolEqRev_runFrom
#check arithmeticStackCellBoolEqRev_steps_le
#check arithmeticStackCellGateStream
#check arithmeticStackCellGateStream_eq_semantic
#check arithmeticStackCellGateStream_eq_block
#check arithmeticStackCellFamilyGateStream
#check arithmeticStackCellFamilyGateStream_eq_semantic
#check arithmeticStackGateStream
#check arithmeticStackGateStream_eq_semantic
#check arithmeticStackGateStream_eq_block
#check arithmeticStackFamilyGateStream
#check arithmeticStackFamilyGateStream_eq_semantic
#check arithmeticStackFamilyGateStream_prefix_postHalted
#check arithmeticValidityFinalConjunctionGateStream
#check arithmeticValidityPostHaltedMatch_eq_stack_append_final

#print axioms arithmeticStackMaskOutputWire_eq_trace
#print axioms arithmeticStackMaskWires_eq_range'
#print axioms arithmeticStackMaskGateStream_eq_semantic
#print axioms arithmeticStackMaskRev_runFrom
#print axioms arithmeticStackMaskRev_steps_le
#print axioms arithmeticStackBlankWire_eq_row
#print axioms arithmeticStackCellNotGateStream_eq_semantic
#print axioms arithmeticStackCellNotRev_runFrom
#print axioms arithmeticStackCellNotRev_steps_le
#print axioms arithmeticStackCellBoolEqGateStream_eq_semantic
#print axioms arithmeticStackCellBoolEqRev_runFrom
#print axioms arithmeticStackCellBoolEqRev_steps_le
#print axioms arithmeticStackCellGateStream_eq_semantic
#print axioms arithmeticStackCellGateStream_eq_block
#print axioms arithmeticStackCellFamilyGateStream_eq_semantic
#print axioms arithmeticStackGateStream_eq_semantic
#print axioms arithmeticStackOrdinal_equiv_symm
#print axioms arithmeticStackGateStream_eq_block
#print axioms arithmeticStackFamilyGateStream_eq_semantic
#print axioms arithmeticStackFamilyGateStream_prefix_postHalted
#print axioms arithmeticValidityPostHaltedMatch_eq_stack_append_final
