import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationLabelMajorTrueProgressionFrames

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.CookLevin

#check verifierTransitionDispatchMuxInvocationLabelMajorTrueProgressionFrames_eq
#check verifierTransitionDispatchMuxInvocationLabelMajorTrueProgressionFrames_computableInPolyTime
#print axioms verifierTransitionDispatchMuxInvocationLabelMajorTrueProgressionFrames_eq
