import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionInputCompiler

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.CookLevin

#check transitionSeedFamilyScripts
#check transitionSeedFamilyInput
#check transitionSeedFamilyUnaryInput
#check transitionSeedLocalUnaryInput
#check transitionDispatchListFinalMuxOffset
#check transitionDispatchListOutputWires_eq_finalMux
#check programLabels_nonempty
#check transitionDispatchOutputWires_eq_finalMux
#check TransitionAffineNat
#check transitionCfgBitAffine_eval
#check compileStmtGateAffine_eval
#check transitionDispatchListFinalMuxOffsetAffine_eval
#check transitionDispatchListGateAffine_eval
#check transitionDispatchGateAffine_eval
#check transitionFinalMuxStartForm
#check transitionFinalMuxStartForm_value
#check transitionDispatchOutputWires_eq_affineFinalMux
#check verifierTransitionTailAffineSeeds
#check verifierTransitionTailAffineSeedEncoding_eq
#check verifierTransitionAffineMapFrames
#check verifierTransitionAffineMapFrames_computableInPolyTime
#check verifierTransitionFinalMuxStartFrames
#check verifierTransitionFinalMuxStartFrames_eq_seeds
#check verifierTransitionFinalMuxStartFrames_computableInPolyTime
#check transitionTailPhaseBoundaryForms
#check transitionTailPhaseBoundaryForms_value
#check verifierTransitionTailPhaseBoundaryFrames
#check verifierTransitionTailPhaseBoundaryFrames_eq_seeds
#check verifierTransitionTailPhaseBoundaryFrames_computableInPolyTime
#check transitionOverflowSlot_eq_affine
#check transitionFinalMuxWireForm_value
#check transitionNarrowOverflowWireForms_value
#check transitionNarrowLeftForms
#check transitionNarrowLeftForms_value
#check verifierTransitionNarrowLeftFrames
#check verifierTransitionNarrowLeftFrames_eq_seeds
#check verifierTransitionNarrowLeftFrames_computableInPolyTime
#check transitionNarrowRightSuccForms
#check transitionNarrowRightSuccForms_value
#check verifierTransitionNarrowRightSuccFrames
#check verifierTransitionNarrowRightSuccFrames_eq_seeds
#check verifierTransitionNarrowRightSuccFrames_computableInPolyTime
#check transitionNarrowInvocationDelimiterTable
#check transitionNarrowInvocationForms
#check transitionNarrowInvocationForms_value
#check verifierTransitionNarrowInvocationInput
#check verifierTransitionNarrowInvocationInput_eq_scripts
#check verifierTransitionNarrowInvocationInput_computableInPolyTime
#check transitionEqSegments
#check transitionEqProgressionDescriptorForms_value
#check verifierTransitionEqProgressionDescriptorFrames_eq
#check verifierTransitionEqProgressionDescriptorFrames_computableInPolyTime
#check transitionSeedFamilyUnaryInput_eq_flatMap
#check transitionSeedFamilyInput_eq_map_data
#check verifierTransitionFamilyScripts
#check verifierTransitionFamilyInputTarget
#check verifierTransitionFamilyUnaryInputTarget
#check verifierTransitionFamilyInputTarget_eq_map_data
#check verifierTransitionFamilyUnaryInputTarget_eq_flatMap
#check transitionRowSeedTriples
#check verifierTransitionRowSeedFrames_eq_triples
#check verifierTransitionRowMarkedSeedFrames
#check verifierTransitionRowMarkedSeedFrames_eq_seeds
#check verifierTransitionRowMarkedSeedFrames_computableInPolyTime
#check verifierTransitionFamilyScripts_eq_canonical
#check verifierTransitionFamilyInputTarget_eq_canonical
#check verifierTransitionFamilyGateStream_eq
#check verifierTransitionFamily_run
#check verifierTransitionFamilyInputTarget_computableInPolyTime_of_unaryCompiler
#check verifierTransitionGateStream_computableInPolyTime_of_inputCompiler

#print axioms verifierTransitionFamilyScripts_eq_canonical
#print axioms transitionDispatchOutputWires_eq_finalMux
#print axioms transitionFinalMuxStartForm_value
#print axioms transitionDispatchOutputWires_eq_affineFinalMux
#print axioms verifierTransitionFinalMuxStartFrames_eq_seeds
#print axioms verifierTransitionFinalMuxStartFrames_computableInPolyTime
#print axioms verifierTransitionTailPhaseBoundaryFrames_eq_seeds
#print axioms verifierTransitionTailPhaseBoundaryFrames_computableInPolyTime
#print axioms transitionNarrowLeftForms_value
#print axioms verifierTransitionNarrowLeftFrames_eq_seeds
#print axioms verifierTransitionNarrowLeftFrames_computableInPolyTime
#print axioms transitionNarrowRightSuccForms_value
#print axioms verifierTransitionNarrowRightSuccFrames_eq_seeds
#print axioms verifierTransitionNarrowRightSuccFrames_computableInPolyTime
#print axioms transitionNarrowInvocationForms_value
#print axioms verifierTransitionNarrowInvocationInput_eq_scripts
#print axioms verifierTransitionNarrowInvocationInput_computableInPolyTime
#print axioms transitionEqStackHeightSegment_eval
#print axioms transitionEqStackCellSegment_eval
#print axioms transitionEqSegmentProgression_base₁
#print axioms transitionEqSegmentProgression_base₂
#print axioms transitionEqSegmentProgression_base₃
#print axioms verifierTransitionEqProgressionDescriptorFrames_eq
#print axioms verifierTransitionEqProgressionDescriptorFrames_computableInPolyTime
#print axioms verifierTransitionFamilyInputTarget_eq_canonical
#print axioms verifierTransitionFamilyUnaryInputTarget_eq_flatMap
#print axioms verifierTransitionRowMarkedSeedFrames_eq_seeds
#print axioms verifierTransitionRowMarkedSeedFrames_computableInPolyTime
#print axioms verifierTransitionFamilyGateStream_eq
#print axioms verifierTransitionFamily_run
#print axioms verifierTransitionFamilyInputTarget_computableInPolyTime_of_unaryCompiler
#print axioms verifierTransitionGateStream_computableInPolyTime_of_inputCompiler
