import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionStatementAffineContextRecursiveSegments

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.PolyBuilder
open CLRS.Chapter34.Turing.CookLevin

#check transitionStmtRecursiveBranchMuxInvocationSegments
#check transitionStmtRecursiveBranchMuxInvocationSegments_frames

#print axioms transitionStmtRecursiveBranchMuxInvocationSegments_frames
