import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationDescriptorHalfDuplicate

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.PolyBuilder
open CLRS.Chapter34.Turing.CookLevin

#check verifierTransitionDispatchMuxInvocationDescriptorHalfRowFamily_encoding_eq
#check verifierTransitionDispatchMuxInvocationDescriptorDuplicatedHalfRows_eq
#check verifierTransitionDispatchMuxInvocationDescriptorDuplicatedHalfRows_computableInPolyTime

#print axioms verifierTransitionDispatchMuxInvocationDescriptorHalfRowFamily_encoding_eq
#print axioms verifierTransitionDispatchMuxInvocationDescriptorDuplicatedHalfRows_eq
#print axioms verifierTransitionDispatchMuxInvocationDescriptorDuplicatedHalfRows_computableInPolyTime
