import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionStatementStackRouteAffineSpanBlockFrames

open CLRS.Chapter34.Turing.CookLevin

#check verifierTransitionStackAffineSpanBlockFrames_computableInPolyTime
#check TransitionStmtTerminalRowLayout.stackAffineSpanBlockSegments_values
#check TransitionStmtTerminalRowLayout.verifierStackAffineSpanBlockFrames_eq

#print axioms TransitionStmtTerminalRowLayout.verifierStackAffineSpanBlockFrames_eq
