import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.PolyBuilder.VerifierBodyController

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.PolyBuilder

#check AffineVerifierBodyScript
#check encodeAffineVerifierBodyScript
#check affineVerifierBodyGateStream
#check affineVerifierBodyRevProgram
#check affineVerifierBody_run
#check affineVerifierBody_steps_le
#check affineVerifierBodyRev_computableInPolyTime
#check affineVerifierBodyGateStream_computableInPolyTime

#print axioms affineVerifierBody_run
#print axioms affineVerifierBody_steps_le
#print axioms affineVerifierBodyRev_computableInPolyTime
#print axioms affineVerifierBodyGateStream_computableInPolyTime
