import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionAffineSegmentRows

open CLRS.Chapter34.Turing.CookLevin

#check verifierTransitionAffineSegmentRowFrames_eq
#check verifierTransitionAffineSegmentRowFrames_computableInPolyTime

#print axioms verifierTransitionAffineSegmentRowFrames_eq
#print axioms verifierTransitionAffineSegmentRowFrames_computableInPolyTime
