import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationDescriptorTrueProgressionExecute

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.PolyBuilder
open CLRS.Chapter34.Turing.CookLevin

#check verifierTransitionDispatchMuxInvocationDescriptorTrueRawValueRowGroups
#check verifierTransitionDispatchMuxInvocationDescriptorTrueRawMarkedFrames_eq
#check verifierTransitionDispatchMuxInvocationDescriptorTrueRawMarkedFrames_computableInPolyTime

#print axioms verifierTransitionDispatchMuxInvocationDescriptorTrueRawMarkedFrames_eq
#print axioms verifierTransitionDispatchMuxInvocationDescriptorTrueRawMarkedFrames_computableInPolyTime
