import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationDescriptorPacketDuplicate

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.PolyBuilder
open CLRS.Chapter34.Turing.CookLevin

#check encodeUnaryFrameFixedWidthPacket_eq_body
#check encodeUnaryFrameFixedWidthPacketBody_frameEnd_free
#check verifierTransitionDispatchMuxInvocationDescriptorPacketFamily_encoding_eq
#check verifierTransitionDispatchMuxInvocationDescriptorDuplicatedPacketFrames_eq
#check verifierTransitionDispatchMuxInvocationDescriptorDuplicatedPacketFrames_computableInPolyTime

#print axioms encodeUnaryFrameFixedWidthPacket_eq_body
#print axioms verifierTransitionDispatchMuxInvocationDescriptorPacketFamily_encoding_eq
#print axioms verifierTransitionDispatchMuxInvocationDescriptorDuplicatedPacketFrames_computableInPolyTime
