import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationDescriptorTrueExecute

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.PolyBuilder
open CLRS.Chapter34.Turing.CookLevin

#check transitionDispatchTrueArmSpanDropAmounts_nonempty
#check transitionDispatchTrueArmSpanRawValueRows_length
#check transitionDispatchTrueArmSpanDroppedValueRows_eq
#check verifierTransitionDispatchMuxInvocationDescriptorTrueDroppedSpanMarkedFrames_eq
#check verifierTransitionDispatchMuxInvocationDescriptorTrueValueFrames_eq
#check verifierTransitionDispatchMuxInvocationDescriptorTrueValueFrames_eq_semantic
#check verifierTransitionDispatchMuxInvocationDescriptorTrueValueFrames_computableInPolyTime

#print axioms transitionDispatchTrueArmSpanDroppedValueRows_eq
#print axioms verifierTransitionDispatchMuxInvocationDescriptorTrueDroppedSpanMarkedFrames_eq
#print axioms verifierTransitionDispatchMuxInvocationDescriptorTrueValueFrames_eq
#print axioms verifierTransitionDispatchMuxInvocationDescriptorTrueValueFrames_eq_semantic
#print axioms verifierTransitionDispatchMuxInvocationDescriptorTrueValueFrames_computableInPolyTime
