import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationDescriptorFourWayReverse

namespace CLRS.Chapter34.Turing.CookLevin

#check verifierTransitionDispatchMuxInvocationDescriptorFourWayMarkedFamily
#check verifierTransitionDispatchMuxInvocationDescriptorFourWayMarkedFamily_encoding_eq
#check verifierTransitionDispatchMuxInvocationDescriptorFourWayReversedRows
#check verifierTransitionDispatchMuxInvocationDescriptorFourWayReversedRows_eq
#check verifierTransitionDispatchMuxInvocationDescriptorFourWayReversedRows_computableInPolyTime

#print axioms verifierTransitionDispatchMuxInvocationDescriptorFourWayReversedRows_computableInPolyTime

end CLRS.Chapter34.Turing.CookLevin
