import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationDescriptorFourWayPrefixRoute

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.PolyBuilder
open CLRS.Chapter34.Turing.CookLevin

#check verifierTransitionDispatchMuxInvocationDescriptorFourWayGroups_encoding_eq
#check verifierTransitionDispatchMuxInvocationDescriptorFourWayPrefixRows_eq
#check verifierTransitionDispatchMuxInvocationDescriptorFourWayPrefixRows_computableInPolyTime

#print axioms verifierTransitionDispatchMuxInvocationDescriptorFourWayGroups_encoding_eq
#print axioms verifierTransitionDispatchMuxInvocationDescriptorFourWayPrefixRows_eq
#print axioms verifierTransitionDispatchMuxInvocationDescriptorFourWayPrefixRows_computableInPolyTime
