import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionStatementRecursiveDescriptorSource

open CLRS.Chapter34 Turing
open CLRS.Chapter34.Turing CookLevin PolyBuilder

#check TransitionStmtRecursivePlan.headPhaseForms
#check TransitionStmtRecursivePlan.headFieldForms
#check verifierTransitionStmtRecursiveDescriptorSeedRowSource
#check verifierTransitionStmtRecursiveDescriptorFamily
#check verifierTransitionStmtRecursiveDescriptorFamily_rows
#check verifierTransitionStmtRecursiveDescriptorFamily_computableInPolyTime

#print axioms verifierTransitionStmtRecursiveDescriptorFamily_rows
#print axioms verifierTransitionStmtRecursiveDescriptorFamily_computableInPolyTime
