import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionStatementAffineContextRecursiveOutputRouteSource

open CLRS.Chapter34
open CLRS.Chapter34.Turing.CookLevin

#check transitionStmtRecursivePlan_linearResult_routeBounds
#check TransitionStmtRecursivePlan.linearRouteBounds_of_uniform
#check verifierTransitionStmtOutputRouteFamily_computableInPolyTime_of_uniformPlanBounds
#check verifierTransitionLabelOutputRouteFamily_computableInPolyTime_of_recursivePlan
#print axioms verifierTransitionLabelOutputRouteFamily_computableInPolyTime_of_recursivePlan
