import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationDescriptorHalfRoute

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.PolyBuilder
open CLRS.Chapter34.Turing.CookLevin

#check transitionDispatchMuxInvocationDescriptorValues_eq_head_append_tail
#check verifierTransitionDispatchMuxInvocationDescriptorHalfRouteFamily_encoding_eq
#check verifierTransitionDispatchMuxInvocationDescriptorRoutedPacketFrames_eq
#check verifierTransitionDispatchMuxInvocationDescriptorRoutedPacketFrames_computableInPolyTime
#check verifierTransitionDispatchMuxInvocationDescriptorHalfRows_eq
#check verifierTransitionDispatchMuxInvocationDescriptorHalfRows_computableInPolyTime

#print axioms transitionDispatchMuxInvocationDescriptorValues_eq_head_append_tail
#print axioms verifierTransitionDispatchMuxInvocationDescriptorHalfRouteFamily_encoding_eq
#print axioms verifierTransitionDispatchMuxInvocationDescriptorRoutedPacketFrames_eq
#print axioms verifierTransitionDispatchMuxInvocationDescriptorHalfRows_eq
#print axioms verifierTransitionDispatchMuxInvocationDescriptorHalfRows_computableInPolyTime
