import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.PolyBuilder.AffineExactlyOneMarkedPrefixPayloadSource

open CLRS.Chapter34.Turing.PolyBuilder

#check AffineExactlyOneMarkedPrefixPayloadFamily
#check encodeAffineExactlyOneMarkedPrefixPayloadInput
#check encodeAffineExactlyOneMarkedPrefixPayloadOutput
#check affineExactlyOneMarkedPrefixPayloadRevProgram
#check affineExactlyOneMarkedPrefixPayload_runFrom
#check affineExactlyOneMarkedPrefixPayloadSteps_le
#check affineExactlyOneMarkedPrefixPayloadRev_computableInPolyTime
#check affineExactlyOneMarkedPrefixPayload_computableInPolyTime

#print axioms affineExactlyOneMarkedPrefixPayload_runFrom
#print axioms affineExactlyOneMarkedPrefixPayloadSteps_le
#print axioms affineExactlyOneMarkedPrefixPayloadRev_computableInPolyTime
#print axioms affineExactlyOneMarkedPrefixPayload_computableInPolyTime
