import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorValidityRowTailSource

open CLRS.Chapter34.Turing.CookLevin

#check arithmeticValidityTailFixedOperandForms
#check arithmeticValidityTailFixedOperandValues
#check arithmeticValidityTailFixedOperandForms_eq
#check verifierValidityRowTailFixedOperandFrames_computableInPolyTime
#check arithmeticValidityTailFixedOperandDelimiters_length
#check verifierValidityRowTailMarkedFixedOperandFrames_eq_cycle
#check verifierValidityRowTailMarkedFixedOperandFrames_computableInPolyTime
#check verifierValidityRowTailPayloadFamily_encoding_eq
#check verifierValidityRowTailAffinePayloadFrames_eq_rows
#check verifierValidityRowTailAffinePayloadFrames_computableInPolyTime
#check verifierValidityRowTailSplicedSourceFrames_eq_invocations
#check verifierValidityRowTailSourceInvocationFrames_computableInPolyTime

#print axioms arithmeticValidityTailFixedOperandForms_eq
#print axioms verifierValidityRowTailFixedOperandFrames_computableInPolyTime
#print axioms verifierValidityRowTailMarkedFixedOperandFrames_eq_cycle
#print axioms verifierValidityRowTailMarkedFixedOperandFrames_computableInPolyTime
#print axioms verifierValidityRowTailPayloadFamily_encoding_eq
#print axioms verifierValidityRowTailAffinePayloadFrames_computableInPolyTime
#print axioms verifierValidityRowTailSplicedSourceFrames_eq_invocations
#print axioms verifierValidityRowTailSourceInvocationFrames_computableInPolyTime
