import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationDescriptorSelectorFrames

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.PolyBuilder
open CLRS.Chapter34.Turing.CookLevin

#check verifierTransitionDispatchMuxInvocationDescriptorSelectorMarkedRows_eq
#check verifierTransitionDispatchMuxInvocationDescriptorSelectorFrames_eq
#check verifierTransitionDispatchMuxInvocationDescriptorSelectorFrames_computableInPolyTime

#print axioms verifierTransitionDispatchMuxInvocationDescriptorSelectorMarkedRows_eq
#print axioms verifierTransitionDispatchMuxInvocationDescriptorSelectorFrames_eq
#print axioms verifierTransitionDispatchMuxInvocationDescriptorSelectorFrames_computableInPolyTime
