import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationLabelMajorLabelChannels

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.CookLevin

#check verifierTransitionDispatchMuxInvocationLabelMajorSelectorLabelFrames_eq_channel
#check verifierTransitionDispatchMuxInvocationLabelMajorCoordinateLabelFrames_eq_channel
#check verifierTransitionDispatchMuxInvocationLabelMajorTrueLabelFrames_eq_channel
#check verifierTransitionDispatchMuxInvocationLabelMajorFalseLabelFrames_eq_channel
#check verifierTransitionDispatchMuxInvocationLabelMajorChannelCompilers

#print axioms verifierTransitionDispatchMuxInvocationLabelMajorTrueLabelFrames_eq_channel
#print axioms verifierTransitionDispatchMuxInvocationLabelMajorFalseLabelFrames_eq_channel
