import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationDescriptorTrueFrames

open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.PolyBuilder
open CLRS.Chapter34.Turing.CookLevin

#check verifierTransitionDispatchMuxInvocationDescriptorTrueMarkedRows_eq
#check verifierTransitionDispatchMuxInvocationDescriptorTrueFrames_eq_values
#check verifierTransitionDispatchMuxInvocationDescriptorTrueFrames_eq
#check verifierTransitionDispatchMuxInvocationDescriptorTrueFrames_computableInPolyTime

#print axioms verifierTransitionDispatchMuxInvocationDescriptorTrueMarkedRows_eq
#print axioms verifierTransitionDispatchMuxInvocationDescriptorTrueFrames_eq_values
#print axioms verifierTransitionDispatchMuxInvocationDescriptorTrueFrames_eq
#print axioms verifierTransitionDispatchMuxInvocationDescriptorTrueFrames_computableInPolyTime
