import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionStatementStackRouteStructuredSourceFrames

open CLRS.Chapter34.Turing.CookLevin

#check verifierTransitionStackRouteBlockDescriptorFrames_computableInPolyTime
#check verifierTransitionStackRouteBlockSourceFrames_computableInPolyTime
#check verifierTransitionStackRouteBlockSourceFrames_eq
#check verifierTransitionStackRouteStructuredSourceFrames_eq_source
#check transitionStackRouteStructuredSourceFrames_computableInPolyTime

#print axioms verifierTransitionStackRouteBlockDescriptorFrames_computableInPolyTime
#print axioms verifierTransitionStackRouteBlockSourceFrames_computableInPolyTime
#print axioms transitionStackRouteStructuredSourceFrames_computableInPolyTime
