import CLRSLean.Chapter_22.Section_22_4_Topological_Sort

#check CLRS.Chapter22.Graph.IsDFSTreeEdge
#check CLRS.Chapter22.Graph.IsDFSBackEdge
#check CLRS.Chapter22.Graph.IsDFSForwardEdge
#check CLRS.Chapter22.Graph.IsDFSCrossEdge
#check CLRS.Chapter22.Graph.IsDFSUndirectedTreeEdge
#check CLRS.Chapter22.Graph.IsDFSUndirectedBackEdge
#check CLRS.Chapter22.Graph.DFSEdgeKind
#check CLRS.Chapter22.Graph.HasDFSEdgeKind
#check CLRS.Chapter22.Graph.dfs_self_loop_is_back
#check CLRS.Chapter22.Graph.dfs_edge_classification
#check CLRS.Chapter22.Graph.dfs_edge_classification_unique
#check CLRS.Chapter22.Graph.dfs_edge_not_finishesBeforeDiscovered
#check CLRS.Chapter22.Graph.dfs_tree_or_forward_edge_iff_timestamps
#check CLRS.Chapter22.Graph.dfs_back_edge_iff_timestamps
#check CLRS.Chapter22.Graph.dfs_cross_edge_iff_timestamps
#check CLRS.Chapter22.Graph.dfs_undirected_edge_not_cross
#check CLRS.Chapter22.Graph.dfs_undirected_edge_tree_or_back
#check CLRS.Chapter22.Graph.isDAG_no_dfs_back_edge
#check CLRS.Chapter22.Graph.dfs_finish_time_decreases_on_dag_edge
#check CLRS.Chapter22.Graph.dfsFinishLe
#check CLRS.Chapter22.Graph.dfsFinishLe_iff_le
#check CLRS.Chapter22.Graph.dfsTopologicalSort
#check CLRS.Chapter22.Graph.dfsTopologicalSort_perm
#check CLRS.Chapter22.Graph.dfsTopologicalSort_nodup
#check CLRS.Chapter22.Graph.mem_dfsTopologicalSort_iff
#check CLRS.Chapter22.Graph.dfsTopologicalSort_pairwise_finish_le
#check CLRS.Chapter22.Graph.dfsTopologicalSort_isTopologicalOrder
