import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.PolyBuilder.AffineExactlyOneSeedCarrierNormalizeSource

open CLRS.Chapter34.Turing.PolyBuilder

#check encodeAffineExactlyOneSeedCarrierNormalizedRow
#check encodeAffineExactlyOneSeedCarrierNormalizedFamily
#check affineExactlyOneSeedCarrierNormalizeRevProgram
#check affineExactlyOneSeedCarrierNormalizeRev_run
#check affineExactlyOneSeedCarrierNormalizeRevSteps_le
#check affineExactlyOneSeedCarrierNormalize_computableInPolyTime

#print axioms affineExactlyOneSeedCarrierNormalizeRev_run
#print axioms affineExactlyOneSeedCarrierNormalizeRevSteps_le
#print axioms affineExactlyOneSeedCarrierNormalize_computableInPolyTime
