import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionStatementStackRouteSourceFrames

open CLRS.Chapter34.Turing.CookLevin

#check verifierTransitionStackRouteHeightSourceFrames_computableInPolyTime
#check verifierTransitionStackRouteCellSourceFrames_computableInPolyTime
#check verifierTransitionStackRoutePopHeightSliceFrames_computableInPolyTime
#check verifierTransitionStackRoutePopCellSliceFrames_computableInPolyTime

#print axioms verifierTransitionStackRouteHeightSourceFrames_computableInPolyTime
#print axioms verifierTransitionStackRouteCellSourceFrames_computableInPolyTime
#print axioms verifierTransitionStackRoutePopHeightSliceFrames_computableInPolyTime
#print axioms verifierTransitionStackRoutePopCellSliceFrames_computableInPolyTime
