import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationLabelMajorTrueFrames

open CLRS.Chapter34.Turing.CookLevin

#check transitionDispatchMuxInvocationLabelMajorDescriptorPackets_trueLayouts
#check verifierTransitionDispatchMuxInvocationLabelMajorTrueMarkedRows_eq
#check verifierTransitionDispatchMuxInvocationLabelMajorTrueFrames_eq_existing
#check verifierTransitionDispatchMuxInvocationLabelMajorTrueFrames_computableInPolyTime

#print axioms transitionDispatchMuxInvocationLabelMajorDescriptorPackets_trueLayouts
#print axioms verifierTransitionDispatchMuxInvocationLabelMajorTrueMarkedRows_eq
#print axioms verifierTransitionDispatchMuxInvocationLabelMajorTrueFrames_eq_existing
#print axioms verifierTransitionDispatchMuxInvocationLabelMajorTrueFrames_computableInPolyTime
