import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationLabelMajorCoordinateExecute

open CLRS.Chapter34.Turing.CookLevin

#check verifierTransitionDispatchMuxInvocationLabelMajorFourRowNormalizedFrames_eq
#check verifierTransitionDispatchMuxInvocationLabelMajorCoordinateMarkedRows_eq
#check verifierTransitionDispatchMuxInvocationLabelMajorCoordinateFrames_eq
#check verifierTransitionDispatchMuxInvocationLabelMajorCoordinateProgressionFrames_computableInPolyTime

#print axioms verifierTransitionDispatchMuxInvocationLabelMajorFourRowNormalizedFrames_eq
#print axioms verifierTransitionDispatchMuxInvocationLabelMajorCoordinateMarkedRows_eq
#print axioms verifierTransitionDispatchMuxInvocationLabelMajorCoordinateFrames_eq
#print axioms verifierTransitionDispatchMuxInvocationLabelMajorCoordinateProgressionFrames_computableInPolyTime
