import CLRSLean.Chapter_34.Section_34_5_NP_Complete_Problems.VertexCover.ComplementMachine.NonedgeFilter

open CLRS.Chapter34
open CLRS.Chapter34.Turing
open CLRS.Chapter34.Turing.VertexCover.ComplementMachine.NonedgeFilter

#check inputStream
#check inputStreamComputableInPolyTime
#check batchInputComputableInPolyTime
#check lookupResultsComputableInPolyTime
#check membershipBitsComputableInPolyTime
#check complementEdges_eq_filter

#print axioms inputStreamComputableInPolyTime
#print axioms membershipBitsComputableInPolyTime
#print axioms complementEdges_eq_filter
