import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionStatementStackRouteTerminal

open CLRS.Chapter34.Turing.CookLevin

#check TransitionStmtTerminalRowLayout.stackDescriptorRouteValues_eq
#check TransitionDispatchTrueArmNormalizedLayout.terminalRowDescriptorRoute_eq
#check transitionDispatchTerminalRowDescriptorRoutes_eq

#print axioms TransitionStmtTerminalRowLayout.stackDescriptorRouteValues_eq
#print axioms TransitionDispatchTrueArmNormalizedLayout.terminalRowDescriptorRoute_eq
#print axioms transitionDispatchTerminalRowDescriptorRoutes_eq
