import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationDescriptorLabelPacketChannelReassembly

open CLRS.Chapter34.Turing.CookLevin

#check transitionDispatchMuxInvocationLabelPacketRowsFromChannels
#check transitionDispatchMuxInvocationLabelPacketRowsFromChannels_maps
#check verifierTransitionDispatchMuxInvocationDescriptorLabelPacketChannelFamily
#check verifierTransitionDispatchMuxInvocationDescriptorLabelPacketChannelFamily_encodings
#check TransitionDispatchMuxInvocationLabelPacketChannelFamily.RowAligned
#check verifierTransitionDispatchMuxInvocationDescriptorLabelPacketChannelFamily_rowAligned
#check transitionDispatchMuxInvocationLabelPacketRowsFromChannels_length_of_rowAligned
#check verifierTransitionDispatchMuxInvocationDescriptorLabelPacketFrames_eq_channelReassembly

#print axioms transitionDispatchMuxInvocationLabelPacketRowsFromChannels_maps
#print axioms verifierTransitionDispatchMuxInvocationDescriptorLabelPacketChannelFamily_encodings
#print axioms verifierTransitionDispatchMuxInvocationDescriptorLabelPacketChannelFamily_rowAligned
#print axioms transitionDispatchMuxInvocationLabelPacketRowsFromChannels_length_of_rowAligned
#print axioms verifierTransitionDispatchMuxInvocationDescriptorLabelPacketFrames_eq_channelReassembly
