import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchLayout

open CLRS.Chapter34.Turing.CookLevin

#check TransitionDispatchLabelArtifact
#check TransitionDispatchLabelArtifact.script
#check compileDispatchLabelsListArtifacts
#check compileDispatchLabelsListArtifacts_flatMap_script
#check compileDispatchLabelsListArtifacts_labels_eq
#check compileDispatchArtifacts
#check compileDispatchArtifacts_flatMap_script
#check compileDispatchArtifacts_length
#check transitionDispatchLabelStarts
#check transitionDispatchStarts
#check compileDispatchLabelsListArtifacts_starts_eq
#check arithmeticWidening_dispatchArtifact_starts_eq_seed
#check transitionDispatchSelectors
#check transitionDispatchSelectors_eq
#check compileDispatchLabelsListArtifacts_selectors_eq
#check arithmeticWidening_dispatchArtifact_selectors_eq_seed

#print axioms compileDispatchLabelsListArtifacts_flatMap_script
#print axioms compileDispatchLabelsListArtifacts_labels_eq
#print axioms compileDispatchArtifacts_flatMap_script
#print axioms compileDispatchArtifacts_length
#print axioms compileDispatchLabelsListArtifacts_starts_eq
#print axioms arithmeticWidening_dispatchArtifact_starts_eq_seed
#print axioms compileDispatchLabelsListArtifacts_selectors_eq
#print axioms transitionDispatchSelectors_eq
#print axioms arithmeticWidening_dispatchArtifact_selectors_eq_seed
