import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionTailLayout

open CLRS.Chapter34.Turing.CookLevin

#check TransitionTailLayout
#check transitionScriptTailLayout
#check transitionTailLayoutAt
#check compileTransitionScript_tailLayout_eq
#check compileTransitionFamilyScripts_tailLayouts_eq_ofFn
#check transitionScriptEqRightOperands
#check transitionEqRightOperandsAt
#check compileTransitionFamilyScripts_eqRightOperands_eq_ofFn
#check compileTransitionFamilyScriptsAt_eqRightOperands_eq_ofFn
#check verifierTransitionRowSeeds_expand_eqRightOperands_eq_scripts
#check expandTransitionRowSeedTailLayout
#check verifierTransitionRowSeeds_expand_tailLayouts_eq_scripts

#print axioms compileTransitionScript_tailLayout_eq
#print axioms compileTransitionFamilyScripts_tailLayouts_eq_ofFn
#print axioms compileTransitionFamilyScripts_eqRightOperands_eq_ofFn
#print axioms compileTransitionFamilyScriptsAt_eqRightOperands_eq_ofFn
#print axioms verifierTransitionRowSeeds_expand_eqRightOperands_eq_scripts
#print axioms verifierTransitionRowSeeds_expand_tailLayouts_eq_scripts
