import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationLabelMajorFalseFrames

open CLRS.Chapter34.Turing.CookLevin

#check transitionDispatchMuxInvocationLabelMajorDescriptorPackets_falseProgressions
#check verifierTransitionDispatchMuxInvocationLabelMajorFalseProgressions_eq
#check verifierTransitionDispatchMuxInvocationLabelMajorFalseFrames_eq_existing
#check verifierTransitionDispatchMuxInvocationLabelMajorFalseFrames_computableInPolyTime

#print axioms transitionDispatchMuxInvocationLabelMajorDescriptorPackets_falseProgressions
#print axioms verifierTransitionDispatchMuxInvocationLabelMajorFalseProgressions_eq
#print axioms verifierTransitionDispatchMuxInvocationLabelMajorFalseFrames_eq_existing
#print axioms verifierTransitionDispatchMuxInvocationLabelMajorFalseFrames_computableInPolyTime
