import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionStatementStackRouteDescriptorSelection

open CLRS.Chapter34.Turing.CookLevin

#check transitionStackRouteHeightDescriptorSelection_nonempty
#check transitionStackRouteCellDescriptorSelection_nonempty
#check transitionWidenedFallbackStackSegments_length
#check transitionStackRouteHeightDescriptorSelection_length
#check transitionStackRouteCellDescriptorSelection_length
#check transitionStackRouteHeightDescriptorSelection_progressions_length
#check transitionStackRouteCellDescriptorSelection_progressions_length
#check verifierTransitionStackRouteHeightMarkedDescriptorFrames_eq
#check verifierTransitionStackRouteCellMarkedDescriptorFrames_eq
#check verifierTransitionStackRouteHeightMarkedDescriptorFrames_computableInPolyTime
#check verifierTransitionStackRouteCellMarkedDescriptorFrames_computableInPolyTime

#print axioms verifierTransitionStackRouteHeightMarkedDescriptorFrames_eq
#print axioms verifierTransitionStackRouteCellMarkedDescriptorFrames_eq
#print axioms verifierTransitionStackRouteHeightMarkedDescriptorFrames_computableInPolyTime
#print axioms verifierTransitionStackRouteCellMarkedDescriptorFrames_computableInPolyTime
