import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionStatementAffineContextLinearResultBounds

open CLRS.Chapter34
open CLRS.Chapter34.Turing.CookLevin

#check transitionStmtStackActionPushCountFor_append_singleton
#check transitionStmtLinearResult_pushCount_le_of_budget
#check TransitionStmtLinearResult.routeBounds_of_capacity_pushCount
#check transitionStmtRecursiveContextPadding_linearResult_routeBounds
#print axioms transitionStmtRecursiveContextPadding_linearResult_routeBounds
