import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionStatementAffineContextRecursiveBranchAlignedPacketSource

open CLRS.Chapter34
open CLRS.Chapter34.Turing.CookLevin

#check VerifierTransitionRecursiveStmtPadding
#check verifierTransitionRecursiveBranchAlignedViewFamily
#check verifierTransitionRecursiveBranchAlignedViewFamily_labelPacketFrames
#check verifierTransitionRecursiveBranchAlignedLabelPacketFrames_computableInPolyTime
#print axioms verifierTransitionRecursiveBranchAlignedLabelPacketFrames_computableInPolyTime
