import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionStatementAffineContextOutputRouteSource

open CLRS.Chapter34
open CLRS.Chapter34.Turing.CookLevin

#check verifierTransitionStmtOutputRouteFamily
#check verifierTransitionStmtOutputRouteFamily_encoding_eq_linear
#check verifierTransitionStmtOutputRouteFamily_encoding_eq_branch
#check verifierTransitionStmtOutputRouteFamily_computableInPolyTime
#check verifierTransitionLabelOutputRouteFamily_computableInPolyTime
#print axioms verifierTransitionLabelOutputRouteFamily_computableInPolyTime
