import CLRSLean.Chapter_34.Section_34_4_NP_Completeness_Proofs.CookLevin.Circuitization.GeneratorTransitionDispatchMuxInvocationLabelMajorMarkedDescriptorSemantics

open CLRS.Chapter34.Turing.CookLevin

#check verifierTransitionDispatchMuxInvocationLabelMajorCanonicalMarkedDescriptorFrames
#check verifierTransitionDispatchMuxInvocationLabelMajorMarkedDescriptorFrames_eq_canonical

#print axioms verifierTransitionDispatchMuxInvocationLabelMajorMarkedDescriptorFrames_eq_canonical
