import CLRSLean.Chapter_34.Section_34_5_NP_Complete_Problems.HamiltonianCycle

#check CLRS.Chapter34.Turing.HamiltonianCycle.VerifierMachine.TargetIncrement.incrementTargetField
#check CLRS.Chapter34.Turing.HamiltonianCycle.VerifierMachine.TargetIncrement.incrementTargetField_encode
#check CLRS.Chapter34.Turing.HamiltonianCycle.VerifierMachine.TargetIncrement.computableInPolyTime

#print axioms CLRS.Chapter34.Turing.HamiltonianCycle.VerifierMachine.TargetIncrement.incrementTargetField_encode
#print axioms CLRS.Chapter34.Turing.HamiltonianCycle.VerifierMachine.TargetIncrement.computableInPolyTime
