import CLRSLean.Audit.Axioms
import CLRSLean.FourthEdition.Chapter_04

/-! # Chapter 4 flagship trust surface -/

#check CLRS.Chapter04.strassen_runtime_bigTheta
#check CLRS.Chapter04.continuous_master_case1
#check CLRS.Chapter04.akraBazzi_bigTheta
#check CLRS.Chapter04.akraBazzi_bigTheta_critical
#check CLRS.Chapter04.balancedThreeQuarter_totalCost_le
#check CLRS.Chapter04.unbalancedThirdTwoThird_totalCost
#check CLRS.Chapter04.IntegerBranchingSpec.build_totalCost_eq
#check CLRS.Chapter04.balancedIntegerTree_totalCost_eq
#check CLRS.Chapter04.unbalancedIntegerTree_totalCost_eq
#check CLRS.Chapter04.unbalancedIntegerTree_has_unequal_depth
#check CLRS.Chapter04.balancedIntegerCost_floorRecurrence

#assert_axioms CLRS.Chapter04.strassen_runtime_bigTheta
#assert_axioms CLRS.Chapter04.continuous_master_case1
#assert_axioms CLRS.Chapter04.akraBazzi_bigTheta
#assert_axioms CLRS.Chapter04.akraBazzi_bigTheta_critical
#assert_axioms CLRS.Chapter04.balancedThreeQuarter_totalCost_le
#assert_axioms CLRS.Chapter04.unbalancedThirdTwoThird_totalCost
#assert_axioms CLRS.Chapter04.IntegerBranchingSpec.build_totalCost_eq
#assert_axioms CLRS.Chapter04.balancedIntegerTree_totalCost_eq
#assert_axioms CLRS.Chapter04.unbalancedIntegerTree_totalCost_eq
#assert_axioms CLRS.Chapter04.unbalancedIntegerTree_has_unequal_depth
#assert_axioms CLRS.Chapter04.balancedIntegerCost_floorRecurrence
