import CLRSLean.Chapter_27.Section_27_2_4_Algorithms.ParallelMerge.Costs.Step

/-!
# CLRS Chapter 27.3 — A Three-Quarter Span Envelope

This module solves the recurrence generated by the actual P-MERGE child-size
bound.  Three applications of {lit}`n - n / 4` (rather than two) cross a binary-log
level above the finite base kernel.
-/

namespace CLRS
namespace Chapter27

namespace ParallelMerge
namespace Costs
namespace Span

set_option maxRecDepth 100000

/-- The natural-number three-quarter shrink used by the P-MERGE analysis. -/
def shrink (n : ℕ) : ℕ := n - n / 4

private theorem shrink_lt (n : ℕ) (hn : 64 ≤ n) : shrink n < n := by
  simp only [shrink]
  omega

private theorem shrink_monotone : Monotone shrink := by
  intro a b hab
  simp only [shrink]
  omega

/-- A total recurrence envelope for the span of P-MERGE.  Values below 64
form a finite kernel; larger values pay one logarithmic search level and
recur on the three-quarter bound. -/
def pMergeSpanUpper (n : ℕ) : ℕ :=
  if h : n < 64 then
    64 * (Nat.log 2 n + 1) ^ 2
  else
    pMergeSpanUpper (shrink n) + Nat.log 2 n + 3
termination_by n
decreasing_by
  exact shrink_lt n (by omega)

theorem pMergeSpanUpper_small (n : ℕ) (hn : n < 64) :
    pMergeSpanUpper n = 64 * (Nat.log 2 n + 1) ^ 2 := by
  rw [pMergeSpanUpper]
  simp [hn]

theorem pMergeSpanUpper_large (n : ℕ) (hn : 64 ≤ n) :
    pMergeSpanUpper n =
      pMergeSpanUpper (shrink n) + Nat.log 2 n + 3 := by
  rw [pMergeSpanUpper]
  simp [show ¬n < 64 by omega]

private theorem pMergeSpanUpper_le_succ (n : ℕ) :
    pMergeSpanUpper n ≤ pMergeSpanUpper (n + 1) := by
  induction n using Nat.strong_induction_on with
  | h n ih =>
      by_cases hn : n < 63
      · rw [pMergeSpanUpper_small n (by omega),
          pMergeSpanUpper_small (n + 1) (by omega)]
        have hlog := Nat.log_monotone (b := 2)
          (show n ≤ n + 1 by omega : n ≤ n + 1)
        nlinarith
      · by_cases hn63 : n = 63
        · subst n
          rw [pMergeSpanUpper_small 63 (by omega),
            pMergeSpanUpper_large 64 (by omega),
            show shrink 64 = 48 by norm_num [shrink],
            pMergeSpanUpper_small 48 (by omega)]
          norm_num
        · have hn64 : 64 ≤ n := by omega
          rw [pMergeSpanUpper_large n hn64,
            pMergeSpanUpper_large (n + 1) (by omega)]
          have hs : shrink n ≤ shrink (n + 1) :=
            shrink_monotone (by omega)
          have hs_lt : shrink (n + 1) < n := by
            simp only [shrink]
            omega
          have hupper : pMergeSpanUpper (shrink n) ≤
              pMergeSpanUpper (shrink (n + 1)) := by
            exact Nat.le_induction (m := shrink n)
              (P := fun k _ => k ≤ shrink (n + 1) →
                pMergeSpanUpper (shrink n) ≤ pMergeSpanUpper k)
              (fun _ => le_rfl)
              (fun k _ hk hksucc =>
                (hk (by omega)).trans (ih k (by omega)))
              (shrink (n + 1)) hs le_rfl
          have hlog := Nat.log_monotone (b := 2)
            (show n ≤ n + 1 by omega : n ≤ n + 1)
          omega

/-- The recurrence envelope is monotone in the input-size bound. -/
theorem pMergeSpanUpper_monotone : Monotone pMergeSpanUpper :=
  monotone_nat_of_le_succ pMergeSpanUpper_le_succ

private theorem shrink_three_twice_lt (n : ℕ) (hn : 128 ≤ n) :
    2 * shrink (shrink (shrink n)) < n := by
  simp only [shrink]
  omega

private theorem shrink_three_log (n : ℕ) (hn : 128 ≤ n) :
    Nat.log 2 (shrink (shrink (shrink n))) + 1 ≤ Nat.log 2 n := by
  let p := 2 ^ Nat.log 2 n
  have hn0 : n ≠ 0 := by omega
  have hp_le : p ≤ n := by
    simpa [p] using Nat.pow_log_le_self 2 hn0
  have hn_lt : n < 2 * p := by
    simpa [p, pow_succ, Nat.mul_comm] using
      Nat.lt_pow_succ_log_self (by omega : 1 < 2) n
  have hthree := shrink_three_twice_lt n hn
  have hlt : shrink (shrink (shrink n)) < p := by omega
  have hlog0 : Nat.log 2 n ≠ 0 := by
    have : 7 ≤ Nat.log 2 n := by
      calc
        7 = Nat.log 2 128 := by norm_num
        _ ≤ Nat.log 2 n := Nat.log_monotone hn
    omega
  have := Nat.log_lt_of_lt_pow' hlog0 hlt
  omega

private theorem shrink_lower_64 (n : ℕ) (hn : 128 ≤ n) :
    64 ≤ shrink n ∧ 64 ≤ shrink (shrink n) := by
  simp only [shrink]
  omega

/-- The three-quarter recurrence is bounded by a quadratic binary logarithm.
The proof unfolds exactly three large levels; the third shrink lies below the
current highest power of two. -/
theorem pMergeSpanUpper_le_quadratic (n : ℕ) :
    pMergeSpanUpper n ≤ 64 * (Nat.log 2 n + 1) ^ 2 := by
  induction n using Nat.strong_induction_on with
  | h n ih =>
      by_cases hn64 : n < 64
      · exact (pMergeSpanUpper_small n hn64).le
      · have hn64 : 64 ≤ n := by omega
        by_cases hn128 : n < 128
        · have hlogn : 6 ≤ Nat.log 2 n := by
            calc
              6 = Nat.log 2 64 := by norm_num
              _ ≤ Nat.log 2 n := Nat.log_monotone hn64
          have hs1le : shrink n ≤ n := by simp [shrink]
          have hs2le : shrink (shrink n) ≤ n :=
            (show shrink (shrink n) ≤ shrink n by simp [shrink]).trans hs1le
          have hs3lt64 : shrink (shrink (shrink n)) < 64 := by
            simp only [shrink]
            omega
          rw [pMergeSpanUpper_large n hn64]
          by_cases hs1 : shrink n < 64
          · rw [pMergeSpanUpper_small (shrink n) hs1]
            have hdrop : Nat.log 2 (shrink n) + 1 ≤ Nat.log 2 n := by
              have hchild : Nat.log 2 (shrink n) ≤ Nat.log 2 63 :=
                Nat.log_monotone (by omega)
              norm_num at hchild
              omega
            nlinarith
          · rw [pMergeSpanUpper_large (shrink n) (by omega)]
            by_cases hs2 : shrink (shrink n) < 64
            · rw [pMergeSpanUpper_small (shrink (shrink n)) hs2]
              have hdrop : Nat.log 2 (shrink (shrink n)) + 1 ≤ Nat.log 2 n := by
                have hchild : Nat.log 2 (shrink (shrink n)) ≤ Nat.log 2 63 :=
                  Nat.log_monotone (by omega)
                norm_num at hchild
                omega
              have hlog1 := Nat.log_monotone (b := 2) hs1le
              nlinarith
            · rw [pMergeSpanUpper_large (shrink (shrink n)) (by omega),
                pMergeSpanUpper_small (shrink (shrink (shrink n))) hs3lt64]
              have hdrop : Nat.log 2 (shrink (shrink (shrink n))) + 1 ≤
                  Nat.log 2 n := by
                have hchild : Nat.log 2 (shrink (shrink (shrink n))) ≤
                    Nat.log 2 63 := Nat.log_monotone (by omega)
                norm_num at hchild
                omega
              have hlog1 := Nat.log_monotone (b := 2) hs1le
              have hlog2 := Nat.log_monotone (b := 2) hs2le
              nlinarith
        · have hn128 : 128 ≤ n := by omega
          obtain ⟨hs1, hs2⟩ := shrink_lower_64 n hn128
          rw [pMergeSpanUpper_large n (by omega),
            pMergeSpanUpper_large (shrink n) hs1,
            pMergeSpanUpper_large (shrink (shrink n)) hs2]
          have hs3lt : shrink (shrink (shrink n)) < n := by
            have := shrink_three_twice_lt n hn128
            omega
          have hrec := ih (shrink (shrink (shrink n))) hs3lt
          have hdrop := shrink_three_log n hn128
          have hlog1 : Nat.log 2 (shrink n) ≤ Nat.log 2 n :=
            Nat.log_monotone (show shrink n ≤ n by simp [shrink])
          have hlog2 : Nat.log 2 (shrink (shrink n)) ≤ Nat.log 2 n := by
            exact Nat.log_monotone (b := 2) (le_trans
              (shrink_monotone (show shrink n ≤ n by simp [shrink]))
              (show shrink n ≤ n by simp [shrink]))
          nlinarith

end Span
end Costs
end ParallelMerge

end Chapter27
end CLRS
