#!/usr/bin/env python3
"""Regenerate the per-chapter proof-progress table in README.md.

The table is a pure function of ``docs/clrs-proof-progress.csv`` (the single
source of truth for chapter status and theorem counts).  This script replaces
the block between the BEGIN/END markers in README.md, so status and counts never
drift from the CSV.  It is idempotent.

Usage:  python3 scripts/gen_readme_table.py  [--check]

``--check`` exits non-zero if the README block is out of date (for CI) without
writing.
"""
from __future__ import annotations

import csv
import sys
from pathlib import Path

from check_progress_csv import completed_prefix

ROOT = Path(__file__).resolve().parents[1]
CSV = ROOT / "docs" / "clrs-proof-progress.csv"
README = ROOT / "README.md"

BEGIN = "<!-- BEGIN progress-table (generated by scripts/gen_readme_table.py — do not edit by hand) -->"
END = "<!-- END progress-table -->"
MILESTONE_BEGIN = "<!-- BEGIN milestone-summary (generated by scripts/gen_readme_table.py — do not edit by hand) -->"
MILESTONE_END = "<!-- END milestone-summary -->"
MILESTONE_LAST_CHAPTER = 29

BADGE = {
    "main-proof-complete": "🟢 complete",
    "main-proof-complete-for-correctness": "🟢 correctness",
    "selected-section-complete": "🟡 sections",
    "partial": "🟠 partial",
    "not-started": "⬜ not started",
    "expository": "⚪ guide",
}


def short(text: str, limit: int = 62) -> str:
    text = " ".join(text.split()).rstrip(".")
    if not text or text == "None":
        return "—"
    if len(text) <= limit:
        return text
    return text[: limit - 1].rsplit(" ", 1)[0] + "…"


def build_milestone_block(
    rows: list[dict[str, str]], last_chapter: int = MILESTONE_LAST_CHAPTER
) -> str:
    """Render the completed-prefix milestone without overstating textbook coverage."""
    milestone_rows = completed_prefix(rows, last_chapter)
    proved = sum(int(row["proved_tracked_theorems"]) for row in milestone_rows)
    return "\n".join(
        [
            MILESTONE_BEGIN,
            f"> 🎉 **Milestone: the advertised proof scope of CLRS Chapters 1–{last_chapter} is complete.**",
            f"> All {proved:,} tracked theorem entries across Chapters 1–{last_chapter} are kernel-checked,",
            "> with zero remaining core theorem groups inside those advertised scopes.",
            "> This completion boundary includes selected-section chapters and does not claim every textbook section,",
            "> exercise, chapter-end Problem, pointer/RAM refinement, or floating-point implementation.",
            MILESTONE_END,
        ]
    )


def build_block() -> str:
    rows = list(csv.DictReader(CSV.open(encoding="utf-8")))
    represented = [
        int(r["chapter_no"]) for r in rows if r["repo_status"] != "not-started"
    ]
    last_represented = max(represented)
    lines = [
        BEGIN,
        "",
        "| Ch | Title | Status | Theorems | Core remaining |",
        "|---:|-------|--------|-------:|----------------|",
    ]
    total = 0
    for r in rows:
        ch = int(r["chapter_no"])
        total += int(r["proved_tracked_theorems"])
        if ch > last_represented:
            continue
        status = BADGE.get(r["repo_status"], r["repo_status"])
        remaining = (
            "—"
            if int(r["missing_core_groups"]) == 0
            else short(r["remaining_core_groups"])
        )
        lines.append(
            f"| {ch} | {r['chapter_title']} | {status} | "
            f"{r['proved_tracked_theorems']} | {remaining} |"
        )
    last_chapter = max(int(r["chapter_no"]) for r in rows)
    if last_represented < last_chapter:
        lines.append(
            f"| {last_represented + 1}–{last_chapter} | Remaining chapters | "
            "⬜ not started | 0 | whole chapters |"
        )
    lines += [
        "",
        f"**Total: {total} kernel-checked theorems across Chapters "
        f"1–{last_represented}** "
        "(no `sorry`/`admit`/axiom on `main`).",
        END,
    ]
    return "\n".join(lines)


def main() -> int:
    text = README.read_text(encoding="utf-8")
    markers = (MILESTONE_BEGIN, MILESTONE_END, BEGIN, END)
    if any(marker not in text for marker in markers):
        print(f"ERROR: generated block markers not found in {README}", file=sys.stderr)
        return 2
    rows = list(csv.DictReader(CSV.open(encoding="utf-8")))
    milestone_pre, milestone_rest = text.split(MILESTONE_BEGIN, 1)
    _, milestone_post = milestone_rest.split(MILESTONE_END, 1)
    new = milestone_pre + build_milestone_block(rows) + milestone_post
    table_pre, table_rest = new.split(BEGIN, 1)
    _, table_post = table_rest.split(END, 1)
    new = table_pre + build_block() + table_post

    check = "--check" in sys.argv[1:]
    if new == text:
        print("README progress table is up to date.")
        return 0
    if check:
        print("README progress table is OUT OF DATE (run scripts/gen_readme_table.py).", file=sys.stderr)
        return 1
    README.write_text(new, encoding="utf-8")
    print("Rewrote README progress table from clrs-proof-progress.csv.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
