#!/usr/bin/env python3
"""Regenerate the per-chapter proof-progress table in README.md.

The table is a pure function of ``docs/clrs-proof-progress.csv`` (the source of
truth for chapter status and theorem counts, interpreted through the edition
map).  This script replaces
the block between the BEGIN/END markers in README.md, so status and counts never
drift from the CSV.  It is idempotent.

Usage:  python3 scripts/gen_readme_table.py  [--check]

``--check`` exits non-zero if the README block is out of date (for CI) without
writing.
"""
from __future__ import annotations

import csv
import sys
from pathlib import Path

from online_material import online_tracked_total

ROOT = Path(__file__).resolve().parents[1]
CSV = ROOT / "docs" / "clrs-proof-progress.csv"
README = ROOT / "README.md"

BEGIN = "<!-- BEGIN progress-table (generated by scripts/gen_readme_table.py — do not edit by hand) -->"
END = "<!-- END progress-table -->"
SNAPSHOT_BEGIN = "<!-- BEGIN edition-summary (generated by scripts/gen_readme_table.py — do not edit by hand) -->"
SNAPSHOT_END = "<!-- END edition-summary -->"
ONLINE_MATERIAL_TRACKED_THEOREMS = online_tracked_total()

BADGE = {
    "main-proof-complete": "🟢 complete",
    "main-proof-complete-for-correctness": "🟢 correctness",
    "selected-section-complete": "🟡 sections",
    "partial": "🟠 partial",
    "not-started": "⬜ not started",
    "expository": "⚪ guide",
}


def short(text: str, limit: int = 62) -> str:
    text = " ".join(text.split()).rstrip(".")
    if not text or text == "None":
        return "—"
    if len(text) <= limit:
        return text
    return text[: limit - 1].rsplit(" ", 1)[0] + "…"


def build_snapshot_block(
    rows: list[dict[str, str]],
    online_material_theorems: int = ONLINE_MATERIAL_TRACKED_THEOREMS,
) -> str:
    """Render the fourth-edition snapshot without imposing a completed prefix."""
    represented = sum(
        row["represented_sections"].lower() != "none" for row in rows
    )
    proved = sum(int(row["proved_tracked_theorems"]) for row in rows)
    return "\n".join(
        [
            SNAPSHOT_BEGIN,
            "> **Fourth-edition snapshot.**",
            f"> {represented} of {len(rows)} chapters have canonical represented content.",
            f"> {proved:,} proved source-inventory entries are mapped into the fourth-edition ledger.",
            f"> {online_material_theorems:,} additional entries remain available through the",
            "> machine-readable online-material catalog. They are disjoint from the canonical chapter counts;",
            "> compatibility imports do not duplicate either ledger.",
            SNAPSHOT_END,
        ]
    )


def build_block_from_rows(rows: list[dict[str, str]]) -> str:
    lines = [
        BEGIN,
        "",
        "| Ch | Title | Status | Theorems | Core remaining |",
        "|---:|-------|--------|-------:|----------------|",
    ]
    total = 0
    for r in rows:
        ch = int(r["chapter_no"])
        total += int(r["proved_tracked_theorems"])
        status = BADGE.get(r["repo_status"], r["repo_status"])
        remaining = (
            "—"
            if int(r["missing_core_groups"]) == 0
            else short(r["remaining_core_groups"])
        )
        lines.append(
            f"| {ch} | {r['chapter_title']} | {status} | "
            f"{r['proved_tracked_theorems']} | {remaining} |"
        )
    represented = sum(r["repo_status"] != "not-started" for r in rows)
    lines += [
        "",
        f"**Total: {total} kernel-checked theorem entries across {represented} "
        "represented fourth-edition chapters** "
        "(no `sorry`/`admit`/axiom on `main`).",
        END,
    ]
    return "\n".join(lines)


def build_block() -> str:
    rows = list(csv.DictReader(CSV.open(encoding="utf-8")))
    return build_block_from_rows(rows)


def main() -> int:
    text = README.read_text(encoding="utf-8")
    markers = (SNAPSHOT_BEGIN, SNAPSHOT_END, BEGIN, END)
    if any(marker not in text for marker in markers):
        print(f"ERROR: generated block markers not found in {README}", file=sys.stderr)
        return 2
    rows = list(csv.DictReader(CSV.open(encoding="utf-8")))
    snapshot_pre, snapshot_rest = text.split(SNAPSHOT_BEGIN, 1)
    _, snapshot_post = snapshot_rest.split(SNAPSHOT_END, 1)
    new = snapshot_pre + build_snapshot_block(rows) + snapshot_post
    table_pre, table_rest = new.split(BEGIN, 1)
    _, table_post = table_rest.split(END, 1)
    new = table_pre + build_block() + table_post

    check = "--check" in sys.argv[1:]
    if new == text:
        print("README progress table is up to date.")
        return 0
    if check:
        print("README progress table is OUT OF DATE (run scripts/gen_readme_table.py).", file=sys.stderr)
        return 1
    README.write_text(new, encoding="utf-8")
    print("Rewrote README progress table from clrs-proof-progress.csv.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
