#!/usr/bin/env python3
"""Regenerate the per-chapter proof-progress table in README.md.

The table is a pure function of ``docs/clrs-proof-progress.csv`` (the single
source of truth for chapter status and theorem counts).  This script replaces
the block between the BEGIN/END markers in README.md, so status and counts never
drift from the CSV.  It is idempotent.

Usage:  python3 scripts/gen_readme_table.py  [--check]

``--check`` exits non-zero if the README block is out of date (for CI) without
writing.
"""
from __future__ import annotations

import csv
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CSV = ROOT / "docs" / "clrs-proof-progress.csv"
README = ROOT / "README.md"

BEGIN = "<!-- BEGIN progress-table (generated by scripts/gen_readme_table.py — do not edit by hand) -->"
END = "<!-- END progress-table -->"

BADGE = {
    "main-proof-complete": "🟢 complete",
    "main-proof-complete-for-correctness": "🟢 correctness",
    "selected-section-complete": "🟡 sections",
    "partial": "🟠 partial",
    "not-started": "⬜ not started",
    "expository": "⚪ guide",
}


def short(text: str, limit: int = 62) -> str:
    text = " ".join(text.split()).rstrip(".")
    if not text or text == "None":
        return "—"
    if len(text) <= limit:
        return text
    return text[: limit - 1].rsplit(" ", 1)[0] + "…"


def build_block() -> str:
    rows = list(csv.DictReader(CSV.open(encoding="utf-8")))
    lines = [
        BEGIN,
        "",
        "| Ch | Title | Status | Theorems | Core remaining |",
        "|---:|-------|--------|-------:|----------------|",
    ]
    total = 0
    for r in rows:
        ch = int(r["chapter_no"])
        total += int(r["proved_tracked_theorems"])
        if ch >= 25:
            continue
        status = BADGE.get(r["repo_status"], r["repo_status"])
        remaining = short(r["remaining_core_groups"])
        lines.append(
            f"| {ch} | {r['chapter_title']} | {status} | "
            f"{r['proved_tracked_theorems']} | {remaining} |"
        )
    lines.append(
        "| 25–35 | All-Pairs SP, Max-Flow, … | ⬜ not started | 0 | "
        "whole chapters (Ch25/26 issues filed) |"
    )
    lines += [
        "",
        f"**Total: {total} kernel-checked theorems across Chapters 1–24** "
        "(no `sorry`/`admit`/axiom on `main`).",
        END,
    ]
    return "\n".join(lines)


def main() -> int:
    text = README.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        print(f"ERROR: markers not found in {README}", file=sys.stderr)
        return 2
    pre, rest = text.split(BEGIN, 1)
    _, post = rest.split(END, 1)
    new = pre + build_block() + post

    check = "--check" in sys.argv[1:]
    if new == text:
        print("README progress table is up to date.")
        return 0
    if check:
        print("README progress table is OUT OF DATE (run scripts/gen_readme_table.py).", file=sys.stderr)
        return 1
    README.write_text(new, encoding="utf-8")
    print("Rewrote README progress table from clrs-proof-progress.csv.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
