import CLRSLean.Chapter_34.Section_34_5_NP_Complete_Problems.HamiltonianCycle.ReductionMachine.Header
import CLRSLean.Chapter_34.Section_34_5_NP_Complete_Problems.HamiltonianCycle.ReductionMachine.WidgetEdges.Formatter
import CLRSLean.Chapter_34.Section_34_5_NP_Complete_Problems.HamiltonianCycle.ReductionMachine.NondegeneratePrefix
import CLRSLean.Chapter_34.Section_34_5_NP_Complete_Problems.HamiltonianCycle.ReductionMachine.SelectorClique.Formatter
import CLRSLean.Chapter_34.Section_34_5_NP_Complete_Problems.HamiltonianCycle.ReductionMachine.Incidence.Scanner.Runtime

/-!
# Fixed VERTEX-COVER to HAM-CYCLE reduction machinery

Exports the verified fixed-machine stages used to compute the total raw
reduction.  The nondegenerate target header, all fourteen internal gadget
edges per source-edge occurrence, and the complete selector clique are now
generated by fixed polynomial-time TM2s.  The shared incidence stage now also
has a fixed polynomial-time scanner from the raw VERTEX-COVER encoding to the
canonical per-vertex occurrence rows.  The remaining incidence-chain and
selector-endpoint formatters, followed by guarded total composition, are
assembled incrementally from similarly small modules.
-/
