import CLRSLean.Chapter_34.Section_34_5_NP_Complete_Problems.HamiltonianCycle.ReductionMachine.Header
import CLRSLean.Chapter_34.Section_34_5_NP_Complete_Problems.HamiltonianCycle.ReductionMachine.WidgetEdges.Formatter
import CLRSLean.Chapter_34.Section_34_5_NP_Complete_Problems.HamiltonianCycle.ReductionMachine.NondegeneratePrefix

/-!
# Fixed VERTEX-COVER to HAM-CYCLE reduction machinery

Exports the verified fixed-machine stages used to compute the total raw
reduction.  The nondegenerate target header and all fourteen internal gadget
edges per source-edge occurrence are now generated by fixed polynomial-time
TM2s.  The remaining edge families and guarded total composition are
assembled incrementally from similarly small modules.
-/
