import CLRSLean.ProofPatterns
import CLRSLean.Probability
import CLRSLean.FourthEdition
import CLRSLean.OnlineMaterial
import CLRSLean.Chapter_01
import CLRSLean.Chapter_02
import CLRSLean.Chapter_03
import CLRSLean.Chapter_04
import CLRSLean.Chapter_05
import CLRSLean.Chapter_06
import CLRSLean.Chapter_07
import CLRSLean.Chapter_08
import CLRSLean.Chapter_09
import CLRSLean.Chapter_10
import CLRSLean.Chapter_11
import CLRSLean.Chapter_12
import CLRSLean.Chapter_13
import CLRSLean.Chapter_14
import CLRSLean.Chapter_15
import CLRSLean.Chapter_16
import CLRSLean.Chapter_17
import CLRSLean.Chapter_18
import CLRSLean.Chapter_19
-- Keep registered Chapter 19 compatibility pages in Verso's module set while
-- the chapter aggregator itself exposes only canonical textbook sections.
import CLRSLean.Chapter_19.Section_19_1_Fibonacci_Heap_Model.S1_ExecutableFibHeap
import CLRSLean.Chapter_19.Section_19_1_Fibonacci_Heap_Model.S2_CascadingCuts
import CLRSLean.Chapter_19.Section_19_1_Fibonacci_Heap_Model.S3_AmortizedCosts
import CLRSLean.Chapter_20
import CLRSLean.Chapter_21
import CLRSLean.Chapter_22
import CLRSLean.Chapter_23
import CLRSLean.Chapter_24
import CLRSLean.Chapter_25
import CLRSLean.Chapter_26
import CLRSLean.Chapter_27
import CLRSLean.Chapter_28
import CLRSLean.Chapter_29
import CLRSLean.Chapter_30
import CLRSLean.Chapter_31
import CLRSLean.Chapter_32
import CLRSLean.Chapter_33
import CLRSLean.Chapter_34
import CLRSLean.Extensions
import CLRSLean.Progress
import CLRSLean.Status
import CLRSLean.Workflow

/-!
# CLRS-Lean

CLRS-Lean is a fourth-edition-primary Lean 4 companion for CLRS
(*Introduction to Algorithms*), organized by chapter and section.  Canonical
chapter guides are `CLRSLean.FourthEdition.Chapter_NN`; unqualified
`CLRSLean.Chapter_NN` modules retain their third-edition meanings during the
compatibility period.  The website is generated by **Verso**, the same literate
programming tool used by `teorth/analysis`.  Every `.lean` file is rendered as a
book-quality web page.

The public project name is `CLRS-Lean`.  The Lean library root remains
`CLRSLean`, because Lean import paths use identifier-like module names.

## Repository shape

- `CLRSLean.lean` — top-level entry + Verso landing page
- `CLRSLean/FourthEdition.lean` — canonical fourth-edition chapter tree
- `CLRSLean/FourthEdition/Chapter_02.lean` — canonical guide/facade
- `CLRSLean/OnlineMaterial.lean` — retained online/supplementary catalog
- `CLRSLean/ProofPatterns/` — reusable cross-chapter proof APIs
- `CLRSLean/Chapter_02.lean` — compatibility source guide/aggregator
- `CLRSLean/Chapter_02/Section_02_1_Insertion_Sort.lean` — section module
- `lakefile.lean` — Lake build config (Lean DSL)
- `literate.toml` — Verso module ordering + titles
- `lean-toolchain` — Lean version pin
- `docs/clrs-fourth-edition-map.csv` — canonical edition/section/source bridge
- `docs/clrs-proof-progress.csv` — chapter-level status source
- `docs/scope.md` — advertised project boundary
- `docs/migrations/clrs4.md` — import and deprecation policy
- `docs/proof-patterns/` — reusable proof-engineering lessons
- `Tests/` — interface and closure tests
- `scripts/check_repository.py` — fast repository-wide checks

## Build commands

- `uv sync --frozen` — prepare the Python helper environment
- `uv run python scripts/check_repository.py` — run repository checks

### Single-file proof development (fast feedback)

Use the lightest command that answers your question.  Full details in
`docs/build-and-agents.md`.

| Situation | Command |
|---|---|
| Checking a single proof compiles | `lake lean <file>` |
| Checking + caching olean | `lake build +<Module.Path>` |
| Quick re-check after small edit | `lake build --old CLRSLean` |
| Full check before committing | `lake build CLRSLean` |
| Lakefile / dependency changes | `lake build --reconfigure CLRSLean` |
| Suspect stale trace / weird error | `lake build --rehash CLRSLean` |
| Build Verso website (publishing tasks only) | four-shard runbook in `docs/site-architecture.md` |
| Build doc-gen4 API docs | `lake -R -Kenv=dev build CLRSLean:docs` |

**Typical latency** (warm build, single-file edit): `lake lean <file>` ≈ 5 s,
`lake build --old` ≈ 3 s, full `lake build` ≈ 6 s.

### Proof work versus website publishing

Chapter and theorem implementation does not authorize website generation or
deployment.  During proof work, keep `literate.toml`, module documentation, and
the source navigation metadata consistent, and run the repository/site
configuration checks.  Do not run `lake build :literateHtml`, prepare or
optimize generated HTML, inspect the live site, or deploy the site unless the
user explicitly requests a publishing, release, or website task.

`lake build CLRSLean` remains the full proof-build gate.  Generated HTML and a
live deployment are not prerequisites for declaring a proof milestone complete.

## Parallel agents & build infrastructure

Fanning out subagents on Lean work? Read `docs/build-and-agents.md`.  The rules
that keep it fast and non-destructive:

- **Provision isolated worktrees with `scripts/setup-worktree.sh <branch>`** (or
  `scripts/provision-fleet.sh` for a batch).  Each gets its own warm, prebuilt
  `.lake`, so `lake build` is a fast incremental compile.
- **Never run `lake exe cache get` in a provisioned worktree.**  Mathlib is
  already there; concurrent cache-gets exhaust RAM and corrupt the shared build.
- **Keep build concurrency ≤ 3–4.**  The machine is RAM-bound (~30G), not CPU
  (32 cores); one `lake build` already uses every core.
- **Verify before merging agent proof work** (`-Dwarn.sorry=false` means a clean
  build is *not* sorry-proof): `grep` for `sorry`/`admit`; `#print axioms` on the
  headline theorem must show only `propext/Classical.choice/Quot.sound` (no
  `sorryAx`); check no public declaration was removed/weakened; regenerate
  `CLRSLean/Progress.lean` from the CSV (`check_progress_csv.py --write-dashboard`)
  rather than hand-merging it.
- **GitHub hygiene:** create labels before issues; have agents commit early/often.
- Recover a corrupted `.lake` with `scripts/refresh-golden.sh`.

## Sources of Truth

| Question | Canonical source |
| --- | --- |
| What Lean modules exist? | `CLRSLean/`, checked against `literate.toml` |
| What does a chapter number mean? | `docs/clrs-fourth-edition-map.csv` |
| What is the public theorem interface? | Section `.lean` files and `Tests/` |
| What is the chapter-level progress snapshot? | `docs/clrs-proof-progress.csv` |
| What boundary does the project advertise? | `docs/scope.md` |
| What should be worked on next? | GitHub issues |
| What appears on the website? | `CLRSLean.lean`, chapter guides, and `literate.toml` |

## Navigation

* {lit}`CLRSLean/FourthEdition.lean`: canonical fourth-edition chapter tree.
* {lit}`CLRSLean/Chapter_NN.lean`: third-edition compatibility guides.
* {lit}`CLRSLean/Chapter_NN/Section_NN_NN_*.lean`: theorem-bearing sources.
* {lit}`CLRSLean/Progress.lean`: generated progress dashboard.
* {lit}`CLRSLean/Status.lean`: reader-facing proof status.
* {lit}`CLRSLean/Workflow.lean`: contributor workflow.
* {lit}`Tests/Chapter_XX_Interface.lean`: public interface checks.

Chapter guides aggregate section modules.  Section modules own formal facts.
Interface tests protect the public surface.  Progress prose never replaces a
kernel-checked theorem.

## Verification

For local repository checks:

* {lit}`uv run python scripts/check_repository.py`
* {lit}`lake build CLRSLean`

For a reader-facing or navigation change, also build the Verso site:

Run {lit}`lake build :literateHtml`.

Generated HTML is deployed by GitHub Actions and is not committed as source.
-/